(function(){
if(window.__cvAnalyticsInstalled)return;window.__cvAnalyticsInstalled=true;
const URL='https://rtyiqggxruwejqqyqtmv.supabase.co';
const KEY='sb_publishable_BxkgX1XJz8o_PsTb_LcVDQ_7DR6oHOk';
const VISITOR_KEY='cv2-anon-visitor-id';
const SESSION_KEY='cv2-analytics-session-id';
let client=null,analyticsAllowed=false;
const el=id=>document.getElementById(id);
function rid(){return (typeof crypto!=='undefined'&&crypto.randomUUID)?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function visitorId(){let v='';try{v=localStorage.getItem(VISITOR_KEY)||'';if(!v){v=rid();localStorage.setItem(VISITOR_KEY,v)}}catch{v=rid()}return v}
function sessionId(){let v='';try{v=sessionStorage.getItem(SESSION_KEY)||'';if(!v){v=rid();sessionStorage.setItem(SESSION_KEY,v)}}catch{v=rid()}return v}
function safeNum(v){const n=Number(v);return Number.isFinite(n)?n:0}
function findFarmSection(title){return [...document.querySelectorAll('.farm-menu-section')].find(s=>s.querySelector('h3')?.textContent.trim()===title)}
function ensureButton(){if(!analyticsAllowed||el('cvAnalyticsMenuBtn'))return;const section=findFarmSection('More');const grid=section?.querySelector('.farm-menu-grid');if(!grid)return;const b=document.createElement('button');b.id='cvAnalyticsMenuBtn';b.type='button';b.className='softbtn';b.textContent='Admin Analytics';b.onclick=()=>{if(typeof window.closeFarmMenu==='function')window.closeFarmMenu();openAnalytics()};grid.appendChild(b)}
function injectModal(){if(el('cvAnalyticsModal'))return;const m=document.createElement('div');m.id='cvAnalyticsModal';m.className='modal hidden';m.innerHTML=`<div class="sheet analytics-sheet"><div class="row"><div><h2>Admin Analytics</h2><div class="muted">App visits and Cloud sign-in activity.</div></div><button class="softbtn" id="cvAnalyticsClose">Close</button></div><div id="cvAnalyticsBody"><div class="muted" style="padding:18px 0">Loading analytics…</div></div></div>`;document.body.appendChild(m);el('cvAnalyticsClose').onclick=()=>m.classList.add('hidden')}
function card(label,value,sub=''){return `<div class="analytics-card"><span>${label}</span><b>${safeNum(value).toLocaleString()}</b>${sub?`<small>${sub}</small>`:''}</div>`}
function render(data){const body=el('cvAnalyticsBody');if(!body)return;const recent=data?.most_recent_visit?new Date(data.most_recent_visit).toLocaleString():'No tracked visits yet';body.innerHTML=`<div class="analytics-group"><h3>Cloud Accounts</h3><div class="analytics-grid">${card('Registered users',data.registered_users)}${card('Signed in • 24h',data.signed_in_users_24h)}${card('Signed in • 7 days',data.signed_in_users_7d)}${card('Signed in • 30 days',data.signed_in_users_30d)}</div><div class="analytics-note">Login sessions in the last 24 hours: <b>${safeNum(data.login_sessions_24h).toLocaleString()}</b></div></div><div class="analytics-group"><h3>Anonymous / Website Use</h3><div class="analytics-grid">${card('Anonymous browsers • 24h',data.anonymous_browsers_24h)}${card('Anonymous browsers • 7 days',data.anonymous_browsers_7d)}${card('Anonymous browsers • 30 days',data.anonymous_browsers_30d)}${card('Unique browsers tracked',data.unique_browsers_lifetime)}</div><div class="analytics-grid analytics-secondary">${card('Visit sessions • 24h',data.sessions_24h)}${card('Visit sessions • 7 days',data.sessions_7d)}${card('Visit sessions • 30 days',data.sessions_30d)}</div><div class="analytics-note">Most recent tracked visit: <b>${recent}</b></div></div><div class="notice analytics-privacy"><b>Privacy-friendly counting</b><br>This counter stores a random browser ID and session ID. It does not store cattle-record text, names, or an IP address in the analytics tables. A “browser” is an estimate of a person/device, not a guaranteed unique human.</div><div class="muted analytics-start">Anonymous counting starts with Cattle Vision v2.7, so older anonymous visits cannot be backfilled.</div><button class="softbtn analytics-refresh" id="cvAnalyticsRefresh">Refresh Analytics</button>`;el('cvAnalyticsRefresh').onclick=refreshAnalytics}
async function refreshAnalytics(){if(!client)return;const body=el('cvAnalyticsBody');if(body)body.innerHTML='<div class="muted" style="padding:18px 0">Refreshing analytics…</div>';const {data,error}=await client.rpc('get_app_analytics');if(error){analyticsAllowed=false;if(body)body.innerHTML='<div class="notice">Admin analytics are only available to a farm owner or admin.</div>';return}analyticsAllowed=true;ensureButton();render(data||{})}
async function openAnalytics(){injectModal();el('cvAnalyticsModal').classList.remove('hidden');await refreshAnalytics()}
window.openAnalytics=openAnalytics;
async function recordVisit(){if(!client)return;try{await client.rpc('record_app_visit',{p_visitor_id:visitorId(),p_session_id:sessionId(),p_path:location.pathname||'/'});}catch(e){console.warn('Visit counter unavailable',e)}}
async function recordLogin(){if(!client)return;try{const {data}=await client.auth.getSession();if(data.session?.user)await client.rpc('record_app_login',{p_session_id:sessionId()})}catch(e){console.warn('Login counter unavailable',e)}}
async function checkAdmin(){if(!client)return;const {data,error}=await client.rpc('get_app_analytics');if(!error){analyticsAllowed=true;ensureButton();if(el('cvAnalyticsModal')&&!el('cvAnalyticsModal').classList.contains('hidden'))render(data||{})}}
function start(){if(!window.supabase?.createClient)return setTimeout(start,250);client=window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});injectModal();recordVisit();recordLogin();checkAdmin();client.auth.onAuthStateChange((event,session)=>{if(session?.user){recordLogin();setTimeout(checkAdmin,150)}else{analyticsAllowed=false;el('cvAnalyticsMenuBtn')?.remove()}});setInterval(ensureButton,1000)}
start();
})();