const $=id=>document.getElementById(id);let cattle=JSON.parse(localStorage.getItem('cv2-cattle')||localStorage.getItem('cattleVision')||'[]');let pending={photos:[],videos:[]},currentId=null,db=null;
function norm(a){a.id=a.id||Date.now()+Math.random();a.tag=String(a.tag||'');a.sex=a.sex||'Cow';a.breed=a.breed||'';a.location=a.location||'';a.dam=a.dam||'';a.sire=a.sire||'';a.status=a.status||'Unknown';a.flag=a.flag||'Normal';a.notes=a.notes||'';a.breeding=Array.isArray(a.breeding)?a.breeding:[];a.calvings=Array.isArray(a.calvings)?a.calvings:[];a.health=Array.isArray(a.health)?a.health:[];return a}cattle=cattle.map(norm);save();
function save(){localStorage.setItem('cv2-cattle',JSON.stringify(cattle));render()}
function openDB(){return new Promise((res,rej)=>{let r=indexedDB.open('cv2-media',1);r.onupgradeneeded=()=>{let d=r.result;if(!d.objectStoreNames.contains('media')){let s=d.createObjectStore('media',{keyPath:'id'});s.createIndex('animalId','animalId')}};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function getMedia(animalId){if(!db)return[];return new Promise((res,rej)=>{let tx=db.transaction('media','readonly').objectStore('media').index('animalId').getAll(IDBKeyRange.only(String(animalId)));tx.onsuccess=()=>res(tx.result||[]);tx.onerror=()=>rej(tx.error)})}
function cloudMediaChanged(){window.dispatchEvent(new Event('cv-local-change'))}
function putMedia(m){return new Promise((res,rej)=>{let r=db.transaction('media','readwrite').objectStore('media').put(m);r.onsuccess=()=>{cloudMediaChanged();res()};r.onerror=()=>rej(r.error)})}
function deleteMediaFor(id){return new Promise((res,rej)=>{let store=db.transaction('media','readwrite').objectStore('media'),idx=store.index('animalId'),cur=idx.openCursor(IDBKeyRange.only(String(id)));cur.onsuccess=e=>{let c=e.target.result;if(c){c.delete();c.continue()}else{cloudMediaChanged();res()}};cur.onerror=()=>rej(cur.error)})}
async function compressPhoto(file){return new Promise((res,rej)=>{let u=URL.createObjectURL(file),im=new Image;im.onload=()=>{let s=Math.min(1,1600/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*s);c.height=Math.round(im.height*s);c.getContext('2d').drawImage(im,0,0,c.width,c.height);URL.revokeObjectURL(u);res(c.toDataURL('image/jpeg',.82))};im.onerror=rej;im.src=u})}
async function savePendingMedia(animalId){if(!db)return;for(let f of pending.photos){let data=await compressPhoto(f);await putMedia({id:crypto.randomUUID(),animalId:String(animalId),type:'photo',data,created:new Date().toISOString()})}for(let f of pending.videos){try{await putMedia({id:crypto.randomUUID(),animalId:String(animalId),type:'video',blob:f,created:new Date().toISOString()})}catch(e){alert('Animal saved, but this video is too large for browser storage. Cloud video storage will fix this later.')}}pending={photos:[],videos:[]}}
function mediaPreview(){let html='';if(pending.photos[0])html+=`<img class="preview" src="${URL.createObjectURL(pending.photos[0])}">`;if(pending.videos[0])html+=`<video class="preview" src="${URL.createObjectURL(pending.videos[0])}" controls></video>`;return html}
function openAdd(){pending={photos:[],videos:[]};$('pendingPreview').innerHTML='<div class="notice">Optional: choose or take a photo/video first, then fill in the tag.</div>';$('addModal').classList.remove('hidden')}
function openAddWithMedia(type,files){pending={photos:[],videos:[]};pending[type]=Array.from(files||[]);$('pendingPreview').innerHTML=mediaPreview();$('addModal').classList.remove('hidden')}
function closeAdd(){$('addModal').classList.add('hidden');['aTag','aBreed','aBirth','aLocation','aReg','aDam','aSire','aNotes'].forEach(x=>$(x).value='');pending={photos:[],videos:[]}}
$('photoCamera').onchange=e=>openAddWithMedia('photos',e.target.files);$('photoInput').onchange=e=>openAddWithMedia('photos',e.target.files);$('videoCamera').onchange=e=>openAddWithMedia('videos',e.target.files);$('videoInput').onchange=e=>openAddWithMedia('videos',e.target.files);
async function saveNewAnimal(){let tag=$('aTag').value.trim();if(!tag)return alert('Enter a tag number.');if(cattle.some(a=>a.tag.toLowerCase()==tag.toLowerCase()))return alert('That tag already exists. Open that animal to add media.');let a=norm({id:Date.now()+Math.random(),tag,sex:$('aSex').value,breed:$('aBreed').value.trim(),birth:$('aBirth').value,location:$('aLocation').value.trim(),registration:$('aReg').value.trim(),dam:$('aDam').value.trim(),sire:$('aSire').value.trim(),notes:$('aNotes').value.trim(),created:new Date().toISOString()});cattle.push(a);save();try{await savePendingMedia(a.id)}catch(e){console.error(e)}closeAdd();render();alert('Animal saved.')}
async function render(){let q=$('search')?.value.toLowerCase()||'';$('totalN').textContent=cattle.length;$('calfN').textContent=cattle.filter(a=>['Calf','Heifer'].includes(a.sex)).length;$('cowN').textContent=cattle.filter(a=>a.sex==='Cow').length;$('bullN').textContent=cattle.filter(a=>a.sex==='Bull').length;let list=cattle.filter(a=>[a.tag,a.breed,a.sire,a.dam,a.location,a.notes].join(' ').toLowerCase().includes(q));if(!list.length){$('herd').innerHTML='<div class="empty">No cattle recorded yet. Use the Photo First panel to add your first animal.</div>';return}let html='';for(let a of list){let media=[];try{media=await getMedia(a.id)}catch{}let ph=media.find(m=>m.type==='photo');html+=`<div class="animal" onclick="openRecord('${a.id}')">${ph?`<img class="thumb" src="${ph.data}">`:`<div class="thumb" style="display:grid;place-items:center;font-size:35px">🐄</div>`}<div><h3>🐄 Tag ${esc(a.tag)}</h3><div class="chips"><span class="chip">${esc(a.sex)}</span>${a.breed?`<span class="chip">${esc(a.breed)}</span>`:''}${a.location?`<span class="chip">📍 ${esc(a.location)}</span>`:''}<span class="chip">${esc(a.status)}</span></div>${a.dam?`<div>Dam: ${esc(a.dam)}</div>`:''}${a.sire?`<div>Sire: ${esc(a.sire)}</div>`:''}${a.notes?`<div class="muted">${esc(a.notes)}</div>`:''}</div><div class="arrow">›</div></div>`}$('herd').innerHTML=html}
async function openRecord(id){currentId=id;let a=cattle.find(x=>String(x.id)===String(id));if(!a)return;$('rTitle').textContent='🐄 Tag '+a.tag;$('rTag').value=a.tag;$('rSex').value=a.sex;$('rBreed').value=a.breed;$('rLocation').value=a.location;$('rDam').value=a.dam;$('rSire').value=a.sire;$('rStatus').value=a.status;$('rFlag').value=a.flag;$('rNotes').value=a.notes;renderHist(a);await renderRecordMedia(a.id);$('recordModal').classList.remove('hidden')}
function closeRecord(){$('recordModal').classList.add('hidden');currentId=null}
async function renderRecordMedia(id){let ms=[];try{ms=await getMedia(id)}catch{}let photos=ms.filter(m=>m.type==='photo'),videos=ms.filter(m=>m.type==='video');$('rMedia').innerHTML=`<div class="photo-grid">${photos.map(p=>`<img src="${p.data}">`).join('')}</div><div class="video-grid">${videos.map(v=>`<video src="${URL.createObjectURL(v.blob)}" controls></video>`).join('')}</div>`}
function saveRecord(){let a=cattle.find(x=>String(x.id)===String(currentId));if(!a)return;a.tag=$('rTag').value.trim();a.sex=$('rSex').value;a.breed=$('rBreed').value.trim();a.location=$('rLocation').value.trim();a.dam=$('rDam').value.trim();a.sire=$('rSire').value.trim();a.status=$('rStatus').value;a.flag=$('rFlag').value;a.notes=$('rNotes').value.trim();save();$('rTitle').textContent='🐄 Tag '+a.tag;alert('Record saved.')}
$('attachPhoto').onchange=async e=>{let a=cattle.find(x=>String(x.id)===String(currentId));pending={photos:Array.from(e.target.files),videos:[]};await savePendingMedia(a.id);await renderRecordMedia(a.id);render()};$('attachVideo').onchange=async e=>{let a=cattle.find(x=>String(x.id)===String(currentId));pending={photos:[],videos:Array.from(e.target.files)};await savePendingMedia(a.id);await renderRecordMedia(a.id);render()};
function renderHist(a){$('breedHist').innerHTML=a.breeding.map(x=>`<div class="history"><b>${esc(x.date)}</b> • ${esc(x.method)} • ${esc(x.sire||'')}<br>${esc(x.notes||'')}</div>`).join('')||'<div class="muted">No breeding records yet.</div>';$('calvHist').innerHTML=a.calvings.map(x=>`<div class="history"><b>${esc(x.date)}</b> • Calf ${esc(x.tag||'')} • ${esc(x.sex||'')}<br>${esc(x.notes||'')}</div>`).join('')||'<div class="muted">No calving records yet.</div>';$('healthHist').innerHTML=a.health.map(x=>`<div class="history"><b>${esc(x.date)}</b> • ${esc(x.treatment||'')}<br>${esc(x.notes||'')}${x.withdraw?` • Withdrawal ${esc(x.withdraw)}`:''}</div>`).join('')||'<div class="muted">No health records yet.</div>'}
function addBreeding(){let a=cattle.find(x=>String(x.id)===String(currentId));if(!$('bDate').value)return alert('Enter breeding date.');a.breeding.push({date:$('bDate').value,method:$('bMethod').value,sire:$('bSire').value.trim(),notes:$('bNotes').value.trim()});save();renderHist(a)}function addCalving(){let a=cattle.find(x=>String(x.id)===String(currentId));if(!$('cDate').value)return alert('Enter calving date.');a.calvings.push({date:$('cDate').value,tag:$('cTag').value.trim(),sex:$('cSex').value,notes:$('cNotes').value.trim()});save();renderHist(a)}function addHealth(){let a=cattle.find(x=>String(x.id)===String(currentId));if(!$('hDate').value)return alert('Enter treatment date.');a.health.push({date:$('hDate').value,treatment:$('hTreatment').value.trim(),withdraw:$('hWithdraw').value,notes:$('hNotes').value.trim()});save();renderHist(a)}
async function deleteAnimal(){if(!confirm('Delete this animal and its stored media?'))return;let id=currentId;cattle=cattle.filter(a=>String(a.id)!==String(id));try{await deleteMediaFor(id)}catch{}save();closeRecord()}
function backup(){let blob=new Blob([JSON.stringify({version:2,date:new Date().toISOString(),cattle},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='cattle-vision-backup.json';a.click();URL.revokeObjectURL(a.href)}function restore(e){let f=e.target.files[0];if(!f)return;let r=new FileReader;r.onload=()=>{try{let o=JSON.parse(r.result);cattle=(o.cattle||o).map(norm);save();alert('Records restored.')}catch{alert('That backup file could not be read.')}};r.readAsText(f)}
function showQuick(kind){let title='',body='';if(kind==='breeding'){title='🗓️ Breeding Calendar';let rows=cattle.flatMap(a=>a.breeding.map(b=>({a,b}))).sort((x,y)=>String(y.b.date).localeCompare(String(x.b.date)));body=rows.map(x=>`<div class="history"><b>Tag ${esc(x.a.tag)}</b> — ${esc(x.b.date)} • ${esc(x.b.method)} • ${esc(x.b.sire||'')}</div>`).join('')||'<div class="empty">No breeding records yet.</div>'}if(kind==='health'){title='✚ Health & Treatments';let rows=cattle.flatMap(a=>a.health.map(h=>({a,h}))).sort((x,y)=>String(y.h.date).localeCompare(String(x.h.date)));body=rows.map(x=>`<div class="history"><b>Tag ${esc(x.a.tag)}</b> — ${esc(x.h.date)} • ${esc(x.h.treatment||'')}</div>`).join('')||'<div class="empty">No health records yet.</div>'}if(kind==='location'){title='📍 Pasture / Location';body=cattle.map(a=>`<div class="history"><b>Tag ${esc(a.tag)}</b> — ${esc(a.location||'No location set')}</div>`).join('')||'<div class="empty">No cattle recorded.</div>'}if(kind==='reports'){title='📊 Herd Reports';body=`<div class="grid2"><div class="history"><b>${cattle.length}</b><br>Total cattle</div><div class="history"><b>${cattle.filter(a=>a.sex==='Cow').length}</b><br>Cows</div><div class="history"><b>${cattle.filter(a=>a.sex==='Bull').length}</b><br>Bulls</div><div class="history"><b>${cattle.reduce((n,a)=>n+a.calvings.length,0)}</b><br>Calving records</div></div>`}$('qTitle').textContent=title;$('qBody').innerHTML=body;$('quickModal').classList.remove('hidden')}
function openSettings(){$('settingsModal').classList.remove('hidden')}function clearAll(){if(!confirm('Clear all test cattle records?'))return;cattle=[];save();$('settingsModal').classList.add('hidden')}function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
(async()=>{try{db=await openDB()}catch(e){console.error(e)}render()})();