const $=id=>document.getElementById(id);
function cvReadArray(raw){const parsed=JSON.parse(raw);if(!Array.isArray(parsed))throw new Error('Expected an array');return parsed}
function cvBackupDamagedLocal(key,raw){if(raw==null)return;try{localStorage.setItem(`${key}-recovery-${Date.now()}`,raw)}catch{}try{sessionStorage.setItem('cv2-local-recovery-warning','1')}catch{}window.__cvRecoveredCattleStorage=true}
function cvLoadCattle(){let primary=null,legacy=null;try{primary=localStorage.getItem('cv2-cattle')}catch(e){console.error('Could not read local cattle records',e)}if(primary!=null){try{return cvReadArray(primary)}catch(e){console.error('Local cattle records were not readable; preserving a recovery copy',e);cvBackupDamagedLocal('cv2-cattle',primary)}}try{legacy=localStorage.getItem('cattleVision')}catch{}if(legacy!=null){try{return cvReadArray(legacy)}catch(e){console.error('Legacy cattle records were not readable',e);cvBackupDamagedLocal('cattleVision',legacy)}}return[]}
let cattle=cvLoadCattle();
let pending={photos:[],videos:[]},currentId=null,db=null;
let renderSeq=0,herdLimit=60,lastHerdQuery='',herdView='all';
let pendingPreviewUrls=[],recordVideoUrls=[];
let lastStorageAlert=0;
const SPECIAL_TYPES=new Set(['Livestock Guardian Dog','Horse']);

function newLocalId(){return (typeof crypto!=='undefined'&&crypto.randomUUID)?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function norm(a){a=a||{};a.id=a.id||newLocalId();a.tag=String(a.tag||'');a.sex=a.sex||'Cow';a.breed=a.breed||'';a.location=a.location||'';a.dam=a.dam||'';a.sire=a.sire||'';a.status=a.status||'Unknown';a.flag=a.flag||'Normal';a.notes=a.notes||'';a.breeding=Array.isArray(a.breeding)?a.breeding:[];a.calvings=Array.isArray(a.calvings)?a.calvings:[];a.health=Array.isArray(a.health)?a.health:[];a.locationHistory=Array.isArray(a.locationHistory)?a.locationHistory:[];return a}
cattle=cattle.map(norm);
function save(){try{localStorage.setItem('cv2-cattle',JSON.stringify(cattle))}catch(e){console.error('Cattle Vision local save failed',e);if(Date.now()-lastStorageAlert>10000){lastStorageAlert=Date.now();alert('This device could not save that change locally. Nothing was intentionally deleted. Keep Cattle Vision open, verify Cloud when you have a connection, and try the change again.')}throw e}render()}

function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open('cv2-media',1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('media')){const s=d.createObjectStore('media',{keyPath:'id'});s.createIndex('animalId','animalId')}};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function getMedia(animalId){if(!db)return[];return new Promise((res,rej)=>{const q=db.transaction('media','readonly').objectStore('media').index('animalId').getAll(IDBKeyRange.only(String(animalId)));q.onsuccess=()=>res(q.result||[]);q.onerror=()=>rej(q.error)})}
async function getAllMedia(){if(!db)return[];return new Promise((res,rej)=>{const q=db.transaction('media','readonly').objectStore('media').getAll();q.onsuccess=()=>res(q.result||[]);q.onerror=()=>rej(q.error)})}
function cloudMediaChanged(){window.dispatchEvent(new Event('cv-local-change'))}
function putMedia(m){return new Promise((res,rej)=>{if(!db)return rej(new Error('Media database is not ready'));const r=db.transaction('media','readwrite').objectStore('media').put(m);r.onsuccess=()=>{cloudMediaChanged();res()};r.onerror=()=>rej(r.error)})}
function deleteMediaFor(id){return new Promise((res,rej)=>{if(!db)return res();const store=db.transaction('media','readwrite').objectStore('media'),idx=store.index('animalId'),cur=idx.openCursor(IDBKeyRange.only(String(id)));cur.onsuccess=e=>{const c=e.target.result;if(c){c.delete();c.continue()}else{cloudMediaChanged();res()}};cur.onerror=()=>rej(cur.error)})}
function clearAllLocalMedia(){return new Promise((res,rej)=>{if(!db)return res();const q=db.transaction('media','readwrite').objectStore('media').clear();q.onsuccess=()=>{cloudMediaChanged();res()};q.onerror=()=>rej(q.error)})}

async function compressPhoto(file){return new Promise((res,rej)=>{const u=URL.createObjectURL(file),im=new Image;im.onload=()=>{const s=Math.min(1,1600/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(im.width*s));c.height=Math.max(1,Math.round(im.height*s));c.getContext('2d').drawImage(im,0,0,c.width,c.height);URL.revokeObjectURL(u);res(c.toDataURL('image/jpeg',.82))};im.onerror=e=>{URL.revokeObjectURL(u);rej(e)};im.src=u})}
async function savePendingMedia(animalId){if(!db)return;for(const f of pending.photos){const data=await compressPhoto(f);await putMedia({id:newLocalId(),animalId:String(animalId),type:'photo',data,created:new Date().toISOString()})}for(const f of pending.videos){try{await putMedia({id:newLocalId(),animalId:String(animalId),type:'video',blob:f,created:new Date().toISOString()})}catch(e){console.error(e);alert('Animal saved, but this video could not be stored on this device. Try choosing the original video again when you have a strong connection.')}}pending={photos:[],videos:[]}}
function clearPendingPreviewUrls(){pendingPreviewUrls.forEach(u=>URL.revokeObjectURL(u));pendingPreviewUrls=[]}
function mediaPreview(){clearPendingPreviewUrls();let html='';if(pending.photos[0]){const u=URL.createObjectURL(pending.photos[0]);pendingPreviewUrls.push(u);html+=`<img class="preview" src="${u}">`}if(pending.videos[0]){const u=URL.createObjectURL(pending.videos[0]);pendingPreviewUrls.push(u);html+=`<video class="preview" src="${u}" controls playsinline></video>`}return html}

function openAdd(){pending={photos:[],videos:[]};clearPendingPreviewUrls();$('pendingPreview').innerHTML='<div class="notice">Optional: choose or take a photo/video first, then enter the tag. Leave the tag blank if no tag is visible.</div>';$('addModal').classList.remove('hidden')}
function openAddWithMedia(type,files){pending={photos:[],videos:[]};pending[type]=Array.from(files||[]);$('pendingPreview').innerHTML=mediaPreview();$('addModal').classList.remove('hidden')}
function closeAdd(){$('addModal').classList.add('hidden');['aTag','aBreed','aBirth','aLocation','aReg','aDam','aSire','aNotes'].forEach(x=>{if($(x))$(x).value=''});if($('aSex'))$('aSex').value='Cow';pending={photos:[],videos:[]};clearPendingPreviewUrls();if($('photoCamera'))$('photoCamera').value='';if($('photoInput'))$('photoInput').value='';if($('videoCamera'))$('videoCamera').value='';if($('videoInput'))$('videoInput').value=''}
$('photoCamera').onchange=e=>openAddWithMedia('photos',e.target.files);$('photoInput').onchange=e=>openAddWithMedia('photos',e.target.files);$('videoCamera').onchange=e=>openAddWithMedia('videos',e.target.files);$('videoInput').onchange=e=>openAddWithMedia('videos',e.target.files);

async function saveNewAnimal(){let tag=$('aTag').value.trim();const noTag=!tag;if(noTag)tag='N-T';if(!noTag&&cattle.some(a=>a.tag&&a.tag!=='N-T'&&a.tag.toLowerCase()===tag.toLowerCase()))return alert('That tag already exists. Open that animal to add media.');const created=new Date().toISOString(),location=$('aLocation').value.trim();const a=norm({id:newLocalId(),tag,sex:$('aSex').value,breed:$('aBreed').value.trim(),birth:$('aBirth').value,location,registration:$('aReg').value.trim(),dam:$('aDam').value.trim(),sire:$('aSire').value.trim(),notes:$('aNotes').value.trim(),created,noTag});if(location)a.locationHistory.push({from:'',to:location,date:created});cattle.push(a);try{save()}catch(e){cattle=cattle.filter(x=>String(x.id)!==String(a.id));return}let mediaFailed=false;try{await savePendingMedia(a.id)}catch(e){mediaFailed=true;console.error(e)}closeAdd();render();if(mediaFailed)return alert('The animal record saved, but one or more photos/videos did not finish saving on this device. Reopen the animal and add that media again.');alert(noTag?'Animal saved as N-T. You can assign the permanent tag later.':'Animal saved.')}

function animalIcon(a){if(a.sex==='Livestock Guardian Dog')return'🐕';if(a.sex==='Horse')return'🐎';return'🐄'}
function coreCattle(){return cattle.filter(a=>!SPECIAL_TYPES.has(a.sex))}
function loadMoreHerd(){herdLimit+=60;render()}
window.loadMoreHerd=loadMoreHerd;
function herdViewLabel(view){return({all:'All Cattle',young:'Young Stock',females:'Females / Cows',sires:'Sires / Bulls'}[view]||'All Cattle')}
function inHerdView(a){if(herdView==='young')return['Calf','Heifer'].includes(a.sex);if(herdView==='females')return a.sex==='Cow';if(herdView==='sires')return a.sex==='Bull';return true}
function setHerdView(view='all'){
  herdView=['all','young','females','sires'].includes(view)?view:'all';
  herdLimit=60;
  const search=$('search');if(search)search.value='';
  try{localStorage.setItem('cv2-herd-collapsed','0')}catch{}
  window.dispatchEvent(new CustomEvent('cv-herd-view',{detail:{view:herdView}}));
  render();
  setTimeout(()=>$('myHerdPanel')?.scrollIntoView({behavior:'smooth',block:'start'}),0);
}
window.setHerdView=setHerdView;
function clearHerdView(){setHerdView('all')}
window.clearHerdView=clearHerdView;
function firstPhoto(animalId){return new Promise(resolve=>{if(!db)return resolve('');try{const store=db.transaction('media','readonly').objectStore('media'),idx=store.index('animalId'),cur=idx.openCursor(IDBKeyRange.only(String(animalId)));cur.onsuccess=e=>{const c=e.target.result;if(!c)return resolve('');const v=c.value;if(v?.type==='photo'&&v.data)return resolve(v.data);c.continue()};cur.onerror=()=>resolve('')}catch{return resolve('')}})}
async function thumbnailMap(rows){const out=new Map();for(let i=0;i<rows.length;i+=10){const vals=await Promise.all(rows.slice(i,i+10).map(async a=>[String(a.id),await firstPhoto(a.id)]));for(const[id,p]of vals)if(p)out.set(id,p);await new Promise(r=>setTimeout(r,0))}return out}
function duplicatePermanentTags(){const counts=new Map();for(const a of cattle){const k=a?.tag&&a.tag!=='N-T'?String(a.tag).trim().toLowerCase():'';if(k)counts.set(k,(counts.get(k)||0)+1)}return new Set([...counts].filter(([,n])=>n>1).map(([k])=>k))}
async function render(){
  const seq=++renderSeq,q=$('search')?.value.trim().toLowerCase()||'';
  if(q!==lastHerdQuery){lastHerdQuery=q;herdLimit=60}
  const core=coreCattle(),counts={all:core.length,young:core.filter(a=>['Calf','Heifer'].includes(a.sex)).length,females:core.filter(a=>a.sex==='Cow').length,sires:core.filter(a=>a.sex==='Bull').length};
  if($('totalN'))$('totalN').textContent=counts.all;if($('calfN'))$('calfN').textContent=counts.young;if($('cowN'))$('cowN').textContent=counts.females;if($('bullN'))$('bullN').textContent=counts.sires;
  window.cvUpdateHerdCollapse?.();window.cvUpdateNoTagHerdCount?.();
  document.querySelectorAll('[data-herd-view]').forEach(card=>{const active=card.dataset.herdView===herdView;card.classList.toggle('active',active);card.setAttribute('aria-pressed',String(active))});
  const herd=$('herd');if(!herd)return;
  const collapsed=localStorage.getItem('cv2-herd-collapsed')!=='0';if(collapsed&&!q){herd.innerHTML='';return}
  let list=core.filter(inHerdView).filter(a=>[a.tag,a.breed,a.sire,a.dam,a.location,a.notes,a.sex].join(' ').toLowerCase().includes(q));
  const filterNote=herdView==='all'?'':`<div class="herd-filter-note"><b>${esc(herdViewLabel(herdView))}</b> • ${list.length} record${list.length===1?'':'s'}<button type="button" class="softbtn" onclick="clearHerdView()">Show All Cattle</button></div>`;
  if(!list.length){herd.innerHTML=filterNote+'<div class="empty">No cattle match this view.</div>';return}
  const shown=list.slice(0,herdLimit),photos=await thumbnailMap(shown);if(seq!==renderSeq)return;
  const dupes=duplicatePermanentTags();let html=filterNote;
  for(const a of shown){const ph=photos.get(String(a.id)),icon=animalIcon(a),key=a?.tag&&a.tag!=='N-T'?String(a.tag).trim().toLowerCase():'';html+=`<div class="animal" onclick="openRecord('${String(a.id).replace(/'/g,"\\'")}')">${ph?`<img class="thumb" loading="lazy" src="${ph}">`:`<div class="thumb" style="display:grid;place-items:center;font-size:35px">${icon}</div>`}<div><h3>${icon} Tag ${esc(a.tag||'N-T')}</h3><div class="chips"><span class="chip">${esc(a.sex)}</span>${a.breed?`<span class="chip">${esc(a.breed)}</span>`:''}${a.location?`<span class="chip">📍 ${esc(a.location)}</span>`:''}<span class="chip">${esc(a.status)}</span>${key&&dupes.has(key)?'<span class="chip" style="background:#fff0cf;color:#805600">Duplicate tag — review</span>':''}</div>${a.dam?`<div>Dam: ${esc(a.dam)}</div>`:''}${a.sire?`<div>Sire: ${esc(a.sire)}</div>`:''}${a.notes?`<div class="muted">${esc(a.notes)}</div>`:''}</div><div class="arrow">›</div></div>`}
  if(shown.length<list.length)html+=`<div class="notice" style="text-align:center;margin-top:10px">Showing ${shown.length} of ${list.length} cattle.<br><button type="button" class="softbtn" style="margin-top:8px" onclick="loadMoreHerd()">Load 60 More</button></div>`;
  herd.innerHTML=html;
}
render.__cvHardened=true;

function clearRecordVideoUrls(){recordVideoUrls.forEach(u=>URL.revokeObjectURL(u));recordVideoUrls=[]}
async function openRecord(id){currentId=id;const a=cattle.find(x=>String(x.id)===String(id));if(!a)return;$('rTitle').textContent=`${animalIcon(a)} Tag ${a.tag||'N-T'}`;$('rTag').value=a.tag==='N-T'&&a.noTag?'':a.tag;$('rSex').value=a.sex;$('rBreed').value=a.breed;$('rLocation').value=a.location;$('rDam').value=a.dam;$('rSire').value=a.sire;$('rStatus').value=a.status;$('rFlag').value=a.flag;$('rNotes').value=a.notes;renderHist(a);await renderRecordMedia(a.id);$('recordModal').classList.remove('hidden')}
function closeRecord(){$('recordModal').classList.add('hidden');clearRecordVideoUrls();currentId=null}
async function renderRecordMedia(id){clearRecordVideoUrls();let ms=[];try{ms=await getMedia(id)}catch(e){console.error(e)}const photos=ms.filter(m=>m.type==='photo'&&m.data),videos=ms.filter(m=>m.type==='video'&&m.blob);const videoHtml=videos.map(v=>{const u=URL.createObjectURL(v.blob);recordVideoUrls.push(u);return`<video src="${u}" controls playsinline preload="metadata"></video>`}).join('');$('rMedia').innerHTML=`<div class="photo-grid">${photos.map(p=>`<img loading="lazy" src="${p.data}">`).join('')}</div><div class="video-grid">${videoHtml}</div>`}
function saveRecord(){const a=cattle.find(x=>String(x.id)===String(currentId));if(!a)return;let newTag=$('rTag').value.trim(),noTag=!newTag;if(noTag)newTag='N-T';if(!noTag&&cattle.some(x=>String(x.id)!==String(a.id)&&x.tag&&x.tag!=='N-T'&&x.tag.toLowerCase()===newTag.toLowerCase()))return alert('Another animal already uses that tag number.');const oldLocation=a.location||'',newLocation=$('rLocation').value.trim();if(oldLocation!==newLocation){a.locationHistory=Array.isArray(a.locationHistory)?a.locationHistory:[];a.locationHistory.push({from:oldLocation,to:newLocation,date:new Date().toISOString()})}a.tag=newTag;a.noTag=noTag;a.sex=$('rSex').value;a.breed=$('rBreed').value.trim();a.location=newLocation;a.dam=$('rDam').value.trim();a.sire=$('rSire').value.trim();a.status=$('rStatus').value;a.flag=$('rFlag').value;a.notes=$('rNotes').value.trim();save();$('rTitle').textContent=`${animalIcon(a)} Tag ${a.tag}`;alert('Record saved.')}
$('attachPhoto').onchange=async e=>{const a=cattle.find(x=>String(x.id)===String(currentId));if(!a)return;pending={photos:Array.from(e.target.files||[]),videos:[]};try{await savePendingMedia(a.id)}catch(err){console.error(err);alert('One or more photos could not be saved.')}e.target.value='';await renderRecordMedia(a.id);render()};
$('attachVideo').onchange=async e=>{const a=cattle.find(x=>String(x.id)===String(currentId));if(!a)return;pending={photos:[],videos:Array.from(e.target.files||[])};try{await savePendingMedia(a.id)}catch(err){console.error(err);alert('One or more videos could not be saved.')}e.target.value='';await renderRecordMedia(a.id);render()};

function renderHist(a){$('breedHist').innerHTML=a.breeding.map(x=>`<div class="history"><b>${esc(x.date)}</b> • ${esc(x.method)} • ${esc(x.sire||'')}<br>${esc(x.notes||'')}</div>`).join('')||'<div class="muted">No breeding records yet.</div>';$('calvHist').innerHTML=a.calvings.map(x=>`<div class="history"><b>${esc(x.date)}</b> • Calf ${esc(x.tag||'')} • ${esc(x.sex||'')}<br>${esc(x.notes||'')}</div>`).join('')||'<div class="muted">No calving records yet.</div>';$('healthHist').innerHTML=a.health.map(x=>`<div class="history"><b>${esc(x.date)}</b> • ${esc(x.treatment||'')}<br>${esc(x.notes||'')}${x.withdraw?` • Withdrawal ${esc(x.withdraw)}`:''}</div>`).join('')||'<div class="muted">No health records yet.</div>'}
function addBreeding(){const a=cattle.find(x=>String(x.id)===String(currentId));if(!a)return;if(!$('bDate').value)return alert('Enter breeding date.');a.breeding.push({date:$('bDate').value,method:$('bMethod').value,sire:$('bSire').value.trim(),notes:$('bNotes').value.trim()});save();renderHist(a)}
function addCalving(){const a=cattle.find(x=>String(x.id)===String(currentId));if(!a)return;if(!$('cDate').value)return alert('Enter calving date.');a.calvings.push({date:$('cDate').value,tag:$('cTag').value.trim(),sex:$('cSex').value,notes:$('cNotes').value.trim()});save();renderHist(a)}
function addHealth(){const a=cattle.find(x=>String(x.id)===String(currentId));if(!a)return;if(!$('hDate').value)return alert('Enter treatment date.');a.health.push({date:$('hDate').value,treatment:$('hTreatment').value.trim(),withdraw:$('hWithdraw').value,notes:$('hNotes').value.trim()});save();renderHist(a)}
async function deleteAnimal(){if(!confirm('Delete this animal and its stored media from this device? If cloud sync is on, the cloud copy will also be removed.'))return;const id=currentId;cattle=cattle.filter(a=>String(a.id)!==String(id));try{await deleteMediaFor(id)}catch(e){console.error(e)}save();closeRecord()}

function cvBackupArray(key){try{const value=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(value)?value:[]}catch{return[]}}
function cvBackupObject(key){try{const value=JSON.parse(localStorage.getItem(key)||'{}');return value&&typeof value==='object'&&!Array.isArray(value)?value:{}}catch{return{}}}
function readLocalExtras(){return{pastures:cvBackupArray('cv2-pastures'),medications:cvBackupArray('cv2-meds'),herdWorkEvents:cvBackupArray('cv2-herd-work-events'),animalCostEvents:cvBackupArray('cv2-animal-cost-events'),animalFinancials:cvBackupObject('cv2-animal-financials'),pastureCostEvents:cvBackupArray('cv2-pasture-cost-events'),mileageEvents:cvBackupArray('cv2-mileage-events')}}
function backup(){const extras=readLocalExtras(),blob=new Blob([JSON.stringify({version:5,date:new Date().toISOString(),cattle,...extras},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='cattle-vision-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function restore(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const o=JSON.parse(r.result),rows=(o.cattle||o);if(!Array.isArray(rows))throw new Error('No cattle array');if(!confirm(`Restore ${rows.length} animal record${rows.length===1?'':'s'} from this backup onto this device? Existing local cattle records will be replaced. Photos and videos already on this device will be kept.`))return;cattle=rows.map(norm);localStorage.setItem('cv2-cattle',JSON.stringify(cattle));const arrays=[['pastures','cv2-pastures'],['medications','cv2-meds'],['herdWorkEvents','cv2-herd-work-events'],['animalCostEvents','cv2-animal-cost-events'],['pastureCostEvents','cv2-pasture-cost-events'],['mileageEvents','cv2-mileage-events']];for(const[name,key]of arrays)if(Array.isArray(o[name]))localStorage.setItem(key,JSON.stringify(o[name]));if(o.animalFinancials&&typeof o.animalFinancials==='object'&&!Array.isArray(o.animalFinancials))localStorage.setItem('cv2-animal-financials',JSON.stringify(o.animalFinancials));render();window.dispatchEvent(new Event('cv-finance-changed'));window.dispatchEvent(new Event('cv-pasture-cost-restored'));window.dispatchEvent(new Event('cv-mileage-restored'));alert('Records and cost ledgers restored.')}catch(err){console.error(err);alert('That backup file could not be read or saved on this device. Existing photos and videos were not intentionally changed.')}finally{e.target.value=''}};r.readAsText(f)}

function showQuick(kind){const core=coreCattle();let title='',body='';if(kind==='breeding'){title='🗓️ Breeding Calendar';const rows=core.flatMap(a=>a.breeding.map(b=>({a,b}))).sort((x,y)=>String(y.b.date).localeCompare(String(x.b.date)));body=rows.map(x=>`<div class="history"><b>Tag ${esc(x.a.tag)}</b> — ${esc(x.b.date)} • ${esc(x.b.method)} • ${esc(x.b.sire||'')}</div>`).join('')||'<div class="empty">No breeding records yet.</div>'}if(kind==='health'){title='✚ Health & Treatments';const rows=core.flatMap(a=>a.health.map(h=>({a,h}))).sort((x,y)=>String(y.h.date).localeCompare(String(x.h.date)));body=rows.map(x=>`<div class="history"><b>Tag ${esc(x.a.tag)}</b> — ${esc(x.h.date)} • ${esc(x.h.treatment||'')}</div>`).join('')||'<div class="empty">No health records yet.</div>'}if(kind==='location'){title='📍 Pasture / Location';body=core.map(a=>`<div class="history"><b>Tag ${esc(a.tag)}</b> — ${esc(a.location||'No location set')}</div>`).join('')||'<div class="empty">No cattle recorded.</div>'}if(kind==='reports'){title='📊 Herd Reports';body=`<div class="grid2"><div class="history"><b>${core.length}</b><br>Total cattle</div><div class="history"><b>${core.filter(a=>a.sex==='Cow').length}</b><br>Cows</div><div class="history"><b>${core.filter(a=>a.sex==='Bull').length}</b><br>Bulls</div><div class="history"><b>${core.reduce((n,a)=>n+a.calvings.length,0)}</b><br>Calving records</div></div>`}$('qTitle').textContent=title;$('qBody').innerHTML=body;$('quickModal').classList.remove('hidden')}
function openSettings(){$('settingsModal').classList.remove('hidden')}
async function clearAll(){const typed=prompt('This clears Cattle Vision records from THIS browser/device only. The cloud account is not erased. Type DELETE LOCAL to continue.','');if(typed!=='DELETE LOCAL')return;const second=confirm('Final check: clear local cattle, pasture, medication, herd-work, cost, mileage, photo, and video data from this browser?');if(!second)return;cattle=[];for(const key of['cv2-cattle','cv2-pastures','cv2-meds','cv2-herd-work-events','cv2-animal-cost-events','cv2-animal-financials','cv2-animal-cost-delete-queue','cv2-pasture-cost-events','cv2-pasture-cost-delete-queue','cv2-mileage-events','cv2-mileage-delete-queue','cv2-pasture-photo-sessions'])localStorage.removeItem(key);try{await Promise.all([clearAllLocalMedia(),window.cvClearPastureSessionMedia?.()])}catch(e){console.error(e)}render();$('settingsModal').classList.add('hidden');alert('Local device data cleared. Cloud records were not deleted.')}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}

try{localStorage.setItem('cv2-cattle',JSON.stringify(cattle))}catch(e){console.error('Could not normalize local cattle records',e)}
(async()=>{try{db=await openDB()}catch(e){console.error(e)}render();let recovered=false;try{recovered=sessionStorage.getItem('cv2-local-recovery-warning')==='1';if(recovered)sessionStorage.removeItem('cv2-local-recovery-warning')}catch{}if(recovered||window.__cvRecoveredCattleStorage)setTimeout(()=>alert('Cattle Vision found damaged local record data and preserved a recovery copy on this device before opening the last readable records. Do not clear browser data; verify Cloud or a backup before making major changes.'),100)})();
