let bulkFiles=[];let bulkUrls=[];let bulkPasture='';
function newId(){return (crypto&&crypto.randomUUID)?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function closeBulkSorter(){bulkUrls.forEach(u=>URL.revokeObjectURL(u));bulkUrls=[];bulkFiles=[];bulkPasture='';let m=$('bulkModal');if(m)m.classList.add('hidden');if($('photoInput'))$('photoInput').value='';if($('bulkGrid'))$('bulkGrid').innerHTML='';if($('bulkProgress'))$('bulkProgress').textContent=''}
function openBulkSorter(files,pastureName=''){bulkFiles=Array.from(files||[]).filter(f=>f.type&&f.type.startsWith('image/'));if(!bulkFiles.length)return;bulkPasture=pastureName||'';bulkUrls=bulkFiles.map(f=>URL.createObjectURL(f));renderBulkSorter();$('bulkModal').classList.remove('hidden')}
function tagOptions(){return cattle.filter(a=>a.tag&&a.tag!=='N-T').slice().sort((a,b)=>String(a.tag).localeCompare(String(b.tag),undefined,{numeric:true})).map(a=>`<option value="${esc(a.tag)}">`).join('')}
function insertDash(input){if(!input)return;const start=input.selectionStart??input.value.length,end=input.selectionEnd??input.value.length;input.value=input.value.slice(0,start)+'-'+input.value.slice(end);input.focus();try{input.setSelectionRange(start+1,start+1)}catch{}input.dispatchEvent(new Event('input',{bubbles:true}))}
function renderBulkSorter(){let g=$('bulkGrid');$('bulkCount').textContent=`${bulkFiles.length} photo${bulkFiles.length===1?'':'s'}`;const note=$('bulkPastureNote');if(note)note.textContent=bulkPasture?`These cattle will be assigned to ${bulkPasture}.`:'Leave a tag blank for a slick-eared/no-tag cow; it will save as N-T.';g.innerHTML=bulkFiles.map((f,i)=>`<div class="bulk-card" data-i="${i}"><img src="${bulkUrls[i]}" alt="Photo ${i+1}"><div class="bulk-fields"><label>Tag Number <button type="button" class="dash-suggest" onclick="insertDash(this.parentElement.nextElementSibling)">Add -</button></label><input class="bulk-tag" data-i="${i}" list="bulkKnownTags" inputmode="numeric" placeholder="Tag, or leave blank for N-T"><label>If tag is new, animal type</label><select class="bulk-sex" data-i="${i}"><option>Cow</option><option>Bull</option><option>Heifer</option><option>Steer</option><option>Calf</option></select><div class="bulk-status" id="bulkStatus${i}"></div></div></div>`).join('')+`<datalist id="bulkKnownTags">${tagOptions()}</datalist>`;document.querySelectorAll('.bulk-tag').forEach(inp=>inp.addEventListener('input',()=>{let t=inp.value.trim(),a=t?cattle.find(x=>x.tag&&x.tag!=='N-T'&&x.tag.toLowerCase()===t.toLowerCase()):null,s=$('bulkStatus'+inp.dataset.i);s.textContent=t?(a?`Will attach to existing Tag ${a.tag}`:'New tag — a basic animal record will be created'):'No tag — will save as N-T';}))}
function applyBulkTagToEmpty(){let t=$('bulkApplyTag').value.trim();if(!t)return;document.querySelectorAll('.bulk-tag').forEach(i=>{if(!i.value.trim()){i.value=t;i.dispatchEvent(new Event('input'))}})}
async function saveBulkPhotos(){if(!db)return alert('Photo storage is not available in this browser.');let inputs=[...document.querySelectorAll('.bulk-tag')];let btn=$('bulkSave');btn.disabled=true;let created=0,saved=0,noTag=0;try{for(let i=0;i<bulkFiles.length;i++){let raw=inputs[i].value.trim(),animal=null;if(raw){animal=cattle.find(a=>a.tag&&a.tag!=='N-T'&&a.tag.toLowerCase()===raw.toLowerCase());}if(!animal){let sex=document.querySelector(`.bulk-sex[data-i="${i}"]`).value;let tag=raw||'N-T';animal=norm({id:Date.now()+Math.random(),tag,sex,location:bulkPasture||'',created:new Date().toISOString(),notes:raw?'Created during bulk photo import':'No tag visible at import; assign permanent tag later'});if(!raw){animal.noTag=true;noTag++;}cattle.push(animal);created++;}else if(bulkPasture){if(typeof setAnimalPasture==='function')setAnimalPasture(animal,bulkPasture);else animal.location=bulkPasture;}let data=await compressPhoto(bulkFiles[i]);await putMedia({id:newId(),animalId:String(animal.id),type:'photo',data,created:new Date().toISOString(),source:bulkPasture?'pasture-bulk-import':'bulk-import'});saved++;$('bulkProgress').textContent=`Saving ${saved} of ${bulkFiles.length} photos…`;}save();closeBulkSorter();render();let msg=`${saved} photo${saved===1?'':'s'} saved.${created?` ${created} new animal record${created===1?'':'s'} created.`:''}${noTag?` ${noTag} saved as N-T.`:''}${bulkPasture?` Herd assigned to ${bulkPasture}.`:''}`;alert(msg);}catch(e){console.error(e);$('bulkProgress').textContent='Some photos could not be saved.';alert(`Saved ${saved} of ${bulkFiles.length} photos. Browser storage may be full.`);}finally{btn.disabled=false}}
if($('photoInput'))$('photoInput').onchange=e=>{let files=Array.from(e.target.files||[]);if(files.length===1)openAddWithMedia('photos',files);else if(files.length>1)openBulkSorter(files)};

(function setupTagDash(){['aTag','rTag'].forEach(id=>{const el=$(id);if(!el)return;el.setAttribute('inputmode','numeric');const label=el.parentElement?.querySelector('label');if(label&&!label.querySelector('.dash-suggest')){const b=document.createElement('button');b.type='button';b.className='dash-suggest';b.textContent='Add -';b.onclick=()=>insertDash(el);label.appendChild(b);}});})();

// Pasture management UI is injected here so older saved cattle stay compatible.
(function setupPastures(){
  const css=document.createElement('link');css.rel='stylesheet';css.href='pastures.css?v=2';document.head.appendChild(css);
  const dl=document.createElement('datalist');dl.id='pastureOptions';document.body.appendChild(dl);
  ['aLocation','rLocation'].forEach(id=>{const el=$(id);if(el){el.setAttribute('list','pastureOptions');el.placeholder='Choose or enter pasture...';}});
  document.querySelectorAll('.quick button').forEach(btn=>{if(btn.textContent.includes('Pasture / Location')){btn.setAttribute('onclick','openPastures()');btn.innerHTML='Pastures<br><span class="muted">Create pastures, upload herds & move cattle</span>';}});
  const modal=document.createElement('div');modal.id='pastureModal';modal.className='modal hidden';modal.innerHTML=`<div class="sheet"><div class="row"><div><h2>Pastures</h2><div class="muted">Build your pasture list, upload a whole herd into a pasture, and move selected cattle whenever the herd changes locations.</div></div><button class="softbtn" onclick="closePastures()">Close</button></div><div class="pasture-add"><div><label>New Pasture Name</label><input id="newPastureName" placeholder="Example: Danny's Summer Pasture"></div><button class="greenbtn" onclick="addPasture()">Add Pasture</button></div><input id="pasturePhotoInput" type="file" accept="image/*" multiple style="display:none" onchange="handlePasturePhotoFiles(event)"><div id="pastureList" class="pasture-list"></div><div class="pasture-bulk"><h3>Move Cattle Between Pastures</h3><div class="muted">Filter by the herd's current pasture, select the cattle you are moving, then choose their destination pasture.</div><div class="pasture-transfer-grid"><div><label>Current pasture</label><select id="pastureSourceFilter" onchange="renderPastureAnimalRows()"><option value="">All cattle</option></select></div><div><label>Move selected cattle to</label><select id="bulkPastureSelect"><option value="">Choose pasture...</option></select></div><button class="greenbtn" onclick="bulkAssignPasture()">Move Selected</button></div><div id="pastureAnimalList" class="pasture-animal-list"></div></div></div>`;document.body.appendChild(modal);
  const s=document.createElement('script');s.src='pastures.js?v=2';document.body.appendChild(s);
})();
