let bulkFiles=[];let bulkUrls=[];
function closeBulkSorter(){bulkUrls.forEach(u=>URL.revokeObjectURL(u));bulkUrls=[];bulkFiles=[];let m=$('bulkModal');if(m)m.classList.add('hidden');if($('photoInput'))$('photoInput').value='';if($('bulkGrid'))$('bulkGrid').innerHTML='';if($('bulkProgress'))$('bulkProgress').textContent=''}
function openBulkSorter(files){bulkFiles=Array.from(files||[]).filter(f=>f.type&&f.type.startsWith('image/'));if(!bulkFiles.length)return;bulkUrls=bulkFiles.map(f=>URL.createObjectURL(f));renderBulkSorter();$('bulkModal').classList.remove('hidden')}
function tagOptions(){return cattle.slice().sort((a,b)=>String(a.tag).localeCompare(String(b.tag),undefined,{numeric:true})).map(a=>`<option value="${esc(a.tag)}">`).join('')}
function renderBulkSorter(){let g=$('bulkGrid');$('bulkCount').textContent=`${bulkFiles.length} photo${bulkFiles.length===1?'':'s'}`;g.innerHTML=bulkFiles.map((f,i)=>`<div class="bulk-card" data-i="${i}"><img src="${bulkUrls[i]}" alt="Photo ${i+1}"><div class="bulk-fields"><label>Tag Number</label><input class="bulk-tag" data-i="${i}" list="bulkKnownTags" inputmode="numeric" placeholder="Enter tag for this photo"><label>If tag is new, animal type</label><select class="bulk-sex" data-i="${i}"><option>Cow</option><option>Bull</option><option>Heifer</option><option>Steer</option><option>Calf</option></select><div class="bulk-status" id="bulkStatus${i}"></div></div></div>`).join('')+`<datalist id="bulkKnownTags">${tagOptions()}</datalist>`;document.querySelectorAll('.bulk-tag').forEach(inp=>inp.addEventListener('input',()=>{let t=inp.value.trim(),a=cattle.find(x=>x.tag.toLowerCase()===t.toLowerCase()),s=$('bulkStatus'+inp.dataset.i);s.textContent=t?(a?`Will attach to existing Tag ${a.tag}`:'New tag — a basic animal record will be created'):''}))}
function applyBulkTagToEmpty(){let t=$('bulkApplyTag').value.trim();if(!t)return;document.querySelectorAll('.bulk-tag').forEach(i=>{if(!i.value.trim()){i.value=t;i.dispatchEvent(new Event('input'))}})}
async function saveBulkPhotos(){if(!db)return alert('Photo storage is not available in this browser.');let inputs=[...document.querySelectorAll('.bulk-tag')];let missing=inputs.filter(i=>!i.value.trim());if(missing.length){missing[0].focus();return alert('Enter a tag number for every photo before saving.');}let btn=$('bulkSave');btn.disabled=true;let created=0,saved=0;try{for(let i=0;i<bulkFiles.length;i++){let tag=inputs[i].value.trim();let animal=cattle.find(a=>a.tag.toLowerCase()===tag.toLowerCase());if(!animal){let sex=document.querySelector(`.bulk-sex[data-i="${i}"]`).value;animal=norm({id:Date.now()+Math.random(),tag,sex,created:new Date().toISOString(),notes:'Created during bulk photo import'});cattle.push(animal);created++;}let data=await compressPhoto(bulkFiles[i]);await putMedia({id:crypto.randomUUID(),animalId:String(animal.id),type:'photo',data,created:new Date().toISOString(),source:'bulk-import'});saved++;$('bulkProgress').textContent=`Saving ${saved} of ${bulkFiles.length} photos…`;}save();closeBulkSorter();render();alert(`${saved} photo${saved===1?'':'s'} categorized by tag.${created?` ${created} new animal record${created===1?'':'s'} created.`:''}`);}catch(e){console.error(e);$('bulkProgress').textContent='Some photos could not be saved.';alert(`Saved ${saved} of ${bulkFiles.length} photos. Browser storage may be full.`);}finally{btn.disabled=false}}
if($('photoInput'))$('photoInput').onchange=e=>{let files=Array.from(e.target.files||[]);if(files.length===1)openAddWithMedia('photos',files);else if(files.length>1)openBulkSorter(files)};

// Pasture management UI is injected here so older saved cattle stay compatible.
(function setupPastures(){
  const css=document.createElement('link');css.rel='stylesheet';css.href='pastures.css?v=1';document.head.appendChild(css);
  const dl=document.createElement('datalist');dl.id='pastureOptions';document.body.appendChild(dl);
  ['aLocation','rLocation'].forEach(id=>{const el=$(id);if(el){el.setAttribute('list','pastureOptions');el.placeholder='Choose or enter pasture...';}});
  document.querySelectorAll('.quick button').forEach(btn=>{if(btn.textContent.includes('Pasture / Location')){btn.setAttribute('onclick','openPastures()');btn.innerHTML='Pastures<br><span class="muted">Create pastures & assign cattle</span>';}});
  const modal=document.createElement('div');modal.id='pastureModal';modal.className='modal hidden';modal.innerHTML=`<div class="sheet"><div class="row"><div><h2>Pastures</h2><div class="muted">Create your pasture list, see how many cattle are in each pasture, and move cattle between pastures.</div></div><button class="softbtn" onclick="closePastures()">Close</button></div><div class="pasture-add"><div><label>New Pasture Name</label><input id="newPastureName" placeholder="Example: East Lot, Timber, North 80"></div><button class="greenbtn" onclick="addPasture()">Add Pasture</button></div><div id="pastureList" class="pasture-list"></div><div class="pasture-bulk"><h3>Assign Cattle</h3><div class="muted">Check several cattle to move them together, or use the dropdown beside one animal.</div><div class="pasture-bulk-controls"><div><label>Move selected cattle to</label><select id="bulkPastureSelect"><option value="">Choose pasture...</option></select></div><button class="greenbtn" onclick="bulkAssignPasture()">Assign Selected</button></div><div id="pastureAnimalList" class="pasture-animal-list"></div></div></div>`;document.body.appendChild(modal);
  const s=document.createElement('script');s.src='pastures.js?v=1';document.body.appendChild(s);
})();
