(function(){
const URL='https://rtyiqggxruwejqqyqtmv.supabase.co';
const KEY='sb_publishable_BxkgX1XJz8o_PsTb_LcVDQ_7DR6oHOk';
const FARM_KEY='cv2-cloud-farm-id';
let client=null,user=null,farm=null,syncing=false;
const el=id=>document.getElementById(id);
const safe=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function status(msg){const x=el('cloudStatus');if(x)x.textContent=msg;const b=el('cloudBtn');if(b)b.textContent=user?(farm?'Cloud ✓':'Cloud Account'):'Cloud Login'}
function inject(){if(el('cloudModal'))return;const b=document.createElement('button');b.id='cloudBtn';b.className='iconbtn';b.textContent='Cloud Login';b.onclick=openCloud;document.querySelector('.top-actions')?.prepend(b);const m=document.createElement('div');m.id='cloudModal';m.className='modal hidden';m.innerHTML=`<div class="sheet" style="max-width:620px"><div class="row"><div><h2 style="margin:0">Cattle Vision Cloud</h2><div class="muted" id="cloudStatus">Connecting…</div></div><button class="softbtn" onclick="closeCloud()">Close</button></div><div id="cloudBody" style="margin-top:14px"></div></div>`;document.body.appendChild(m)}
function openCloud(){el('cloudModal')?.classList.remove('hidden');renderCloud()}
function closeCloud(){el('cloudModal')?.classList.add('hidden')}
window.openCloud=openCloud;window.closeCloud=closeCloud;
async function init(){inject();if(!window.supabase?.createClient){status('Cloud library did not load.');return}client=window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const {data}=await client.auth.getSession();user=data.session?.user||null;client.auth.onAuthStateChange(async(_e,s)=>{user=s?.user||null;farm=null;if(user)await loadFarm();status(user?(farm?`Signed in • ${farm.name}`:'Signed in'):'Not signed in');renderCloud()});if(user)await loadFarm();status(user?(farm?`Signed in • ${farm.name}`:'Signed in'):'Not signed in')}
async function loadFarm(){const wanted=localStorage.getItem(FARM_KEY);const {data,error}=await client.from('farms').select('id,name,created_at').order('created_at');if(error){console.error(error);return}farm=(data||[]).find(x=>x.id===wanted)||(data||[])[0]||null;if(farm)localStorage.setItem(FARM_KEY,farm.id)}
function renderCloud(){const body=el('cloudBody');if(!body)return;if(!user){body.innerHTML=`<p>Sign in to keep this device's herd backed up in Cattle Vision Cloud.</p><label>Email</label><input id="cloudEmail" type="email" autocomplete="email" placeholder="you@example.com"><label>Password</label><input id="cloudPassword" type="password" autocomplete="current-password" placeholder="Password"><div class="row" style="margin-top:12px"><button class="greenbtn" onclick="cloudSignIn()">Sign In</button><button class="softbtn" onclick="cloudSignUp()">Create Account</button></div><div class="muted" style="margin-top:10px">Your local records stay on this phone while cloud backup is being set up.</div>`;return}if(!farm){body.innerHTML=`<p><b>${safe(user.email||'Signed in')}</b></p><p>Create the farm account that will own these records.</p><label>Farm Name</label><input id="cloudFarmName" placeholder="Example: Buckner Farm"><button class="greenbtn" style="margin-top:10px;width:100%" onclick="cloudCreateFarm()">Create Farm</button><button class="softbtn" style="margin-top:10px;width:100%" onclick="cloudSignOut()">Sign Out</button>`;return}body.innerHTML=`<div style="padding:12px;border:1px solid #d5ddd6;border-radius:10px"><b>${safe(farm.name)}</b><br><span class="muted">${safe(user.email||'')}</span></div><div style="padding:12px;border:1px solid #dfc56a;background:#fff8d8;border-radius:10px;margin:12px 0"><b>Device migration is now available.</b><br><span class="muted">This copies local cattle, pastures, breeding, calving, health records, photos and videos to this farm. Local data is not deleted.</span></div><button id="cloudSyncBtn" class="greenbtn" style="width:100%" onclick="cloudSyncNow()">Migrate / Sync This Device</button><div id="cloudProgress" class="muted" style="margin-top:10px"></div><button class="softbtn" style="margin-top:10px;width:100%" onclick="cloudSignOut()">Sign Out</button>`}
async function cloudSignIn(){const email=el('cloudEmail')?.value.trim(),password=el('cloudPassword')?.value;if(!email||!password)return alert('Enter your email and password.');const {error}=await client.auth.signInWithPassword({email,password});if(error)alert(error.message)}
async function cloudSignUp(){const email=el('cloudEmail')?.value.trim(),password=el('cloudPassword')?.value;if(!email||!password)return alert('Enter an email and password.');if(password.length<6)return alert('Use a password with at least 6 characters.');const {data,error}=await client.auth.signUp({email,password});if(error)return alert(error.message);if(!data.session)alert('Account created. Check your email for the confirmation message, then come back and sign in.');else alert('Account created and signed in.')}
async function cloudSignOut(){await client.auth.signOut();localStorage.removeItem(FARM_KEY);farm=null;user=null;renderCloud();status('Not signed in')}
async function cloudCreateFarm(){const name=el('cloudFarmName')?.value.trim();if(!name)return alert('Enter a farm name.');const {data,error}=await client.from('farms').insert({name,created_by:user.id}).select('id,name').single();if(error)return alert(error.message);farm=data;localStorage.setItem(FARM_KEY,farm.id);status(`Signed in • ${farm.name}`);renderCloud()}
window.cloudSignIn=cloudSignIn;window.cloudSignUp=cloudSignUp;window.cloudSignOut=cloudSignOut;window.cloudCreateFarm=cloudCreateFarm;
function progress(t){const p=el('cloudProgress');if(p)p.textContent=t}
async function syncPastures(){const local=JSON.parse(localStorage.getItem('cv2-pastures')||'[]');const names=[...new Set([...(local||[]).map(x=>x.name),...(window.cattle||cattle||[]).map(a=>a.location)].map(x=>String(x||'').trim()).filter(Boolean))];for(const name of names){const {error}=await client.from('pastures').upsert({farm_id:farm.id,name},{onConflict:'farm_id,name',ignoreDuplicates:true});if(error&&error.code!=='23505')throw error}const {data,error}=await client.from('pastures').select('id,name').eq('farm_id',farm.id);if(error)throw error;return new Map((data||[]).map(p=>[p.name.toLowerCase(),p.id]))}
async function upsertAnimal(a,pmap){const legacy=String(a.id);const row={farm_id:farm.id,legacy_id:legacy,tag:String(a.tag||''),animal_type:a.sex||'Cow',breed:a.breed||null,birth_date:a.birth||null,registration_no:a.registration||null,dam:a.dam||null,sire:a.sire||null,reproductive_status:a.status||null,management_flag:a.flag||null,notes:a.notes||null,no_tag:!!a.noTag,current_pasture_id:pmap.get(String(a.location||'').toLowerCase())||null,current_location_text:a.location||null,updated_at:new Date().toISOString()};const {data,error}=await client.from('animals').upsert(row,{onConflict:'farm_id,legacy_id'}).select('id').single();if(error)throw error;const id=data.id;for(let i=0;i<(a.breeding||[]).length;i++){const x=a.breeding[i],legacy_key=`${legacy}:breeding:${i}`;const {error:e}=await client.from('breeding_records').upsert({farm_id:farm.id,animal_id:id,legacy_key,breeding_date:x.date||null,method:x.method||null,sire:x.sire||null,notes:x.notes||null},{onConflict:'farm_id,legacy_key'});if(e)throw e}for(let i=0;i<(a.calvings||[]).length;i++){const x=a.calvings[i],legacy_key=`${legacy}:calving:${i}`;const {error:e}=await client.from('calving_records').upsert({farm_id:farm.id,animal_id:id,legacy_key,calving_date:x.date||null,calf_tag:x.tag||null,calf_sex:x.sex||null,notes:x.notes||null},{onConflict:'farm_id,legacy_key'});if(e)throw e}for(let i=0;i<(a.health||[]).length;i++){const x=a.health[i],legacy_key=`${legacy}:health:${i}`;const {error:e}=await client.from('health_records').upsert({farm_id:farm.id,animal_id:id,legacy_key,event_date:x.date||null,treatment:x.treatment||'Health record',withdrawal_date:x.withdraw||null,notes:x.notes||null},{onConflict:'farm_id,legacy_key'});if(e)throw e}return id}
function getAllLocalMedia(){return new Promise((resolve,reject)=>{const r=indexedDB.open('cv2-media',1);r.onsuccess=()=>{const d=r.result;if(!d.objectStoreNames.contains('media'))return resolve([]);const q=d.transaction('media','readonly').objectStore('media').getAll();q.onsuccess=()=>resolve(q.result||[]);q.onerror=()=>reject(q.error)};r.onerror=()=>reject(r.error)})}
async function mediaBlob(m){if(m.blob instanceof Blob)return m.blob;if(typeof m.data==='string'&&m.data.startsWith('data:'))return await (await fetch(m.data)).blob();return null}
async function syncMedia(idMap){let media=[];try{media=await getAllLocalMedia()}catch(e){console.error(e);return 0}let done=0;for(const m of media){const animalId=idMap.get(String(m.animalId));if(!animalId)continue;const blob=await mediaBlob(m);if(!blob)continue;const ext=(blob.type||'').includes('video')?'mp4':'jpg';const path=`${farm.id}/${animalId}/${String(m.id).replace(/[^A-Za-z0-9._-]/g,'_')}.${ext}`;const {error:uerr}=await client.storage.from('cattle-vision-media').upload(path,blob,{contentType:blob.type||undefined,upsert:true});if(uerr)throw uerr;const {error:merr}=await client.from('media_items').upsert({farm_id:farm.id,animal_id:animalId,media_type:(m.type==='video'?'video':'photo'),storage_path:path,mime_type:blob.type||null,byte_size:blob.size,source:m.source||'device-migration',created_by:user.id},{onConflict:'storage_path'});if(merr)throw merr;done++;progress(`Uploading media ${done} of ${media.length}…`)}return done}
async function syncMeds(){let meds=[];try{meds=JSON.parse(localStorage.getItem('cv2-meds')||'[]')}catch{}for(const m of meds){const row={farm_id:farm.id,name:m.name||'Medication',dose:m.dose||null,basis_lb:m.basis||null,unit:m.unit||null,route:m.route||null,withdrawal:m.withdraw||null,lot_no:m.lot||null,expires:m.expires||null,notes:m.notes||null,updated_at:new Date().toISOString()};const {error}=await client.from('medications').insert(row);if(error)console.warn('Medication sync skipped',error)}}
async function cloudSyncNow(){if(syncing||!user||!farm)return;syncing=true;const btn=el('cloudSyncBtn');if(btn)btn.disabled=true;try{const localAnimals=Array.isArray(window.cattle)?window.cattle:cattle;progress(`Preparing ${localAnimals.length} animal records…`);const pmap=await syncPastures();const idMap=new Map();for(let i=0;i<localAnimals.length;i++){progress(`Saving animal ${i+1} of ${localAnimals.length}…`);const id=await upsertAnimal(localAnimals[i],pmap);idMap.set(String(localAnimals[i].id),id)}progress('Saving medication cabinet…');await syncMeds();const mediaCount=await syncMedia(idMap);localStorage.setItem('cv2-cloud-last-sync',new Date().toISOString());progress(`Cloud sync complete: ${localAnimals.length} animals and ${mediaCount} media files backed up.`);alert('Cattle Vision cloud sync completed. Your local copy was kept on this device.')}catch(e){console.error(e);progress('Cloud sync stopped before completion. Anything already uploaded remains safely saved and you can run it again.');alert('Cloud sync stopped: '+(e?.message||e))}finally{syncing=false;if(btn)btn.disabled=false}}
window.cloudSyncNow=cloudSyncNow;
init().catch(e=>{console.error(e);status('Cloud connection error')});
})();