(function(){
if(window.__cvEquineRecordsInstalled)return;window.__cvEquineRecordsInstalled=true;
const HORSE='Horse';
const el=id=>document.getElementById(id);
const safe=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
const herd=()=>typeof cattle!=='undefined'&&Array.isArray(cattle)?cattle:[];
const isHorse=a=>a&&a.sex===HORSE;
const horseName=a=>String(a?.tag||'').trim()||'Unnamed horse';
const classes=['Unknown','Mare','Gelding','Stallion','Filly','Colt','Weanling','Yearling'];
function labelFor(id,text){const x=el(id),lab=x?.parentElement?.querySelector('label');if(lab)lab.childNodes[0].textContent=text+' '}
function setOptions(id,values){const s=el(id);if(!s)return;const cur=s.value;s.innerHTML=values.map(v=>`<option>${safe(v)}</option>`).join('');if(values.includes(cur))s.value=cur}
function ensureAddFields(){if(el('aHorseFields'))return;const host=el('aBreed')?.parentElement?.parentElement;if(!host)return;host.insertAdjacentHTML('afterend',`<div id="aHorseFields" class="equine-fields hidden"><h4>Equine Details</h4><div class="grid2"><div><label>Horse Class / Sex</label><select id="aEquineClass">${classes.map(x=>`<option>${x}</option>`).join('')}</select></div><div><label>Registered Name</label><input id="aHorseRegistered" placeholder="Optional registered name"></div></div><div class="grid2"><div><label>Color / Markings</label><input id="aHorseColor" placeholder="Bay, sorrel, blaze, stockings..."></div><div><label>Height (hands)</label><input id="aHorseHeight" inputmode="decimal" placeholder="Example: 15.2"></div></div><div class="grid2"><div><label>Primary Use / Discipline</label><input id="aHorseUse" placeholder="Ranch, trail, roping, broodmare..."></div><div><label>Microchip / Permanent ID</label><input id="aHorseMicrochip" placeholder="Optional"></div></div></div>`)}
function ensureRecordFields(){if(el('rHorseFields'))return;const host=el('rSire')?.parentElement?.parentElement;if(!host)return;host.insertAdjacentHTML('afterend',`<div id="rHorseFields" class="equine-fields hidden"><h4>Equine Details</h4><div class="grid2"><div><label>Horse Class / Sex</label><select id="rEquineClass">${classes.map(x=>`<option>${x}</option>`).join('')}</select></div><div><label>Registered Name</label><input id="rHorseRegistered"></div></div><div class="grid2"><div><label>Color / Markings</label><input id="rHorseColor"></div><div><label>Height (hands)</label><input id="rHorseHeight" inputmode="decimal"></div></div><div class="grid2"><div><label>Primary Use / Discipline</label><input id="rHorseUse"></div><div><label>Microchip / Permanent ID</label><input id="rHorseMicrochip"></div></div><div class="grid2"><div><label>Farrier Notes / Schedule</label><input id="rHorseFarrier" placeholder="Trim/shoe schedule, farrier notes..."></div><div><label>Dental Notes / Schedule</label><input id="rHorseDental" placeholder="Float/dental schedule, notes..."></div></div></div>`)}
function breedingSection(){return[...document.querySelectorAll('#recordModal .section')].find(s=>s.querySelector('h3')?.textContent.trim()==='Breeding History')}
function calvingSection(){return[...document.querySelectorAll('#recordModal .section')].find(s=>['Calving History','Foaling History'].includes(s.querySelector('h3')?.textContent.trim()))}
function healthSection(){return[...document.querySelectorAll('#recordModal .section')].find(s=>s.querySelector('h3')?.textContent.trim()==='Health & Treatments')}
function ensureCarePanel(){let p=el('horseCarePanel');if(p)return p;const health=healthSection();if(!health)return null;p=document.createElement('div');p.id='horseCarePanel';p.className='section equine-care hidden';p.innerHTML=`<h3>🐎 Equine Care</h3><div class="muted">Track farrier, dental, Coggins, vaccinations, deworming, veterinary visits, and other horse-specific care.</div><div id="horseCareHist" class="equine-care-list"></div><div class="grid3"><div><label>Date</label><input id="eCareDate" type="date"></div><div><label>Care Type</label><select id="eCareType"><option>Farrier / Trim / Shoeing</option><option>Dental / Float</option><option>Coggins / Health Certificate</option><option>Vaccination</option><option>Deworming</option><option>Veterinary</option><option>Bodywork / Chiropractic</option><option>Other</option></select></div><div><label>Provider</label><input id="eCareProvider" placeholder="Farrier / veterinarian"></div></div><div class="grid2"><div><label>Cost</label><input id="eCareCost" inputmode="decimal" placeholder="Optional"></div><div><label>Notes</label><input id="eCareNotes"></div></div><button class="greenbtn" type="button" onclick="addEquineCare()">Add Equine Care</button>`;health.parentElement.insertBefore(p,health);return p}
function restoreGenericLabels(){labelFor('rTag','Tag');labelFor('rSex','Type');labelFor('rLocation','Location');labelFor('rDam','Dam');labelFor('rSire','Sire');labelFor('rStatus','Reproductive Status');labelFor('rFlag','Management Flag');labelFor('bSire','Bull / Sire');const c=calvingSection();if(c){c.style.display='';const h=c.querySelector('h3');if(h)h.textContent='Calving History';labelFor('cDate','Date');labelFor('cTag','Calf Tag');labelFor('cSex','Calf Sex');setOptions('cSex',['Heifer','Bull','Steer'])}el('rHorseFields')?.classList.add('hidden');el('horseCarePanel')?.classList.add('hidden')}
function prepareHorseForm(horse){ensureRecordFields();ensureCarePanel();if(!horse){restoreGenericLabels();return}labelFor('rTag','Horse Name / ID');labelFor('rSex','Record Type');labelFor('rLocation','Pasture / Stall / Location');labelFor('rDam','Dam');labelFor('rSire','Sire');labelFor('rStatus','Equine Reproductive Status');labelFor('rFlag','Activity / Health Status');labelFor('bSire','Stallion / Sire');setOptions('rStatus',['Unknown','Open','Bred','Pregnant','Foaled','Dry','Not Breeding']);setOptions('rFlag',['Normal','Working','Training','Watch','Treat','Resting','Retired']);setOptions('bMethod',['Natural Cover','AI','Embryo Transfer']);const b=breedingSection()?.querySelector('h3');if(b)b.textContent='Breeding History';const c=calvingSection();if(c){c.style.display='';const h=c.querySelector('h3');if(h)h.textContent='Foaling History';labelFor('cDate','Foaling Date');labelFor('cTag','Foal Name / ID');labelFor('cSex','Foal Sex');setOptions('cSex',['Filly','Colt','Unknown'])}el('rHorseFields')?.classList.remove('hidden');el('horseCarePanel')?.classList.remove('hidden')}
function decorateAdd(horse){ensureAddFields();labelFor('aTag',horse?'Horse Name / ID':'Tag Number');labelFor('aSex',horse?'Record Type':'Sex / Type');labelFor('aLocation',horse?'Pasture / Stall / Location':'Location / Pasture');labelFor('aDam',horse?'Dam':'Dam / Mother');labelFor('aSire',horse?'Sire':'Sire / Father');el('aHorseFields')?.classList.toggle('hidden',!horse);if(horse&&el('addTitle'))el('addTitle').textContent='Add Horse'}
function loadHorseFields(a){if(!isHorse(a))return;ensureRecordFields();el('rEquineClass').value=a.equineClass||'Unknown';el('rHorseRegistered').value=a.registeredName||'';el('rHorseColor').value=a.colorMarkings||'';el('rHorseHeight').value=a.heightHands??'';el('rHorseUse').value=a.primaryUse||'';el('rHorseMicrochip').value=a.equineMicrochip||'';el('rHorseFarrier').value=a.farrierNotes||'';el('rHorseDental').value=a.dentalNotes||'';if(el('rTitle'))el('rTitle').textContent=`🐎 ${horseName(a)} — Equine Record`;renderEquineCare(a)}
function saveHorseFields(a){if(!isHorse(a))return;a.equineClass=el('rEquineClass')?.value||'Unknown';a.registeredName=el('rHorseRegistered')?.value.trim()||'';a.colorMarkings=el('rHorseColor')?.value.trim()||'';const h=parseFloat(el('rHorseHeight')?.value);a.heightHands=Number.isFinite(h)?h:null;a.primaryUse=el('rHorseUse')?.value.trim()||'';a.equineMicrochip=el('rHorseMicrochip')?.value.trim()||'';a.farrierNotes=el('rHorseFarrier')?.value.trim()||'';a.dentalNotes=el('rHorseDental')?.value.trim()||''}
function renderEquineCare(a){const p=ensureCarePanel();if(!p||!isHorse(a)){p?.classList.add('hidden');return}const rows=(Array.isArray(a.health)?a.health:[]).filter(x=>x.equineCareType).slice().sort((x,y)=>String(y.date||'').localeCompare(String(x.date||'')));el('horseCareHist').innerHTML=rows.length?rows.map(x=>`<div class="equine-care-row"><b>${safe(x.date||'')} • ${safe(x.equineCareType)}</b><span>${safe(x.provider||'')}${x.cost!==null&&x.cost!==undefined?`${x.provider?' • ':''}$${Number(x.cost).toFixed(2)}`:''}</span>${x.notes?`<small>${safe(x.notes)}</small>`:''}</div>`).join(''):'<div class="muted">No equine-specific care entries yet.</div>';p.classList.remove('hidden')}
function addEquineCare(){const a=herd().find(x=>String(x.id)===String(typeof currentId!=='undefined'?currentId:''));if(!isHorse(a))return;const date=el('eCareDate')?.value;if(!date)return alert('Enter the care date.');const type=el('eCareType').value,provider=el('eCareProvider').value.trim(),raw=el('eCareCost').value.trim(),cost=raw===''?null:Number(raw),notes=el('eCareNotes').value.trim();if(raw!==''&&!Number.isFinite(cost))return alert('Check the cost amount.');if(!Array.isArray(a.health))a.health=[];a.health.push({date,treatment:`${type}${provider?` — ${provider}`:''}`,withdraw:'',notes:[cost!==null?`Cost: $${cost.toFixed(2)}`:'',notes].filter(Boolean).join(' • '),equineCareType:type,provider,cost});if(typeof save==='function')save();else localStorage.setItem('cv2-cattle',JSON.stringify(herd()));['eCareDate','eCareProvider','eCareCost','eCareNotes'].forEach(id=>{if(el(id))el(id).value=''});renderEquineCare(a);if(typeof renderHist==='function')renderHist(a);window.dispatchEvent(new Event('cv-equine-changed'))}
window.addEquineCare=addEquineCare;
function injectRegistry(){if(el('equineRegistry'))return;const m=document.createElement('div');m.id='equineRegistry';m.className='modal hidden';m.innerHTML=`<div class="sheet equine-registry-sheet"><div class="row"><div><h2>🐎 Horse Registry</h2><div class="muted">Equine records, pedigree, use, and care history.</div></div><button class="softbtn" onclick="closeEquineRegistry()">Close</button></div><div id="equineRegistryBody"></div></div>`;document.body.appendChild(m)}
function renderRegistry(){injectRegistry();const hs=herd().filter(isHorse).sort((a,b)=>horseName(a).localeCompare(horseName(b),undefined,{numeric:true}));const mares=hs.filter(h=>['Mare','Filly'].includes(h.equineClass)).length,geld=hs.filter(h=>h.equineClass==='Gelding').length,stall=hs.filter(h=>['Stallion','Colt'].includes(h.equineClass)).length;el('equineRegistryBody').innerHTML=`<div class="equine-summary"><div><span>Total Horses</span><b>${hs.length}</b></div><div><span>Mares / Fillies</span><b>${mares}</b></div><div><span>Geldings</span><b>${geld}</b></div><div><span>Stallions / Colts</span><b>${stall}</b></div></div><button class="greenbtn" style="width:100%;margin-bottom:12px" onclick="closeEquineRegistry();openOtherAnimal('${HORSE}')">Add Horse</button><div class="equine-registry-list">${hs.length?hs.map(h=>`<button class="equine-row" type="button" onclick="closeEquineRegistry();openRecord('${String(h.id).replace(/'/g,"\\'")}')"><span><b>🐎 ${safe(horseName(h))}</b><small>${safe(h.equineClass||'Class unknown')}${h.breed?` • ${safe(h.breed)}`:''}${h.colorMarkings?` • ${safe(h.colorMarkings)}`:''}${h.location?`<br>📍 ${safe(h.location)}`:''}${h.primaryUse?` • ${safe(h.primaryUse)}`:''}</small></span><span>›</span></button>`).join(''):'<div class="empty">No horses saved yet.</div>'}</div>`}
function openEquineRegistry(){renderRegistry();el('equineRegistry').classList.remove('hidden')}
function closeEquineRegistry(){el('equineRegistry')?.classList.add('hidden')}
window.openEquineRegistry=openEquineRegistry;window.closeEquineRegistry=closeEquineRegistry;
function ensureMenu(){if(el('equineRegistryBtn'))return;const secs=[...document.querySelectorAll('.farm-menu-section')],s=secs.find(x=>x.querySelector('h3')?.textContent.trim()==='Animals'),grid=s?.querySelector('.farm-menu-grid');if(!grid)return;const b=document.createElement('button');b.id='equineRegistryBtn';b.type='button';b.className='softbtn';b.textContent='Horse Registry';b.onclick=()=>{window.closeFarmMenu?.();openEquineRegistry()};grid.appendChild(b)}
function install(){ensureAddFields();ensureRecordFields();ensureCarePanel();injectRegistry();ensureMenu();const aSex=el('aSex');if(aSex&&!aSex.__cvHorseChange){aSex.__cvHorseChange=true;aSex.addEventListener('change',()=>decorateAdd(aSex.value===HORSE))}
if(typeof window.openOtherAnimal==='function'&&!window.openOtherAnimal.__cvEquine){const old=window.openOtherAnimal;window.openOtherAnimal=function(type){const r=old.apply(this,arguments);setTimeout(()=>decorateAdd(type===HORSE),0);return r};window.openOtherAnimal.__cvEquine=true}
if(typeof window.openAdd==='function'&&!window.openAdd.__cvEquine){const old=window.openAdd;window.openAdd=function(){const r=old.apply(this,arguments);setTimeout(()=>decorateAdd(el('aSex')?.value===HORSE),0);return r};window.openAdd.__cvEquine=true}
if(typeof window.saveNewAnimal==='function'&&!window.saveNewAnimal.__cvEquine){const old=window.saveNewAnimal;window.saveNewAnimal=async function(){const horse=el('aSex')?.value===HORSE,meta=horse?{equineClass:el('aEquineClass')?.value||'Unknown',registeredName:el('aHorseRegistered')?.value.trim()||'',colorMarkings:el('aHorseColor')?.value.trim()||'',heightHands:Number.isFinite(parseFloat(el('aHorseHeight')?.value))?parseFloat(el('aHorseHeight').value):null,primaryUse:el('aHorseUse')?.value.trim()||'',equineMicrochip:el('aHorseMicrochip')?.value.trim()||'',farrierNotes:'',dentalNotes:''}:null,before=new Set(herd().map(a=>String(a.id)));const r=await old.apply(this,arguments);if(horse){const added=herd().find(a=>!before.has(String(a.id)));if(added){Object.assign(added,meta);if(typeof save==='function')save();window.dispatchEvent(new Event('cv-equine-changed'))}}return r};window.saveNewAnimal.__cvEquine=true}
if(typeof window.openRecord==='function'&&!window.openRecord.__cvEquine){const old=window.openRecord;window.openRecord=async function(id){const a=herd().find(x=>String(x.id)===String(id));prepareHorseForm(isHorse(a));const r=await old.apply(this,arguments);if(isHorse(a)){prepareHorseForm(true);loadHorseFields(a)}return r};window.openRecord.__cvEquine=true}
if(typeof window.saveRecord==='function'&&!window.saveRecord.__cvEquine){const old=window.saveRecord;window.saveRecord=function(){const a=herd().find(x=>String(x.id)===String(typeof currentId!=='undefined'?currentId:''));if(isHorse(a))saveHorseFields(a);const r=old.apply(this,arguments);if(isHorse(a)){window.dispatchEvent(new Event('cv-equine-changed'));setTimeout(()=>{prepareHorseForm(true);loadHorseFields(a)},0)}return r};window.saveRecord.__cvEquine=true}
if(typeof window.addBreeding==='function'&&!window.addBreeding.__cvEquine){const old=window.addBreeding;window.addBreeding=function(){const a=herd().find(x=>String(x.id)===String(typeof currentId!=='undefined'?currentId:''));const r=old.apply(this,arguments);if(isHorse(a))window.dispatchEvent(new Event('cv-equine-changed'));return r};window.addBreeding.__cvEquine=true}
if(typeof window.addCalving==='function'&&!window.addCalving.__cvEquine){const old=window.addCalving;window.addCalving=function(){const a=herd().find(x=>String(x.id)===String(typeof currentId!=='undefined'?currentId:''));const r=old.apply(this,arguments);if(isHorse(a)){setTimeout(()=>prepareHorseForm(true),0);window.dispatchEvent(new Event('cv-equine-changed'))}return r};window.addCalving.__cvEquine=true}
}
install();setInterval(ensureMenu,1500);
})();