(function(){
const DOG='Livestock Guardian Dog',HORSE='Horse';
let meds=JSON.parse(localStorage.getItem('cv2-meds')||'[]');
function saveMeds(){try{localStorage.setItem('cv2-meds',JSON.stringify(meds));renderMedList();return true}catch(e){console.error(e);alert('This browser is low on local storage. The medication change could not be saved on this device. Remove an unnecessary local file or try again after your cloud/media sync finishes.');return false}}
function addOption(sel,val){if(!sel||[...sel.options].some(o=>o.value===val))return;const o=document.createElement('option');o.value=val;o.textContent=val;sel.appendChild(o)}
function ensureOtherAnimalOptions(){['aSex','rSex'].forEach(id=>{addOption($(id),DOG);addOption($(id),HORSE)});document.querySelectorAll('select.bulk-sex').forEach(s=>{addOption(s,DOG);addOption(s,HORSE)})}
function openFarmMenu(){ensureOtherAnimalOptions();renderMedList();$('farmDrawerBackdrop').classList.remove('hidden');$('farmDrawer').classList.remove('hidden')}
function closeFarmMenu(){$('farmDrawerBackdrop').classList.add('hidden');$('farmDrawer').classList.add('hidden')}
window.openFarmMenu=openFarmMenu;window.closeFarmMenu=closeFarmMenu;
function openOtherAnimal(type){closeFarmMenu();openAdd();ensureOtherAnimalOptions();$('aSex').value=type;$('addTitle').textContent=type===HORSE?'Add Horse':'Add Livestock Guardian Dog'}
window.openOtherAnimal=openOtherAnimal;
function compressMedPhoto(file){return new Promise((res,rej)=>{if(!file)return res('');const u=URL.createObjectURL(file),im=new Image;im.onload=()=>{const s=Math.min(1,700/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(im.width*s));c.height=Math.max(1,Math.round(im.height*s));c.getContext('2d').drawImage(im,0,0,c.width,c.height);URL.revokeObjectURL(u);res(c.toDataURL('image/jpeg',.62))};im.onerror=e=>{URL.revokeObjectURL(u);rej(e)};im.src=u})}
async function saveMedication(){const name=$('medName').value.trim();if(!name)return alert('Enter the medication name.');const dose=parseFloat($('medDose').value),basis=parseFloat($('medBasis').value);if((Number.isFinite(dose)&&!Number.isFinite(basis))||(!Number.isFinite(dose)&&Number.isFinite(basis)))return alert('Enter both the label dose and the body-weight basis, or leave both blank.');let photo='';try{photo=await compressMedPhoto($('medPhoto').files[0])}catch(e){console.error(e);alert('The label photo could not be processed. The medication can still be saved without it.')}const item={id:(typeof newLocalId==='function'?newLocalId():String(Date.now()+Math.random())),name,dose:Number.isFinite(dose)?dose:null,basis:Number.isFinite(basis)?basis:null,unit:$('medUnit').value,route:$('medRoute').value.trim(),withdraw:$('medWithdraw').value.trim(),lot:$('medLot').value.trim(),expires:$('medExpires').value,notes:$('medNotes').value.trim(),photo,created:new Date().toISOString()};meds.push(item);if(!saveMeds()){meds=meds.filter(m=>m!==item);return}['medName','medDose','medBasis','medRoute','medWithdraw','medLot','medExpires','medNotes'].forEach(id=>$(id).value='');$('medPhoto').value='';alert('Medication saved. If Cloud is signed in, it will be included in the next backup.')}
window.saveMedication=saveMedication;
function deleteMedication(id){if(!confirm('Remove this medication from the cabinet?'))return;const before=meds;meds=meds.filter(m=>String(m.id)!==String(id));if(!saveMeds())meds=before}
window.deleteMedication=deleteMedication;
function calcMedication(id){const m=meds.find(x=>String(x.id)===String(id));if(!m)return;const w=parseFloat(prompt(`Animal weight in pounds for ${m.name}:`,''));if(!Number.isFinite(w)||w<=0)return;if(!Number.isFinite(m.dose)||!Number.isFinite(m.basis)||m.basis<=0)return alert('No label dose has been saved for this product yet. Edit/re-add it using the current bottle label or veterinarian directions.');const amt=w/m.basis*m.dose;alert(`${m.name}\n${w.toLocaleString()} lb animal → ${amt.toFixed(2)} ${m.unit}\nSaved basis: ${m.dose} ${m.unit} per ${m.basis} lb.\n\nVerify the current product label and veterinarian directions before treatment.`)}
window.calcMedication=calcMedication;
function renderMedList(){const el=$('medList');if(!el)return;el.innerHTML=meds.length?meds.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(m=>`<div class="med-card"><div class="med-card-head">${m.photo?`<img class="med-thumb" src="${m.photo}" alt="${esc(m.name)} label">`:'<div class="med-thumb"></div>'}<div><h4>${esc(m.name)}</h4><div class="med-meta">${Number.isFinite(m.dose)?`${esc(m.dose)} ${esc(m.unit)} per ${esc(m.basis)} lb`:'Dose not entered'}${m.route?` • ${esc(m.route)}`:''}${m.withdraw?`<br>Withdrawal: ${esc(m.withdraw)}`:''}${m.expires?`<br>Expires: ${esc(m.expires)}`:''}</div></div></div><div class="med-actions"><button class="greenbtn" onclick="calcMedication('${m.id}')">Dose Calculator</button><button class="softbtn" onclick="deleteMedication('${m.id}')">Remove</button></div></div>`).join(''):'<div class="muted">No medications saved yet. Add the bottle or label once, then use it from here.</div>'}
function injectDrawer(){if($('farmDrawer'))return;const back=document.createElement('div');back.id='farmDrawerBackdrop';back.className='farm-drawer-backdrop hidden';back.onclick=closeFarmMenu;document.body.appendChild(back);const d=document.createElement('aside');d.id='farmDrawer';d.className='farm-drawer hidden';d.innerHTML=`<div class="farm-drawer-head"><div><h2>Farm Tools</h2><div class="muted">Keep extra tools here so the main page stays simple.</div></div><button class="softbtn" onclick="closeFarmMenu()">Close</button></div><div class="farm-menu-section"><h3>Records</h3><div class="farm-menu-grid">${typeof window.openPaperImport==='function'?'<button class="softbtn" onclick="openPaperImport()">Import Paper Herd Records</button>':''}</div></div><div class="farm-menu-section"><h3>Animals</h3><div class="farm-menu-grid"><button class="softbtn" onclick="openOtherAnimal('${HORSE}')">Add Horse</button><button class="softbtn" onclick="openOtherAnimal('${DOG}')">Add Livestock Guardian Dog</button></div></div><div class="farm-menu-section"><h3>Medication Cabinet</h3><div class="muted">Save products on hand and the dose exactly as it appears on the current label or veterinarian directions.</div><div class="med-form-grid" style="margin-top:10px"><div class="wide"><label>Medication / Product</label><input id="medName" placeholder="Example: Draxxin, LA-200, LA-300"></div><div><label>Label dose</label><input id="medDose" inputmode="decimal" placeholder="Example: 1.5"></div><div><label>Per body weight</label><input id="medBasis" inputmode="decimal" placeholder="Example: 100 lb"></div><div><label>Unit</label><select id="medUnit"><option>mL</option><option>cc</option><option>oz</option><option>tablet(s)</option></select></div><div><label>Route</label><input id="medRoute" placeholder="SQ, IM, oral..."></div><div><label>Withdrawal</label><input id="medWithdraw" placeholder="Enter from label"></div><div><label>Lot #</label><input id="medLot"></div><div><label>Expiration</label><input id="medExpires" type="date"></div><div class="wide"><label>Photo of bottle / label</label><input id="medPhoto" type="file" accept="image/*" capture="environment"></div><div class="wide"><label>Notes</label><textarea id="medNotes"></textarea></div></div><button class="greenbtn" style="width:100%;margin-top:10px" onclick="saveMedication()">Save Medication</button><div class="farm-note muted">The calculator only uses the dose you save from the current label or veterinarian instructions. Cattle Vision does not guess a drug dose.</div><div id="medList" class="med-list"></div></div><div class="farm-menu-section"><h3>More</h3><div class="farm-menu-grid"><button class="softbtn" onclick="openSettings();closeFarmMenu()">Settings / Backup</button>${typeof window.openFeedback==='function'?'<button class="softbtn" onclick="openFeedback();closeFarmMenu()">Send Feedback</button>':''}</div></div>`;document.body.appendChild(d);renderMedList()}
function hookMenu(){const b=document.querySelector('.menu');if(!b)return;b.type='button';b.setAttribute('aria-label','Open farm tools');b.onclick=openFarmMenu}
const originalRender=window.render;if(typeof originalRender==='function')window.render=async function(){const r=await originalRender.apply(this,arguments);ensureOtherAnimalOptions();return r};
const originalCloseAdd=window.closeAdd;if(typeof originalCloseAdd==='function')window.closeAdd=function(){const r=originalCloseAdd.apply(this,arguments);if($('addTitle'))$('addTitle').textContent='Add Animal';return r};
injectDrawer();hookMenu();ensureOtherAnimalOptions();if(typeof window.render==='function')window.render();
})();