(function(){
  if(window.__cvFeedbackInstalled)return;window.__cvFeedbackInstalled=true;
  let rec=null, listening=false;
  function el(id){return document.getElementById(id)}
  function escF(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function categorize(text){const t=(text||'').toLowerCase();if(/bug|broken|won't|wont|doesn't|doesnt|error|crash|not working|problem/.test(t))return 'Bug / Problem';if(/confus|hard to|don't understand|dont understand|where do|how do/.test(t))return 'Confusing / Hard to Use';if(/idea|should|could|would like|add|feature|wish/.test(t))return 'Idea / Feature Request';return 'General Feedback'}
  function summarize(){const text=el('feedbackText').value.trim();const cat=categorize(text);el('feedbackCategory').value=cat;const parts=[];if(text)parts.push(text);if(el('feedbackScreen').value.trim())parts.push('Where in app: '+el('feedbackScreen').value.trim());el('feedbackPreview').textContent=parts.join('\n\n')||'Your spoken or typed feedback will appear here.';}
  function openFeedback(){el('feedbackModal').classList.remove('hidden');setTimeout(()=>el('feedbackText').focus(),100);}
  function closeFeedback(){if(rec&&listening)try{rec.stop()}catch{}listening=false;el('feedbackModal').classList.add('hidden')}
  function startVoice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){el('feedbackHelp').textContent='Direct voice capture is not available in this browser. Tap the feedback box and use the microphone on your phone keyboard to dictate, then tap Prepare Feedback.';el('feedbackText').focus();return;}if(listening){try{rec.stop()}catch{}return;}rec=new SR();rec.lang='en-US';rec.continuous=true;rec.interimResults=true;let base=el('feedbackText').value.trim();rec.onstart=()=>{listening=true;el('feedbackVoiceBtn').textContent='Stop Listening';el('feedbackHelp').textContent='Listening… talk normally about what worked, what did not, or what you would change.'};rec.onresult=e=>{let final='',interim='';for(let i=e.resultIndex;i<e.results.length;i++){const s=e.results[i][0].transcript;if(e.results[i].isFinal)final+=s+' ';else interim+=s;}if(final){base=(base+' '+final).trim();el('feedbackText').value=base;summarize()}el('feedbackLive').textContent=interim?('Hearing: '+interim):''};rec.onerror=()=>{el('feedbackHelp').textContent='Voice capture stopped. You can keep typing or use the phone keyboard microphone.'};rec.onend=()=>{listening=false;el('feedbackVoiceBtn').textContent='Talk Feedback';el('feedbackLive').textContent=''};try{rec.start()}catch{}}
  async function shareFeedback(){summarize();const text=el('feedbackText').value.trim();if(!text)return alert('Say or type some feedback first.');const cat=el('feedbackCategory').value;const where=el('feedbackScreen').value.trim();const msg=`Cattle Vision Tester Feedback\nCategory: ${cat}${where?`\nWhere in app: ${where}`:''}\n\n${text}\n\nSent from Cattle Vision test app.`;try{if(navigator.share){await navigator.share({title:'Cattle Vision Feedback',text:msg});return;}if(navigator.clipboard){await navigator.clipboard.writeText(msg);alert('Feedback copied. Paste it into a text or email to send it.');return;}}catch(e){if(e&&e.name==='AbortError')return;}const ta=document.createElement('textarea');ta.value=msg;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();alert('Feedback copied. Paste it into a text or email to send it.');}
  const css=document.createElement('link');css.rel='stylesheet';css.href='feedback.css?v=1';document.head.appendChild(css);
  const btn=document.createElement('button');btn.type='button';btn.className='feedback-fab';btn.textContent='Send Feedback';btn.onclick=openFeedback;document.body.appendChild(btn);
  const modal=document.createElement('div');modal.id='feedbackModal';modal.className='modal hidden';modal.innerHTML=`<div class="sheet feedback-sheet"><div class="row"><div><h2>Send Feedback</h2><div class="muted">Talk naturally. Cattle Vision turns your voice into text and packages it so it is easy to understand and share.</div></div><button class="softbtn" type="button" id="feedbackClose">Close</button></div><div class="feedback-voice-row"><button class="greenbtn" type="button" id="feedbackVoiceBtn">Talk Feedback</button><span id="feedbackHelp" class="muted">Say what you liked, what did not work, or what you would change.</span></div><div id="feedbackLive" class="feedback-live"></div><label>Feedback</label><textarea id="feedbackText" rows="7" placeholder="Example: I was trying to move 12 cows to another pasture and the button was hard to find..."></textarea><div class="grid2"><div><label>Where in the app? (optional)</label><input id="feedbackScreen" placeholder="Pastures, bulk photos, animal record..."></div><div><label>Category</label><select id="feedbackCategory"><option>General Feedback</option><option>Bug / Problem</option><option>Confusing / Hard to Use</option><option>Idea / Feature Request</option></select></div></div><button class="softbtn" type="button" id="feedbackPrepare">Prepare Feedback</button><div id="feedbackPreview" class="feedback-preview">Your spoken or typed feedback will appear here.</div><button class="greenbtn" style="width:100%" type="button" id="feedbackShare">Share Feedback</button><div class="muted feedback-note">On iPhone this opens the Share sheet so the tester can send it by text, email, AirDrop, Notes, or another app. If direct microphone capture is unavailable, use the microphone on the iPhone keyboard.</div></div>`;document.body.appendChild(modal);
  el('feedbackClose').onclick=closeFeedback;el('feedbackVoiceBtn').onclick=startVoice;el('feedbackPrepare').onclick=summarize;el('feedbackShare').onclick=shareFeedback;el('feedbackText').addEventListener('input',summarize);el('feedbackScreen').addEventListener('input',summarize);
  window.openFeedback=openFeedback;
})();