(function(){
const DOG='Livestock Guardian Dog';
function addDogOption(sel){if(!sel||[...sel.options].some(o=>o.value===DOG))return;const o=document.createElement('option');o.value=DOG;o.textContent=DOG;sel.appendChild(o)}
function setupDogOptions(){addDogOption($('aSex'));addDogOption($('rSex'));document.querySelectorAll('select.bulk-sex').forEach(addDogOption)}
function isDog(a){return a&&a.sex===DOG}
function currentPastureStart(a,pasture){const hist=Array.isArray(a.locationHistory)?a.locationHistory:[];for(let i=hist.length-1;i>=0;i--){const h=hist[i];if(String(h.to||'').toLowerCase()===String(pasture||'').toLowerCase()&&h.date)return new Date(h.date)}if(a.created)return new Date(a.created);return null}
function daysSince(d){if(!d||Number.isNaN(d.getTime()))return null;const now=new Date();return Math.max(0,Math.floor((now-d)/86400000))}
function grazingText(animals,pasture){const cattleOnly=animals.filter(a=>!isDog(a));const vals=cattleOnly.map(a=>daysSince(currentPastureStart(a,pasture))).filter(v=>v!==null);if(!vals.length)return '';const min=Math.min(...vals),max=Math.max(...vals);return min===max?`${min} day${min===1?'':'s'} on grass`:`${min}–${max} days on grass`}
function decoratePastures(){document.querySelectorAll('.pasture-card').forEach(card=>{const name=card.querySelector('.pasture-card-head strong')?.textContent?.trim();if(!name)return;const animals=cattle.filter(a=>String(a.location||'').toLowerCase()===name.toLowerCase());const dogs=animals.filter(isDog).length,cows=animals.length-dogs;const count=card.querySelector('.pasture-card-head span');const countText=dogs?`${cows} cattle • ${dogs} guardian dog${dogs===1?'':'s'}`:`${cows} head`;if(count&&count.textContent!==countText)count.textContent=countText;let info=card.querySelector('.grass-days');if(!info){info=document.createElement('div');info.className='grass-days muted';info.style.marginTop='6px';card.querySelector('.pasture-card-head>div')?.appendChild(info)}const gt=grazingText(animals,name),txt=gt?`Pasture time: ${gt}`:'';if(info&&info.textContent!==txt)info.textContent=txt})}
window.cvDecoratePastures=decoratePastures;
function openGuardianDog(){openAdd();setupDogOptions();$('aSex').value=DOG;$('addTitle').textContent='Add Livestock Guardian Dog'}
window.openGuardianDog=openGuardianDog;
const origCloseAdd=window.closeAdd;if(typeof origCloseAdd==='function')window.closeAdd=function(){origCloseAdd();if($('addTitle'))$('addTitle').textContent='Add Animal'};
const origRender=window.render;if(typeof origRender==='function')window.render=async function(){const out=await origRender.apply(this,arguments);if($('totalN'))$('totalN').textContent=cattle.filter(a=>!isDog(a)).length;setupDogOptions();document.querySelectorAll('.animal').forEach(el=>{if(el.querySelector('.chip')?.textContent===DOG){const th=el.querySelector('.thumb');if(th&&!th.tagName.match(/IMG/i))th.textContent='🐕'}});return out};
const origPastureRender=window.renderPastureManager;if(typeof origPastureRender==='function')window.renderPastureManager=function(){const out=origPastureRender.apply(this,arguments);decoratePastures();return out};
const origBulkRender=window.renderBulkSorter;if(typeof origBulkRender==='function')window.renderBulkSorter=function(){const out=origBulkRender.apply(this,arguments);setupDogOptions();return out};
const origSaveRecord=window.saveRecord;if(typeof origSaveRecord==='function')window.saveRecord=function(){const a=cattle.find(x=>String(x.id)===String(currentId));const from=a?.location||'',to=$('rLocation')?.value.trim()||'';if(a&&from!==to){a.locationHistory=Array.isArray(a.locationHistory)?a.locationHistory:[];a.locationHistory.push({from,to,date:new Date().toISOString()})}return origSaveRecord.apply(this,arguments)};
setupDogOptions();if(typeof window.render==='function')window.render();
})();