(function(){
if(window.__cvGuardianDogsInstalled)return;window.__cvGuardianDogsInstalled=true;
const DOG='Livestock Guardian Dog';
const el=id=>document.getElementById(id);
const safe=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const herd=()=>typeof cattle!=='undefined'&&Array.isArray(cattle)?cattle:[];
const isDog=a=>a&&a.sex===DOG;
const dogName=a=>String(a?.tag||'').trim()||'Unnamed dog';
const findDogByName=n=>herd().find(a=>isDog(a)&&dogName(a).toLowerCase()===String(n||'').trim().toLowerCase());
function setOptions(id,values){const s=el(id);if(!s)return;const cur=s.value;s.innerHTML=values.map(v=>`<option>${safe(v)}</option>`).join('');if(values.includes(cur))s.value=cur}
function labelFor(id,text){const i=el(id),lab=i?.parentElement?.querySelector('label');if(lab)lab.childNodes[0].textContent=text+' '}
function hideAiField(hide){['aDoubleTagged','rDoubleTagged'].forEach(id=>{const x=el(id)?.closest('.ai-double-field');if(x)x.style.display=hide?'none':''})}
function ensureDogAddFields(){if(el('aDogFields'))return;const host=el('aBreed')?.parentElement?.parentElement;if(!host)return;host.insertAdjacentHTML('afterend',`<div id="aDogFields" class="dog-record-fields hidden"><h4>Canine Details</h4><div class="grid2"><div><label>Canine Sex</label><select id="aCanineSex"><option>Unknown</option><option>Female</option><option>Male</option></select></div><div><label>Working Role</label><input id="aDogRole" placeholder="Guardian, breeding female, young prospect..."></div></div><div class="grid2"><div><label>Guardian Status</label><select id="aDogStatus"><option>Working</option><option>Puppy / Training</option><option>Breeding</option><option>Retired</option><option>Companion</option></select></div><div><label>Altered Status</label><select id="aDogAltered"><option>Unknown</option><option>Intact</option><option>Spayed</option><option>Neutered</option></select></div></div><label>Microchip / Permanent ID</label><input id="aDogMicrochip" placeholder="Optional"></div>`)}
function ensureDogRecordFields(){if(el('rDogFields'))return;const host=el('rSire')?.parentElement?.parentElement;if(!host)return;host.insertAdjacentHTML('afterend',`<div id="rDogFields" class="dog-record-fields hidden"><h4>Canine Details</h4><div class="grid2"><div><label>Canine Sex</label><select id="rCanineSex"><option>Unknown</option><option>Female</option><option>Male</option></select></div><div><label>Working Role</label><input id="rDogRole" placeholder="Guardian, breeding female, young prospect..."></div></div><div class="grid2"><div><label>Guardian Status</label><select id="rDogStatus"><option>Working</option><option>Puppy / Training</option><option>Breeding</option><option>Retired</option><option>Companion</option></select></div><div><label>Altered Status</label><select id="rDogAltered"><option>Unknown</option><option>Intact</option><option>Spayed</option><option>Neutered</option></select></div></div><label>Microchip / Permanent ID</label><input id="rDogMicrochip" placeholder="Optional"></div>`)}
function calvingSection(){return [...document.querySelectorAll('#recordModal .section')].find(s=>s.querySelector('h3')?.textContent.trim()==='Calving History')}
function breedingSection(){return [...document.querySelectorAll('#recordModal .section')].find(s=>s.querySelector('h3')?.textContent.trim()==='Breeding History')}
function familyHost(){let x=el('dogFamilyPanel');if(x)return x;const health=[...document.querySelectorAll('#recordModal .section')].find(s=>s.querySelector('h3')?.textContent.trim()==='Health & Treatments');if(!health)return null;x=document.createElement('div');x.id='dogFamilyPanel';x.className='dog-family hidden';health.parentElement.insertBefore(x,health);return x}
function prepareDogForm(dog){ensureDogRecordFields();labelFor('rTag',dog?'Name / ID':'Tag');labelFor('rSex',dog?'Record Type':'Type');labelFor('rLocation',dog?'Pasture / Working Area':'Location');labelFor('rDam',dog?'Dam (mother)':'Dam');labelFor('rSire',dog?'Sire (father)':'Sire');labelFor('rStatus',dog?'Canine Reproductive Status':'Reproductive Status');labelFor('rFlag',dog?'Working / Health Flag':'Management Flag');labelFor('bSire',dog?'Mate / Sire':'Bull / Sire');if(dog){setOptions('rStatus',['Unknown','Open','Bred','Pregnant','Whelped','Not Breeding']);setOptions('rFlag',['Normal','Working','Training','Watch','Treat','Retired']);setOptions('bMethod',['Natural Breeding','AI']);const b=breedingSection()?.querySelector('h3');if(b)b.textContent='Breeding History';const c=calvingSection();if(c)c.style.display='none';el('rDogFields')?.classList.remove('hidden');hideAiField(true)}else{setOptions('rStatus',['Unknown','Open','Bred','Pregnant','Calved','Dry']);setOptions('rFlag',['Normal','Watch','Treat','Keep Replacement','Cull']);setOptions('bMethod',['AI','Natural Service','Cleanup Bull','Embryo Transfer']);const c=calvingSection();if(c)c.style.display='';el('rDogFields')?.classList.add('hidden');el('dogFamilyPanel')?.classList.add('hidden');hideAiField(false)}}
function decorateAdd(isCanine){ensureDogAddFields();labelFor('aTag',isCanine?'Name / ID':'Tag Number');labelFor('aSex',isCanine?'Record Type':'Sex / Type');labelFor('aLocation',isCanine?'Pasture / Working Area':'Location / Pasture');labelFor('aDam',isCanine?'Dam (mother)':'Dam / Mother');labelFor('aSire',isCanine?'Sire (father)':'Sire / Father');el('aDogFields')?.classList.toggle('hidden',!isCanine);hideAiField(isCanine);if(isCanine&&el('addTitle'))el('addTitle').textContent='Add Livestock Guardian Dog'}
function parentCard(title,name){if(!name)return `<div class="dog-family-card"><span>${title}</span><b>Not recorded</b></div>`;const p=findDogByName(name);const gp=p?[p.dam,p.sire].filter(Boolean).join(' × '):'';return `<div class="dog-family-card"><span>${title}</span>${p?`<button class="dog-link" onclick="openRecord('${String(p.id).replace(/'/g,"\\'")}')">${safe(dogName(p))}</button>`:`<b>${safe(name)}</b>`}${gp?`<small>Parents: ${safe(gp)}</small>`:''}</div>`}
function renderFamily(a){const host=familyHost();if(!host||!isDog(a))return;const name=dogName(a).toLowerCase(),kids=herd().filter(x=>isDog(x)&&x.id!==a.id&&[x.dam,x.sire].some(v=>String(v||'').trim().toLowerCase()===name)).sort((x,y)=>String(x.birth||'').localeCompare(String(y.birth||'')));host.innerHTML=`<h3>🐕 Guardian Dog Family Tree</h3><div class="muted">Canine lineage stays separate from cattle records. Add puppies here and Cattle Vision links the dam and sire automatically.</div><div class="dog-family-grid" style="margin-top:10px">${parentCard('Dam',a.dam)}${parentCard('Sire',a.sire)}</div><div style="margin-top:13px"><b>Offspring / Puppies (${kids.length})</b></div><div class="dog-offspring">${kids.length?kids.map(k=>`<button type="button" onclick="openRecord('${String(k.id).replace(/'/g,"\\'")}')"><span><b>${safe(dogName(k))}</b><small>${safe(k.canineSex||'Sex unknown')}${k.birth?` • born ${safe(k.birth)}`:''}${k.breed?` • ${safe(k.breed)}`:''}</small></span><span>›</span></button>`).join(''):'<div class="muted">No linked puppies yet.</div>'}</div><div class="dog-puppy-actions"><button class="greenbtn" type="button" onclick="openPuppyModal('${String(a.id).replace(/'/g,"\\'")}')">Add Puppy to This Lineage</button><button class="softbtn" type="button" onclick="openGuardianRegistry()">Open Guardian Dog Registry</button></div>`;host.classList.remove('hidden')}
function loadDogFields(a){if(!isDog(a))return;ensureDogRecordFields();el('rCanineSex').value=a.canineSex||'Unknown';el('rDogRole').value=a.workingRole||'';el('rDogStatus').value=a.guardianStatus||'Working';el('rDogMicrochip').value=a.microchip||'';el('rDogAltered').value=a.alteredStatus||'Unknown';if(el('rTitle'))el('rTitle').textContent=`🐕 ${dogName(a)} — Guardian Dog`;renderFamily(a)}
function saveDogFields(a){if(!isDog(a))return;a.canineSex=el('rCanineSex')?.value||'Unknown';a.workingRole=el('rDogRole')?.value.trim()||'';a.guardianStatus=el('rDogStatus')?.value||'Working';a.microchip=el('rDogMicrochip')?.value.trim()||'';a.alteredStatus=el('rDogAltered')?.value||'Unknown'}
function injectRegistry(){if(el('guardianDogRegistry'))return;const m=document.createElement('div');m.id='guardianDogRegistry';m.className='modal hidden';m.innerHTML=`<div class="sheet dog-registry-sheet"><div class="row"><div><h2>🐕 Guardian Dog Registry</h2><div class="muted">Canine records, working status, and family lines.</div></div><button class="softbtn" onclick="closeGuardianRegistry()">Close</button></div><div id="guardianDogRegistryBody"></div></div>`;document.body.appendChild(m)}
function renderRegistry(){injectRegistry();const dogs=herd().filter(isDog).sort((a,b)=>dogName(a).localeCompare(dogName(b),undefined,{numeric:true})),f=dogs.filter(d=>d.canineSex==='Female').length,m=dogs.filter(d=>d.canineSex==='Male').length,puppies=dogs.filter(d=>d.guardianStatus==='Puppy / Training').length;el('guardianDogRegistryBody').innerHTML=`<div class="dog-summary"><div><span>Total Dogs</span><b>${dogs.length}</b></div><div><span>Females</span><b>${f}</b></div><div><span>Males</span><b>${m}</b></div><div><span>Puppies / Training</span><b>${puppies}</b></div></div><button class="greenbtn" style="width:100%;margin-bottom:12px" onclick="closeGuardianRegistry();openOtherAnimal('${DOG}')">Add Guardian Dog</button><div class="dog-registry-list">${dogs.length?dogs.map(d=>`<button class="dog-row" type="button" onclick="closeGuardianRegistry();openRecord('${String(d.id).replace(/'/g,"\\'")}')"><span><b>🐕 ${safe(dogName(d))}</b><small>${safe(d.canineSex||'Sex unknown')}${d.breed?` • ${safe(d.breed)}`:''}${d.location?` • ${safe(d.location)}`:''}<br>${d.dam?`Dam ${safe(d.dam)}`:''}${d.dam&&d.sire?' • ':''}${d.sire?`Sire ${safe(d.sire)}`:''}</small></span><span class="dog-badge">${safe(d.guardianStatus||'Working')}</span></button>`).join(''):'<div class="empty">No guardian dogs saved yet.</div>'}</div>`}
function openGuardianRegistry(){renderRegistry();el('guardianDogRegistry').classList.remove('hidden')}
function closeGuardianRegistry(){el('guardianDogRegistry')?.classList.add('hidden')}
window.openGuardianRegistry=openGuardianRegistry;window.closeGuardianRegistry=closeGuardianRegistry;
function ensureMenu(){if(el('guardianDogRegistryBtn'))return;const secs=[...document.querySelectorAll('.farm-menu-section')],s=secs.find(x=>x.querySelector('h3')?.textContent.trim()==='Animals');const grid=s?.querySelector('.farm-menu-grid');if(!grid)return;const b=document.createElement('button');b.id='guardianDogRegistryBtn';b.type='button';b.className='softbtn';b.textContent='Guardian Dog Registry';b.onclick=()=>{window.closeFarmMenu?.();openGuardianRegistry()};grid.appendChild(b)}
function injectPuppyModal(){if(el('dogPuppyModal'))return;const m=document.createElement('div');m.id='dogPuppyModal';m.className='modal hidden';m.innerHTML=`<div class="sheet" style="max-width:620px"><div class="row"><div><h2>Add Puppy</h2><div class="muted" id="dogPuppyParentText"></div></div><button class="softbtn" onclick="closePuppyModal()">Close</button></div><label>Puppy Name / ID</label><input id="dogPuppyName" placeholder="Name or permanent ID"><div class="grid2"><div><label>Canine Sex</label><select id="dogPuppySex"><option>Unknown</option><option>Female</option><option>Male</option></select></div><div><label>Birth Date</label><input id="dogPuppyBirth" type="date"></div></div><div class="grid2"><div><label>Breed</label><input id="dogPuppyBreed"></div><div><label>This dog is the puppy's</label><select id="dogParentRole"><option>Dam</option><option>Sire</option></select></div></div><label>Other Parent</label><input id="dogOtherParent" placeholder="Name / ID if known"><label>Notes</label><textarea id="dogPuppyNotes"></textarea><button class="greenbtn" style="width:100%" onclick="savePuppy()">Save Puppy & Link Lineage</button></div>`;document.body.appendChild(m)}
let puppyParentId=null;
function openPuppyModal(parentId){injectPuppyModal();const p=herd().find(a=>String(a.id)===String(parentId));if(!p||!isDog(p))return;puppyParentId=p.id;el('dogPuppyParentText').textContent=`Linking this puppy to ${dogName(p)}.`;el('dogParentRole').value=p.canineSex==='Male'?'Sire':'Dam';el('dogPuppyBreed').value=p.breed||'';['dogPuppyName','dogPuppyBirth','dogOtherParent','dogPuppyNotes'].forEach(id=>el(id).value='');el('dogPuppySex').value='Unknown';el('dogPuppyModal').classList.remove('hidden')}
function closePuppyModal(){el('dogPuppyModal')?.classList.add('hidden');puppyParentId=null}
function savePuppy(){const p=herd().find(a=>String(a.id)===String(puppyParentId)),name=el('dogPuppyName')?.value.trim();if(!p||!isDog(p))return;if(!name)return alert('Enter the puppy name or ID.');if(herd().some(a=>isDog(a)&&dogName(a).toLowerCase()===name.toLowerCase()))return alert('A guardian dog with that name / ID already exists.');const role=el('dogParentRole').value,other=el('dogOtherParent').value.trim(),created=new Date().toISOString(),a=norm({id:typeof newLocalId==='function'?newLocalId():String(Date.now()),tag:name,sex:DOG,breed:el('dogPuppyBreed').value.trim(),birth:el('dogPuppyBirth').value,location:p.location||'',dam:role==='Dam'?dogName(p):other,sire:role==='Sire'?dogName(p):other,notes:el('dogPuppyNotes').value.trim(),created});a.canineSex=el('dogPuppySex').value;a.workingRole='Guardian prospect';a.guardianStatus='Puppy / Training';a.alteredStatus='Unknown';a.microchip='';if(a.location)a.locationHistory=[{from:'',to:a.location,date:created}];cattle.push(a);save();window.dispatchEvent(new Event('cv-dog-changed'));closePuppyModal();renderFamily(p);alert(`${name} saved and linked to ${dogName(p)}.`)}
window.openPuppyModal=openPuppyModal;window.closePuppyModal=closePuppyModal;window.savePuppy=savePuppy;
function install(){ensureDogAddFields();ensureDogRecordFields();injectRegistry();injectPuppyModal();ensureMenu();const aSex=el('aSex');if(aSex&&!aSex.__cvDogChange){aSex.__cvDogChange=true;aSex.addEventListener('change',()=>decorateAdd(aSex.value===DOG))}
if(typeof window.openOtherAnimal==='function'&&!window.openOtherAnimal.__cvDog){const old=window.openOtherAnimal;window.openOtherAnimal=function(type){const r=old.apply(this,arguments);setTimeout(()=>decorateAdd(type===DOG),0);return r};window.openOtherAnimal.__cvDog=true}
if(typeof window.openGuardianDog==='function'&&!window.openGuardianDog.__cvDog){const old=window.openGuardianDog;window.openGuardianDog=function(){const r=old.apply(this,arguments);setTimeout(()=>decorateAdd(true),0);return r};window.openGuardianDog.__cvDog=true}
if(typeof window.openAdd==='function'&&!window.openAdd.__cvDog){const old=window.openAdd;window.openAdd=function(){const r=old.apply(this,arguments);setTimeout(()=>decorateAdd(el('aSex')?.value===DOG),0);return r};window.openAdd.__cvDog=true}
if(typeof window.openAddWithMedia==='function'&&!window.openAddWithMedia.__cvDog){const old=window.openAddWithMedia;window.openAddWithMedia=function(){const r=old.apply(this,arguments);setTimeout(()=>decorateAdd(el('aSex')?.value===DOG),0);return r};window.openAddWithMedia.__cvDog=true}
if(typeof window.saveNewAnimal==='function'&&!window.saveNewAnimal.__cvDog){const old=window.saveNewAnimal;window.saveNewAnimal=async function(){const dog=el('aSex')?.value===DOG,meta=dog?{canineSex:el('aCanineSex')?.value||'Unknown',workingRole:el('aDogRole')?.value.trim()||'',guardianStatus:el('aDogStatus')?.value||'Working',microchip:el('aDogMicrochip')?.value.trim()||'',alteredStatus:el('aDogAltered')?.value||'Unknown'}:null,before=new Set(herd().map(a=>String(a.id)));const r=await old.apply(this,arguments);if(dog){const added=herd().find(a=>!before.has(String(a.id)));if(added){Object.assign(added,meta);save();window.dispatchEvent(new Event('cv-dog-changed'))}}return r};window.saveNewAnimal.__cvDog=true}
if(typeof window.openRecord==='function'&&!window.openRecord.__cvDog){const old=window.openRecord;window.openRecord=async function(id){const a=herd().find(x=>String(x.id)===String(id));prepareDogForm(isDog(a));const r=await old.apply(this,arguments);if(isDog(a))loadDogFields(a);return r};window.openRecord.__cvDog=true}
if(typeof window.saveRecord==='function'&&!window.saveRecord.__cvDog){const old=window.saveRecord;window.saveRecord=function(){const a=herd().find(x=>String(x.id)===String(typeof currentId!=='undefined'?currentId:''));if(isDog(a))saveDogFields(a);const r=old.apply(this,arguments);if(isDog(a)){window.dispatchEvent(new Event('cv-dog-changed'));setTimeout(()=>renderFamily(a),0)}return r};window.saveRecord.__cvDog=true}
}
install();setTimeout(ensureMenu,300);setInterval(ensureMenu,1500);
})();