(function(){
const DOG='Livestock Guardian Dog',HORSE='Horse';
let grazingPasture='';
function addOption(sel,val){if(!sel||[...sel.options].some(o=>o.value===val))return;const o=document.createElement('option');o.value=val;o.textContent=val;sel.appendChild(o)}
function setupAnimalOptions(){['aSex','rSex'].forEach(id=>{addOption($(id),DOG);addOption($(id),HORSE)});document.querySelectorAll('select.bulk-sex').forEach(sel=>{addOption(sel,DOG);addOption(sel,HORSE)})}
function isDog(a){return a&&a.sex===DOG}
function isHorse(a){return a&&a.sex===HORSE}
function isCattle(a){return a&&!isDog(a)&&!isHorse(a)}
function currentPastureMove(a,pasture){const hist=Array.isArray(a.locationHistory)?a.locationHistory:[];for(let i=hist.length-1;i>=0;i--){const h=hist[i];if(String(h.to||'').toLowerCase()===String(pasture||'').toLowerCase()&&h.date)return h}return null}
function currentPastureStart(a,pasture){const h=currentPastureMove(a,pasture);if(!h?.date)return null;const d=new Date(h.date);return Number.isNaN(d.getTime())?null:d}
function daysSince(d){if(!d||Number.isNaN(d.getTime()))return null;const now=new Date();return Math.max(0,Math.floor((now-d)/86400000))}
function dateInputValue(d){if(!d||Number.isNaN(d.getTime()))return'';const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return`${y}-${m}-${day}`}
function grazingCattle(pasture){return cattle.filter(a=>isCattle(a)&&String(a.location||'').toLowerCase()===String(pasture||'').toLowerCase())}
function grazingStats(animals,pasture){const vals=animals.map(a=>daysSince(currentPastureStart(a,pasture))).filter(v=>v!==null),known=vals.length,total=animals.length,cattleDays=vals.reduce((s,v)=>s+v,0);if(!known)return{total,known:0,min:null,max:null,average:null,cattleDays:0};return{total,known,min:Math.min(...vals),max:Math.max(...vals),average:cattleDays/known,cattleDays}}
function grazingText(animals,pasture){const s=grazingStats(animals.filter(isCattle),pasture);if(!s.known)return'';const dayText=s.min===s.max?`${s.min} day${s.min===1?'':'s'} on grass`:`${s.min}–${s.max} days on grass`;return s.known<s.total?`${dayText} • ${s.total-s.known} date${s.total-s.known===1?'':'s'} missing`:dayText}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function ensureGrazingModal(){if(document.getElementById('grazingDatesModal'))return;const m=document.createElement('div');m.id='grazingDatesModal';m.className='modal hidden';m.innerHTML=`<div class="sheet" style="max-width:720px"><div class="row"><div><h2 style="margin:0" id="grazingDatesTitle">Pasture Details</h2><div class="muted" id="grazingDatesSub"></div></div><button class="softbtn" type="button" id="grazingDatesClose">Close</button></div><div id="grazingSummary" class="notice" style="margin:14px 0"></div><div class="section"><h3 style="margin-top:0">Set the herd entry date</h3><div class="muted">Use this when most or all of the cattle entered this pasture on the same day.</div><div class="row" style="margin-top:10px;align-items:end"><div style="flex:1"><label>Entry Date</label><input id="grazingGroupDate" type="date"></div><button class="greenbtn" type="button" id="grazingApplyAll">Apply to All Cattle Here</button></div></div><div class="section"><div class="row"><div><h3 style="margin:0">Individual Entry Dates</h3><div class="muted">Correct a cow separately if she entered later or earlier.</div></div></div><div id="grazingAnimalRows" style="margin-top:10px"></div></div><button class="greenbtn" type="button" id="grazingSave" style="width:100%">Save Grazing Dates</button></div>`;document.body.appendChild(m);document.getElementById('grazingDatesClose').onclick=()=>m.classList.add('hidden');document.getElementById('grazingApplyAll').onclick=applyGrazingDateToAll;document.getElementById('grazingSave').onclick=saveGrazingDates}
function setEntryDate(a,pasture,dateStr){if(!a||!pasture)return;const hist=Array.isArray(a.locationHistory)?a.locationHistory:(a.locationHistory=[]),move=currentPastureMove(a,pasture);if(!dateStr){if(move)move.date='';return}const d=new Date(`${dateStr}T12:00:00`);if(Number.isNaN(d.getTime()))return;const iso=d.toISOString();if(move)move.date=iso;else hist.push({from:'',to:pasture,date:iso,corrected:true})}
function renderGrazingRows(){const host=document.getElementById('grazingAnimalRows');if(!host)return;const animals=grazingCattle(grazingPasture).sort((a,b)=>String(a.tag||'').localeCompare(String(b.tag||''),undefined,{numeric:true}));host.innerHTML=animals.length?animals.map(a=>{const d=currentPastureStart(a,grazingPasture),days=daysSince(d);return`<div class="pasture-animal-row" style="grid-template-columns:minmax(0,1fr) minmax(145px,190px);margin-bottom:8px"><span><b>Tag ${esc(a.tag||'N-T')}</b><small>${d?`${days} day${days===1?'':'s'} on grass`:'Entry date unknown'}</small></span><input class="grazing-animal-date" data-animal-id="${esc(a.id)}" type="date" value="${dateInputValue(d)}"></div>`}).join(''):'<div class="empty">No cattle are currently assigned to this pasture.</div>';renderGrazingSummary()}
function renderGrazingSummary(){const host=document.getElementById('grazingSummary');if(!host)return;const s=grazingStats(grazingCattle(grazingPasture),grazingPasture);if(!s.total){host.textContent='No cattle are currently assigned to this pasture.';return}if(!s.known){host.innerHTML=`<b>${s.total} cattle</b> • Entry dates have not been set yet.`;return}const range=s.min===s.max?`${s.min} day${s.min===1?'':'s'}`:`${s.min}–${s.max} days`;host.innerHTML=`<b>${s.total} cattle</b> • ${range} on grass • <b>${s.cattleDays.toLocaleString()} cattle-days</b>${s.known<s.total?` • ${s.total-s.known} missing date${s.total-s.known===1?'':'s'}`:''}`}
function openGrazingDates(pasture){ensureGrazingModal();grazingPasture=String(pasture||'').trim();if(!grazingPasture)return;document.getElementById('grazingDatesTitle').textContent=`${grazingPasture} Grazing Dates`;document.getElementById('grazingDatesSub').textContent='Edit when cattle actually entered this pasture. Days on grass update automatically.';const animals=grazingCattle(grazingPasture),dates=animals.map(a=>dateInputValue(currentPastureStart(a,grazingPasture))).filter(Boolean),same=dates.length&&dates.every(x=>x===dates[0]);document.getElementById('grazingGroupDate').value=same?dates[0]:'';renderGrazingRows();document.getElementById('grazingDatesModal').classList.remove('hidden')}
function applyGrazingDateToAll(){const v=document.getElementById('grazingGroupDate')?.value;if(!v)return alert('Choose the date the cattle entered this pasture.');for(const input of document.querySelectorAll('.grazing-animal-date'))input.value=v;renderGrazingSummary()}
function saveGrazingDates(){const animals=grazingCattle(grazingPasture),byId=new Map(animals.map(a=>[String(a.id),a]));for(const input of document.querySelectorAll('.grazing-animal-date')){const a=byId.get(String(input.dataset.animalId));if(a)setEntryDate(a,grazingPasture,input.value)}if(typeof save==='function')save();else localStorage.setItem('cv2-cattle',JSON.stringify(cattle));try{localStorage.setItem('cv2-cloud-dirty','1');if(typeof window.cvCloudChanged==='function')window.cvCloudChanged();else window.dispatchEvent(new Event('cv-local-change'))}catch{}renderGrazingRows();if(typeof window.renderPastureManager==='function')window.renderPastureManager(false);alert('Grazing dates saved. Days on grass and pasture movement history are updated.')}
window.openGrazingDates=openGrazingDates;
function decoratePastures(){document.querySelectorAll('.pasture-card').forEach(card=>{const name=card.querySelector('.pasture-card-head strong')?.textContent?.trim();if(!name)return;const animals=cattle.filter(a=>String(a.location||'').toLowerCase()===name.toLowerCase());const dogs=animals.filter(isDog).length,horses=animals.filter(isHorse).length,cows=animals.filter(isCattle).length;const count=card.querySelector('.pasture-card-head span');const parts=[`${cows} cattle`];if(dogs)parts.push(`${dogs} guardian dog${dogs===1?'':'s'}`);if(horses)parts.push(`${horses} horse${horses===1?'':'s'}`);const countText=parts.join(' • ');if(count&&count.textContent!==countText)count.textContent=countText;let info=card.querySelector('.grass-days');if(!info){info=document.createElement('div');info.className='grass-days muted';info.style.marginTop='6px';card.querySelector('.pasture-card-head>div')?.appendChild(info)}const gt=grazingText(animals,name),txt=gt?`Pasture time: ${gt}`:'Pasture time: entry date not set';if(info&&info.textContent!==txt)info.textContent=txt;const actions=card.querySelector('.pasture-card-actions');if(actions&&!actions.querySelector('.grazing-dates-btn')){const b=document.createElement('button');b.type='button';b.className='softbtn grazing-dates-btn';b.textContent='Grazing Dates / Pasture Details';b.onclick=()=>openGrazingDates(name);const work=[...actions.querySelectorAll('button')].find(x=>/Work Entire Herd/i.test(x.textContent||''));if(work)actions.insertBefore(b,work);else actions.appendChild(b)}})}
window.cvDecoratePastures=decoratePastures;
function openGuardianDog(){openAdd();setupAnimalOptions();$('aSex').value=DOG;$('addTitle').textContent='Add Livestock Guardian Dog'}
window.openGuardianDog=openGuardianDog;
const origCloseAdd=window.closeAdd;if(typeof origCloseAdd==='function')window.closeAdd=function(){const out=origCloseAdd.apply(this,arguments);if($('addTitle'))$('addTitle').textContent='Add Animal';return out};
const origRender=window.render;if(typeof origRender==='function'){const wrappedRender=async function(){const out=await origRender.apply(this,arguments);setupAnimalOptions();return out};Object.assign(wrappedRender,origRender);window.render=wrappedRender}
const origPastureRender=window.renderPastureManager;if(typeof origPastureRender==='function'){const wrappedPastureRender=function(){const out=origPastureRender.apply(this,arguments);decoratePastures();return out};Object.assign(wrappedPastureRender,origPastureRender);window.renderPastureManager=wrappedPastureRender}
const origBulkRender=window.renderBulkSorter;if(typeof origBulkRender==='function'){const wrappedBulkRender=function(){const out=origBulkRender.apply(this,arguments);setupAnimalOptions();return out};Object.assign(wrappedBulkRender,origBulkRender);window.renderBulkSorter=wrappedBulkRender}
setupAnimalOptions();
})();
