(function(){
if(window.__cvGuardianVetInstalled)return;window.__cvGuardianVetInstalled=true;
const DOG='Livestock Guardian Dog';
const el=id=>document.getElementById(id);
const safe=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const herd=()=>typeof cattle!=='undefined'&&Array.isArray(cattle)?cattle:[];
const isDog=a=>a&&a.sex===DOG;
const dogName=a=>String(a?.tag||'').trim()||'Unnamed dog';
const CATEGORIES=['Wellness Exam','Vaccinations','Deworming / Parasite Control','Reproductive Care','Injury / Illness','Surgery / Procedure','Diagnostics / Lab Work','Medication','Dental','Other'];
let vetDogId=null,pendingReceiptFile=null,pendingReceiptUrl='',recognizedText='';
function localId(){return typeof newLocalId==='function'?newLocalId():(Date.now().toString(36)+Math.random().toString(36).slice(2))}
function ensureArrays(a){if(!Array.isArray(a.vetRecords))a.vetRecords=[];if(!Array.isArray(a.health))a.health=[];return a}
function loadTesseract(){return new Promise((resolve,reject)=>{if(window.Tesseract)return resolve(window.Tesseract);const old=document.getElementById('cvTesseractLib');if(old){old.addEventListener('load',()=>resolve(window.Tesseract),{once:true});old.addEventListener('error',()=>reject(new Error('Receipt reader could not load')),{once:true});return}const s=document.createElement('script');s.id='cvTesseractLib';s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.onload=()=>resolve(window.Tesseract);s.onerror=()=>reject(new Error('Receipt reader could not load'));document.head.appendChild(s)})}
function normalizeDate(y,m,d){y=Number(y);m=Number(m);d=Number(d);if(y<100)y+=2000;if(y<2000||y>2100||m<1||m>12||d<1||d>31)return'';return`${String(y).padStart(4,'0')}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`}
function detectDate(text){let m=String(text||'').match(/\b(0?[1-9]|1[0-2])[\/-](0?[1-9]|[12]\d|3[01])[\/-](\d{2,4})\b/);if(m)return normalizeDate(m[3],m[1],m[2]);const months={jan:1,january:1,feb:2,february:2,mar:3,march:3,apr:4,april:4,may:5,jun:6,june:6,jul:7,july:7,aug:8,august:8,sep:9,sept:9,september:9,oct:10,october:10,nov:11,november:11,dec:12,december:12};m=String(text||'').match(/\b(January|February|March|April|May|June|July|August|September|October|November|December|Jan|Feb|Mar|Apr|Jun|Jul|Aug|Sep|Sept|Oct|Nov|Dec)\.?\s+(\d{1,2})(?:st|nd|rd|th)?[,]?\s+(\d{4})\b/i);if(m)return normalizeDate(m[3],months[m[1].toLowerCase()],m[2]);return''}
const categoryRules=[
 ['Wellness Exam',/\b(exam|office visit|wellness|physical|annual|checkup|check-up|consult)\b/i],
 ['Vaccinations',/\b(vaccin|rabies|distemper|parvo|bordetella|dapp|dhpp|lepto|leptospirosis)\b/i],
 ['Deworming / Parasite Control',/\b(deworm|wormer|fecal|parasite|heartworm|flea|tick|bravecto|nexgard|simparica|ivermectin)\b/i],
 ['Reproductive Care',/\b(pregnan|breeding|repro|progesterone|whelp|ultrasound.*preg|inseminat|semen)\b/i],
 ['Injury / Illness',/\b(injur|wound|infection|illness|sick|lameness|limp|fever|vomit|diarrhea|otitis|ear infection)\b/i],
 ['Surgery / Procedure',/\b(surger|procedure|spay|neuter|anesthe|suture|incision|laceration repair)\b/i],
 ['Diagnostics / Lab Work',/\b(cbc|chemistry|bloodwork|blood work|radiograph|x-ray|xray|diagnostic|lab|culture|cytology|biopsy|test)\b/i],
 ['Medication',/\b(medication|prescription|rx|antibiotic|injection|tablet|capsule|ointment|amoxic|cephal|carprofen|meloxicam|predni)\b/i],
 ['Dental',/\b(dental|teeth|tooth|cleaning|extraction)\b/i]
];
function detectCategories(text){const out=categoryRules.filter(([,re])=>re.test(text)).map(([name])=>name);return out.length?out:['Other']}
function detectClinic(lines){const hit=lines.find(l=>/\b(vet|veterinary|animal hospital|animal clinic|pet hospital|clinic)\b/i.test(l));if(hit)return hit.slice(0,120);return(lines.find(l=>/[A-Za-z]{3,}/.test(l)&&!/^invoice|receipt|statement|date\b/i.test(l))||'').slice(0,120)}
function detectAmount(text){const lines=String(text||'').split(/\n+/).map(x=>x.trim()).filter(Boolean);const candidates=lines.filter(l=>/\b(grand total|amount due|balance due|total|paid)\b/i.test(l));for(let i=candidates.length-1;i>=0;i--){const ms=[...candidates[i].matchAll(/\$?\s*(\d{1,5}(?:,\d{3})*(?:\.\d{2}))/g)];if(ms.length)return Number(ms[ms.length-1][1].replace(/,/g,''))}return null}
function detectServices(lines){const ignore=/\b(phone|fax|address|invoice|receipt|statement|subtotal|tax|total|balance|amount due|credit|visa|mastercard|cash|change|thank you)\b/i;const service=lines.filter(l=>l.length>2&&!ignore.test(l)&&categoryRules.some(([,re])=>re.test(l))).slice(0,10);return service.join('; ')}
function parseReceipt(text){const lines=String(text||'').split(/\n+/).map(x=>x.replace(/\s+/g,' ').trim()).filter(Boolean);return{date:detectDate(text),clinic:detectClinic(lines),categories:detectCategories(text),services:detectServices(lines),amount:detectAmount(text)}}
function categoryChecks(selected){return CATEGORIES.map(c=>`<label class="vet-cat-chip"><input type="checkbox" value="${safe(c)}" ${selected.includes(c)?'checked':''}><span>${safe(c)}</span></label>`).join('')}
function injectModal(){if(el('dogVetReceiptModal'))return;const m=document.createElement('div');m.id='dogVetReceiptModal';m.className='modal hidden';m.innerHTML=`<div class="sheet vet-sheet"><div class="row"><div><h2>Vet Receipt → Medical Record</h2><div class="muted" id="dogVetSubtitle">Photograph a printed receipt and review what Cattle Vision reads before saving.</div></div><button class="softbtn" onclick="closeVetReceipt()">Close</button></div><input id="dogVetReceiptInput" class="hidden" type="file" accept="image/*" capture="environment"><div id="dogVetPickArea"><button class="greenbtn" style="width:100%;margin-top:12px" onclick="dogVetReceiptInput.click()">Take / Choose Vet Receipt</button></div><div id="dogVetReadStatus" class="muted" style="margin:10px 0"></div><div id="dogVetPreview"></div><div id="dogVetDraft" class="hidden"><div class="notice vet-review-note"><b>Review before saving.</b> Printed receipt reading is automatic but may misread a date, price, or service.</div><div class="grid2"><div><label>Visit Date</label><input id="dogVetDate" type="date"></div><div><label>Vet Clinic</label><input id="dogVetClinic" placeholder="Clinic / veterinarian"></div></div><label>Automatic Categories</label><div id="dogVetCategories" class="vet-category-grid"></div><label>Services / What Was Done</label><textarea id="dogVetServices" placeholder="Exam, vaccines, tests, medications, procedures..."></textarea><div class="grid2"><div><label>Receipt Total</label><input id="dogVetAmount" inputmode="decimal" placeholder="Optional"></div><div><label>Additional Notes</label><input id="dogVetNotes" placeholder="Optional"></div></div><details class="vet-ocr-details"><summary>Show text read from receipt</summary><textarea id="dogVetRawText"></textarea><button class="softbtn" type="button" style="width:100%" onclick="reparseVetReceiptText()">Re-read Corrected Text</button></details><button class="greenbtn" style="width:100%;margin-top:12px" onclick="confirmVetReceipt()">Confirm & Add to Medical Timeline</button></div></div>`;document.body.appendChild(m);el('dogVetReceiptInput').addEventListener('change',e=>{const f=e.target.files?.[0];if(f)readVetReceipt(f)})}
function injectPanel(){let p=el('dogVetPanel');if(p)return p;const health=[...document.querySelectorAll('#recordModal .section')].find(s=>s.querySelector('h3')?.textContent.trim()==='Health & Treatments');if(!health)return null;p=document.createElement('div');p.id='dogVetPanel';p.className='section dog-vet-panel hidden';health.parentElement.insertBefore(p,health);return p}
function clearPending(){pendingReceiptFile=null;recognizedText='';if(pendingReceiptUrl){URL.revokeObjectURL(pendingReceiptUrl);pendingReceiptUrl=''}const input=el('dogVetReceiptInput');if(input)input.value=''}
function openVetReceipt(dogId){injectModal();const a=herd().find(x=>String(x.id)===String(dogId));if(!a||!isDog(a))return;vetDogId=a.id;clearPending();el('dogVetSubtitle').textContent=`Add a vet receipt to ${dogName(a)}. Cattle Vision will read, categorize, and date the visit for you to review.`;el('dogVetReadStatus').textContent='';el('dogVetPreview').innerHTML='';el('dogVetDraft').classList.add('hidden');el('dogVetReceiptModal').classList.remove('hidden')}
function closeVetReceipt(){el('dogVetReceiptModal')?.classList.add('hidden');clearPending();vetDogId=null}
window.openVetReceipt=openVetReceipt;window.closeVetReceipt=closeVetReceipt;
async function readVetReceipt(file){pendingReceiptFile=file;el('dogVetReadStatus').textContent='Reading printed receipt…';if(pendingReceiptUrl)URL.revokeObjectURL(pendingReceiptUrl);pendingReceiptUrl=URL.createObjectURL(file);el('dogVetPreview').innerHTML=`<img class="vet-receipt-preview" src="${pendingReceiptUrl}" alt="Vet receipt preview">`;try{const T=await loadTesseract();const out=await T.recognize(file,'eng',{logger:m=>{if(m.status==='recognizing text')el('dogVetReadStatus').textContent=`Reading printed receipt… ${Math.round((m.progress||0)*100)}%`}});recognizedText=out?.data?.text||'';const d=parseReceipt(recognizedText);fillDraft(d,recognizedText);el('dogVetReadStatus').textContent='Receipt read. Review the detected visit details below.'}catch(e){console.error(e);recognizedText='';fillDraft({date:'',clinic:'',categories:['Other'],services:'',amount:null},'');el('dogVetReadStatus').textContent='Automatic reading could not finish. You can still enter the visit details manually and save the receipt.'}}
window.readVetReceipt=readVetReceipt;
function fillDraft(d,raw){el('dogVetDate').value=d.date||'';el('dogVetClinic').value=d.clinic||'';el('dogVetCategories').innerHTML=categoryChecks(d.categories||['Other']);el('dogVetServices').value=d.services||'';el('dogVetAmount').value=Number.isFinite(d.amount)?d.amount.toFixed(2):'';el('dogVetNotes').value='';el('dogVetRawText').value=raw||'';el('dogVetDraft').classList.remove('hidden');window.dispatchEvent(new CustomEvent('cv-vet-receipt-read',{detail:{type:'dog',raw:raw||''}}))}
function reparseVetReceiptText(){recognizedText=el('dogVetRawText').value;const d=parseReceipt(recognizedText);const oldNotes=el('dogVetNotes').value;fillDraft(d,recognizedText);el('dogVetNotes').value=oldNotes}
window.reparseVetReceiptText=reparseVetReceiptText;
function chosenCategories(){const vals=[...document.querySelectorAll('#dogVetCategories input:checked')].map(x=>x.value);return vals.length?vals:['Other']}
async function compressReceipt(file){if(typeof compressPhoto==='function')return compressPhoto(file);return new Promise((res,rej)=>{const u=URL.createObjectURL(file),im=new Image;im.onload=()=>{const s=Math.min(1,1800/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(im.width*s));c.height=Math.max(1,Math.round(im.height*s));c.getContext('2d').drawImage(im,0,0,c.width,c.height);URL.revokeObjectURL(u);res(c.toDataURL('image/jpeg',.84))};im.onerror=e=>{URL.revokeObjectURL(u);rej(e)};im.src=u})}
async function confirmVetReceipt(){const a=herd().find(x=>String(x.id)===String(vetDogId));if(!a||!isDog(a))return;if(!pendingReceiptFile)return alert('Take or choose the vet receipt first.');const date=el('dogVetDate').value;if(!date)return alert('Confirm the visit date before saving.');const categories=chosenCategories(),services=el('dogVetServices').value.trim(),clinic=el('dogVetClinic').value.trim(),amountRaw=el('dogVetAmount').value.trim(),amount=amountRaw===''?null:Number(amountRaw),notes=el('dogVetNotes').value.trim(),recordId=localId(),mediaId=localId();if(amountRaw!==''&&!Number.isFinite(amount))return alert('Check the receipt total.');el('dogVetReadStatus').textContent='Saving receipt and medical record…';try{const data=await compressReceipt(pendingReceiptFile);if(typeof putMedia!=='function')throw new Error('Photo storage is not ready');await putMedia({id:mediaId,animalId:String(a.id),type:'vet_receipt',data,created:new Date().toISOString(),source:'vet-receipt'});ensureArrays(a);const rec={id:recordId,date,clinic,categories,services,amount,notes,receiptMediaId:mediaId,created:new Date().toISOString()};a.vetRecords.push(rec);const treatment=`Vet — ${categories.join(' + ')}${services?`: ${services}`:''}`;const detail=[clinic?`Clinic: ${clinic}`:'',amount!==null?`Receipt: $${amount.toFixed(2)}`:'',notes].filter(Boolean).join(' • ');a.health.push({date,treatment,withdraw:'',notes:detail,vetRecordId:recordId});if(typeof save==='function')save();else localStorage.setItem('cv2-cattle',JSON.stringify(herd()));window.dispatchEvent(new Event('cv-vet-changed'));window.dispatchEvent(new Event('cv-dog-changed'));closeVetReceipt();await renderVetPanel(a);if(typeof renderHist==='function')renderHist(a);alert(`Vet visit saved to ${dogName(a)}'s medical timeline.`)}catch(e){console.error(e);el('dogVetReadStatus').textContent='The receipt could not be saved yet.';alert('The vet record was not saved because the receipt photo could not be stored. Try again.') }}
window.confirmVetReceipt=confirmVetReceipt;
async function receiptMap(a){let ms=[];try{if(typeof getMedia==='function')ms=await getMedia(a.id)}catch(e){console.warn(e)}return new Map(ms.filter(m=>m.type==='vet_receipt').map(m=>[String(m.id),m]))}
async function renderVetPanel(a){const p=injectPanel();if(!p)return;if(!isDog(a)){p.classList.add('hidden');return}ensureArrays(a);const media=await receiptMap(a),rows=a.vetRecords.slice().sort((x,y)=>String(y.date||'').localeCompare(String(x.date||'')));p.innerHTML=`<div class="dog-vet-head"><div><h3>🩺 Veterinary Records</h3><div class="muted">Receipts become dated, categorized medical-history entries after you confirm what was read.</div></div><button class="greenbtn" type="button" onclick="openVetReceipt('${String(a.id).replace(/'/g,"\\'")}')">Add Vet Receipt</button></div><div class="dog-vet-list">${rows.length?rows.map(r=>{const m=media.get(String(r.receiptMediaId)),cats=Array.isArray(r.categories)?r.categories:[r.category||'Other'];return`<div class="vet-record-card">${m?.data?`<button class="vet-thumb-btn" onclick="viewVetReceipt('${String(a.id).replace(/'/g,"\\'")}','${String(r.receiptMediaId).replace(/'/g,"\\'")}')"><img src="${m.data}" alt="Vet receipt"></button>`:'<div class="vet-thumb-placeholder">Receipt</div>'}<div class="vet-record-copy"><b>${safe(r.date||'Date not set')} • ${safe(cats.join(' + '))}</b>${r.clinic?`<span>${safe(r.clinic)}</span>`:''}${r.services?`<small>${safe(r.services)}</small>`:''}<small>${r.amount!==null&&r.amount!==undefined?`$${Number(r.amount).toFixed(2)}`:''}${r.notes?`${r.amount!==null&&r.amount!==undefined?' • ':''}${safe(r.notes)}`:''}</small></div></div>`}).join(''):'<div class="muted">No veterinary receipts saved yet.</div>'}</div>`;p.classList.remove('hidden')}
window.cvRenderDogVetPanel=renderVetPanel;
async function viewVetReceipt(animalId,mediaId){let ms=[];try{ms=typeof getMedia==='function'?await getMedia(animalId):[]}catch{}const m=ms.find(x=>String(x.id)===String(mediaId));if(!m?.data)return alert('That receipt image is not available on this device yet. Run Cloud Restore / Merge to retrieve backed-up media.');let modal=el('vetReceiptViewer');if(!modal){modal=document.createElement('div');modal.id='vetReceiptViewer';modal.className='modal hidden';modal.innerHTML=`<div class="sheet" style="max-width:720px"><div class="row"><h2>Vet Receipt</h2><button class="softbtn" onclick="vetReceiptViewer.classList.add('hidden')">Close</button></div><img id="vetReceiptViewerImg" class="vet-full-receipt" alt="Vet receipt"></div>`;document.body.appendChild(modal)}el('vetReceiptViewerImg').src=m.data;modal.classList.remove('hidden')}
window.viewVetReceipt=viewVetReceipt;
function wrap(){injectModal();injectPanel();for(const a of herd())if(isDog(a))ensureArrays(a);if(typeof window.openRecord==='function'&&!window.openRecord.__cvVet){const old=window.openRecord;window.openRecord=async function(id){const out=await old.apply(this,arguments),a=herd().find(x=>String(x.id)===String(id));if(a&&isDog(a))await renderVetPanel(a);else el('dogVetPanel')?.classList.add('hidden');return out};window.openRecord.__cvVet=true}}
// The animal record handler is ready before this script loads. Do not poll and
// repeatedly wrap it; that creates an ever-growing call chain on iPhone.
wrap();
})();
