(function(){
if(window.__cvMedicalCostsInstalled)return;window.__cvMedicalCostsInstalled=true;
const el=id=>document.getElementById(id);
const safe=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const herd=()=>typeof cattle!=='undefined'&&Array.isArray(cattle)?cattle:[];
const money=n=>Number.isFinite(Number(n))?`$${Number(n).toFixed(2)}`:'$0.00';
const localId=()=>typeof newLocalId==='function'?newLocalId():Date.now().toString(36)+Math.random().toString(36).slice(2);
function meds(){try{const x=JSON.parse(localStorage.getItem('cv2-meds')||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function saveMeds(arr){localStorage.setItem('cv2-meds',JSON.stringify(arr));window.dispatchEvent(new Event('cv-local-change'));window.dispatchEvent(new Event('cv-med-cost-changed'));window.cvRefreshMedicationCabinet?.()}
function ensureEvents(a){if(!Array.isArray(a.costEvents))a.costEvents=[];return a.costEvents}
function addEvent(a,e){const arr=ensureEvents(a),sourceType=String(e.sourceType||''),sourceId=String(e.sourceId||'');if(sourceType&&sourceId&&arr.some(x=>String(x.sourceType||'')===sourceType&&String(x.sourceId||'')===sourceId))return;arr.push({id:e.id||localId(),date:e.date||new Date().toISOString().slice(0,10),category:e.category||'Veterinary',sourceType,sourceId,description:e.description||'',amount:Number(e.amount)||0,medicationCost:Number(e.medicationCost)||0})}
function saveHerd(){if(typeof save==='function')save();else localStorage.setItem('cv2-cattle',JSON.stringify(herd()));window.dispatchEvent(new Event('cv-medical-cost-changed'))}
function totals(a){const ev=ensureEvents(a);return{total:ev.reduce((s,x)=>s+(Number(x.amount)||0),0),med:ev.reduce((s,x)=>s+(Number(x.medicationCost)||0),0),vet:ev.filter(x=>x.category==='Veterinary').reduce((s,x)=>s+(Number(x.amount)||0),0),other:ev.filter(x=>x.category!=='Veterinary'&&x.category!=='Medication').reduce((s,x)=>s+(Number(x.amount)||0),0)}}
function ensureSummaryPanel(){let p=el('medicalCostPanel');if(p)return p;const health=[...document.querySelectorAll('#recordModal .section')].find(s=>s.querySelector('h3')?.textContent.trim()==='Health & Treatments');if(!health)return null;p=document.createElement('div');p.id='medicalCostPanel';p.className='section medical-cost-panel';health.parentElement.insertBefore(p,health);return p}
function renderSummary(a){const p=ensureSummaryPanel();if(!p||!a){p?.classList.add('hidden');return}const t=totals(a),ev=ensureEvents(a).slice().sort((x,y)=>String(y.date||'').localeCompare(String(x.date||'')));p.innerHTML=`<div class="cost-head"><div><h3>💵 Medical Cost Summary</h3><div class="muted">Costs tied to this individual from confirmed receipts, litter allocations, medication use, and equine care.</div></div><div class="cost-total"><span>Total Tracked</span><b>${money(t.total)}</b></div></div><div class="cost-stats"><div><span>Veterinary</span><b>${money(t.vet)}</b></div><div><span>Medication Portion</span><b>${money(t.med)}</b></div><div><span>Other Care</span><b>${money(t.other)}</b></div></div>${ev.length?`<details class="cost-history"><summary>View cost history (${ev.length})</summary>${ev.map(x=>`<div class="cost-row"><span><b>${safe(x.date||'')}</b> • ${safe(x.category||'Care')}</span><span>${money(x.amount)}</span>${x.description?`<small>${safe(x.description)}</small>`:''}</div>`).join('')}</details>`:'<div class="muted" style="margin-top:8px">No veterinary or medication costs have been assigned to this animal yet.</div>'}`;p.classList.remove('hidden')}
window.cvRenderMedicalCosts=renderSummary;
function ensureMedicationTreatmentPanel(){let p=el('medTreatmentPanel');if(p)return p;const cost=ensureSummaryPanel(),host=cost?.parentElement;if(!host)return null;p=document.createElement('div');p.id='medTreatmentPanel';p.className='section med-treatment-panel';host.insertBefore(p,cost.nextSibling);p.innerHTML=`<h3>💉 Apply Medication</h3><div class="muted">Record the amount actually administered. Cattle Vision uses your saved purchase cost to calculate the dollar amount; it does not invent a drug dose.</div><div class="grid3"><div><label>Date</label><input id="costMedDate" type="date"></div><div><label>Medication</label><select id="costMedSelect"></select></div><div><label>Amount Given</label><input id="costMedAmount" inputmode="decimal" placeholder="Actual amount"></div></div><div id="costMedHint" class="cost-med-hint"></div><label>Notes</label><input id="costMedNotes" placeholder="Optional treatment notes"><button class="greenbtn" type="button" onclick="saveMedicationTreatment()">Add Medication Treatment</button>`;el('costMedSelect').addEventListener('change',refreshMedHint);el('costMedAmount').addEventListener('input',refreshMedHint);return p}
function refreshMedicationOptions(){const s=el('costMedSelect');if(!s)return;const cur=s.value,ms=meds().slice().sort((a,b)=>String(a.name).localeCompare(String(b.name)));s.innerHTML='<option value="">Choose medication...</option>'+ms.map(m=>`<option value="${safe(m.id)}">${safe(m.name)}</option>`).join('');if(ms.some(m=>String(m.id)===String(cur)))s.value=cur;refreshMedHint()}
function refreshMedHint(){const m=meds().find(x=>String(x.id)===String(el('costMedSelect')?.value||'')),box=el('costMedHint');if(!box)return;if(!m){box.innerHTML='';return}const amount=Number(el('costMedAmount')?.value),cpu=Number(m.costPerUnit),cost=Number.isFinite(amount)&&amount>0&&Number.isFinite(cpu)?amount*cpu:null;box.innerHTML=`<span>Saved label basis: <b>${Number.isFinite(Number(m.dose))?`${safe(m.dose)} ${safe(m.unit)} per ${safe(m.basis)} lb`:'dose not saved'}</b></span><span>Purchase cost: <b>${Number.isFinite(cpu)?`${money(cpu)} per ${safe(m.costUnit||m.unit||'unit')}`:'not entered yet'}</b></span>${cost!==null?`<span>Cost for this treatment: <b>${money(cost)}</b></span>`:''}`}
function saveMedicationTreatment(){const a=herd().find(x=>String(x.id)===String(typeof currentId!=='undefined'?currentId:''));if(!a)return;const m=meds().find(x=>String(x.id)===String(el('costMedSelect')?.value||''));if(!m)return alert('Choose the medication used.');const date=el('costMedDate').value;if(!date)return alert('Enter the treatment date.');const amount=Number(el('costMedAmount').value);if(!Number.isFinite(amount)||amount<=0)return alert('Enter the amount actually administered.');const cpu=Number(m.costPerUnit),cost=Number.isFinite(cpu)?amount*cpu:0,unit=m.costUnit||m.unit||'unit',notes=el('costMedNotes').value.trim(),eventId=localId();if(!Array.isArray(a.health))a.health=[];a.health.push({date,treatment:`Medication — ${m.name}`,withdraw:'',notes:[`${amount} ${unit} administered`,cost>0?`Medication cost: ${money(cost)}`:'Medication purchase cost not entered',notes].filter(Boolean).join(' • '),medicationId:m.id,medicationAmount:amount,medicationUnit:unit,medicationCost:cost,costEventId:eventId});if(cost>0)addEvent(a,{id:eventId,date,category:'Medication',sourceType:'medication_treatment',sourceId:eventId,description:`${m.name} • ${amount} ${unit}`,amount:cost,medicationCost:cost});saveHerd();if(typeof renderHist==='function')renderHist(a);renderSummary(a);el('costMedAmount').value='';el('costMedNotes').value='';refreshMedHint()}
window.saveMedicationTreatment=saveMedicationTreatment;
function ensurePurchaseFields(){if(el('medPurchasePrice'))return;const photo=el('medPhoto')?.closest('.wide')||el('medPhoto')?.parentElement;if(!photo)return;photo.insertAdjacentHTML('beforebegin',`<div><label>Purchase Price</label><input id="medPurchasePrice" inputmode="decimal" placeholder="Bottle / package total"></div><div><label>Container Size</label><input id="medContainerSize" inputmode="decimal" placeholder="Example: 100"></div><div><label>Cost Unit</label><select id="medCostUnit"><option>mL</option><option>cc</option><option>dose</option><option>tablet</option><option>oz</option></select></div><div id="medCostPreview" class="med-cost-preview"></div>`);['medPurchasePrice','medContainerSize','medCostUnit'].forEach(id=>el(id)?.addEventListener('input',updatePurchasePreview));updatePurchasePreview()}
function updatePurchasePreview(){const p=Number(el('medPurchasePrice')?.value),s=Number(el('medContainerSize')?.value),box=el('medCostPreview');if(!box)return;box.innerHTML=Number.isFinite(p)&&p>=0&&Number.isFinite(s)&&s>0?`<span>Cost per ${safe(el('medCostUnit')?.value||'unit')}</span><b>${money(p/s)}</b>`:'<span>Enter price + container size to calculate unit cost.</span>'}
function updateMedicationCost(id){const arr=meds(),m=arr.find(x=>String(x.id)===String(id));if(!m)return;const price=Number(prompt(`Purchase price for ${m.name}:`,Number.isFinite(Number(m.purchasePrice))?Number(m.purchasePrice).toFixed(2):''));if(!Number.isFinite(price)||price<0)return;const size=Number(prompt(`Container size for ${m.name} (${m.costUnit||m.unit||'mL'}):`,Number.isFinite(Number(m.containerSize))?String(m.containerSize):''));if(!Number.isFinite(size)||size<=0)return;m.purchasePrice=price;m.containerSize=size;m.costUnit=m.costUnit||m.unit||'mL';m.costPerUnit=price/size;m.costUpdatedAt=new Date().toISOString();saveMeds(arr);setTimeout(enhanceMedCards,100)}
window.updateMedicationCost=updateMedicationCost;
function enhanceMedCards(){ensurePurchaseFields();const cards=[...document.querySelectorAll('#medList .med-card')],arr=meds().slice().sort((a,b)=>String(a.name).localeCompare(String(b.name)));cards.forEach((card,i)=>{const m=arr[i];if(!m)return;card.querySelector('.med-cost-extra')?.remove();const d=document.createElement('div');d.className='med-cost-extra';d.innerHTML=`${Number.isFinite(Number(m.costPerUnit))?`<b>${money(m.costPerUnit)} / ${safe(m.costUnit||m.unit||'unit')}</b><span>${money(m.purchasePrice)} ÷ ${safe(m.containerSize)} ${safe(m.costUnit||m.unit||'unit')}</span>`:'<span>Purchase cost not entered.</span>'}<button class="softbtn" type="button" onclick="updateMedicationCost('${String(m.id).replace(/'/g,"\\'")}')">${Number.isFinite(Number(m.costPerUnit))?'Update Purchase Cost':'Add Purchase Cost'}</button>`;card.appendChild(d)})}
function installMedicationSaveWrapper(){if(typeof window.saveMedication!=='function'||window.saveMedication.__cvCost)return;const old=window.saveMedication;window.saveMedication=async function(){ensurePurchaseFields();const rawP=el('medPurchasePrice')?.value.trim()||'',rawS=el('medContainerSize')?.value.trim()||'';if((rawP&&!rawS)||(!rawP&&rawS))return alert('Enter both purchase price and container size, or leave both blank.');const p=rawP?Number(rawP):null,s=rawS?Number(rawS):null;if((p!==null&&(!Number.isFinite(p)||p<0))||(s!==null&&(!Number.isFinite(s)||s<=0)))return alert('Check the medication purchase price and container size.');const before=new Set(meds().map(m=>String(m.id))),unit=el('medCostUnit')?.value||'mL',out=await old.apply(this,arguments),arr=meds(),added=arr.find(m=>!before.has(String(m.id)));if(added&&p!==null&&s!==null){added.purchasePrice=p;added.containerSize=s;added.costUnit=unit;added.costPerUnit=p/s;added.costUpdatedAt=new Date().toISOString();saveMeds(arr)}if(el('medPurchasePrice'))el('medPurchasePrice').value='';if(el('medContainerSize'))el('medContainerSize').value='';updatePurchasePreview();setTimeout(enhanceMedCards,100);return out};window.saveMedication.__cvCost=true}
function numberOnLine(text,re){const line=String(text||'').split(/\n+/).find(l=>re.test(l));if(!line)return null;const ms=[...line.matchAll(/\$?\s*(\d{1,6}(?:,\d{3})*(?:\.\d{2}))/g)];return ms.length?Number(ms[ms.length-1][1].replace(/,/g,'')):null}
function receiptSuggestions(raw,total){const subtotal=numberOnLine(raw,/\bsubtotal\b/i);const med=numberOnLine(raw,/\b(medication|pharmacy|drug)\s*(subtotal|total)\b/i);return{subtotal:Number.isFinite(subtotal)?subtotal:(Number.isFinite(Number(total))?Number(total):null),medication:Number.isFinite(med)?med:null}}
function injectVetCosts(){const draft=el('dogVetDraft');if(!draft||el('dogVetSubtotal'))return;const amount=el('dogVetAmount')?.parentElement;if(!amount)return;amount.parentElement.insertAdjacentHTML('afterend',`<div class="vet-cost-box"><h4>Cost Breakdown</h4><div class="grid2"><div><label>Veterinary Care Subtotal</label><input id="dogVetSubtotal" inputmode="decimal" placeholder="Care subtotal"></div><div><label>Medication Portion</label><input id="dogVetMedicationSubtotal" inputmode="decimal" placeholder="Medication subtotal"></div></div><div class="muted">Review these amounts before saving. Medication is part of the veterinary total, not added on top.</div></div>`)}
function fillVetCostSuggestions(){injectVetCosts();const sub=el('dogVetSubtotal'),med=el('dogVetMedicationSubtotal'),raw=el('dogVetRawText')?.value||'',total=Number(el('dogVetAmount')?.value),s=receiptSuggestions(raw,total);if(sub&&!sub.value&&s.subtotal!==null)sub.value=s.subtotal.toFixed(2);if(med&&!med.value&&s.medication!==null)med.value=s.medication.toFixed(2)}
function injectLitterCosts(){const draft=el('litterVetDraft');if(!draft||el('litterVetSubtotal'))return;const amt=el('litterVetAmount')?.parentElement?.parentElement;if(!amt)return;amt.insertAdjacentHTML('afterend',`<div class="vet-cost-box"><h4>Litter Cost Allocation</h4><div class="grid2"><div><label>Veterinary Care Subtotal</label><input id="litterVetSubtotal" inputmode="decimal" placeholder="Care subtotal"></div><div><label>Medication Portion</label><input id="litterVetMedicationSubtotal" inputmode="decimal" placeholder="Medication subtotal"></div></div><div id="litterCostPreview" class="litter-cost-preview"></div></div>`);['litterVetSubtotal','litterVetMedicationSubtotal'].forEach(id=>el(id)?.addEventListener('input',updateLitterPreview));el('litterVetPuppies')?.addEventListener('change',updateLitterPreview);el('litterVetIncludeParent')?.addEventListener('change',updateLitterPreview)}
function fillLitterCostSuggestions(){injectLitterCosts();const sub=el('litterVetSubtotal'),med=el('litterVetMedicationSubtotal'),raw=el('litterVetRaw')?.value||'',total=Number(el('litterVetAmount')?.value),s=receiptSuggestions(raw,total);if(sub&&!sub.value&&s.subtotal!==null)sub.value=s.subtotal.toFixed(2);if(med&&!med.value&&s.medication!==null)med.value=s.medication.toFixed(2);updateLitterPreview()}
function updateLitterPreview(){const box=el('litterCostPreview');if(!box)return;const count=[...document.querySelectorAll('#litterVetPuppies input:checked')].length+(el('litterVetIncludeParent')?.checked?1:0),sub=Number(el('litterVetSubtotal')?.value),med=Number(el('litterVetMedicationSubtotal')?.value);if(!count){box.innerHTML='<span>Select the animals this receipt applies to.</span>';return}box.innerHTML=`<span>Animals sharing this care: <b>${count}</b></span>${Number.isFinite(sub)?`<span>Veterinary care per animal: <b>${money(sub/count)}</b></span>`:''}${Number.isFinite(med)?`<span>Medication portion per animal: <b>${money(med/count)}</b></span>`:''}`}
function installReceiptWrappers(){if(typeof window.confirmVetReceipt==='function'&&!window.confirmVetReceipt.__cvCost){const old=window.confirmVetReceipt;window.confirmVetReceipt=async function(){const dogId=typeof currentId!=='undefined'?currentId:null,a=herd().find(x=>String(x.id)===String(dogId)),before=a&&Array.isArray(a.vetRecords)?a.vetRecords.length:0,subRaw=el('dogVetSubtotal')?.value.trim()||'',medRaw=el('dogVetMedicationSubtotal')?.value.trim()||'';const sub=subRaw===''?null:Number(subRaw),med=medRaw===''?0:Number(medRaw);if(subRaw!==''&&!Number.isFinite(sub))return alert('Check the veterinary care subtotal.');if(medRaw!==''&&!Number.isFinite(med))return alert('Check the medication subtotal.');const out=await old.apply(this,arguments);if(a&&Array.isArray(a.vetRecords)&&a.vetRecords.length>before){const r=a.vetRecords[a.vetRecords.length-1],amount=sub!==null?sub:(Number(r.amount)||0);r.careSubtotal=amount;r.medicationSubtotal=med;if(amount>0)addEvent(a,{date:r.date,category:'Veterinary',sourceType:'vet_receipt',sourceId:r.id,description:[r.clinic,r.services].filter(Boolean).join(' • '),amount,medicationCost:med});saveHerd();renderSummary(a)}return out};window.confirmVetReceipt.__cvCost=true}
if(typeof window.confirmLitterVetReceipt==='function'&&!window.confirmLitterVetReceipt.__cvCost){const old=window.confirmLitterVetReceipt;window.confirmLitterVetReceipt=async function(){const parentId=typeof currentId!=='undefined'?currentId:null,p=herd().find(x=>String(x.id)===String(parentId)),before=p&&Array.isArray(p.litterVetRecords)?p.litterVetRecords.length:0,selected=[...document.querySelectorAll('#litterVetPuppies input:checked')].map(x=>x.value),include=!!el('litterVetIncludeParent')?.checked,subRaw=el('litterVetSubtotal')?.value.trim()||'',medRaw=el('litterVetMedicationSubtotal')?.value.trim()||'';const sub=subRaw===''?null:Number(subRaw),med=medRaw===''?0:Number(medRaw);if(subRaw!==''&&!Number.isFinite(sub))return alert('Check the veterinary care subtotal.');if(medRaw!==''&&!Number.isFinite(med))return alert('Check the medication subtotal.');const out=await old.apply(this,arguments);if(p&&Array.isArray(p.litterVetRecords)&&p.litterVetRecords.length>before){const r=p.litterVetRecords[p.litterVetRecords.length-1],total=sub!==null?sub:(Number(r.amount)||0),count=selected.length+(include?1:0),per=count?total/count:0,medPer=count?med/count:0;r.careSubtotal=total;r.medicationSubtotal=med;r.costPerAnimal=per;r.medicationCostPerAnimal=medPer;for(const aid of selected){const a=herd().find(x=>String(x.id)===String(aid));if(a&&per>0)addEvent(a,{date:r.date,category:'Veterinary',sourceType:'litter_vet',sourceId:r.id,description:`Litter veterinary care${r.services?` • ${r.services}`:''}`,amount:per,medicationCost:medPer})}if(include&&per>0)addEvent(p,{date:r.date,category:'Veterinary',sourceType:'litter_vet',sourceId:r.id,description:`Litter veterinary care${r.services?` • ${r.services}`:''}`,amount:per,medicationCost:medPer});saveHerd();renderSummary(p)}return out};window.confirmLitterVetReceipt.__cvCost=true}
if(typeof window.addEquineCare==='function'&&!window.addEquineCare.__cvCost){const old=window.addEquineCare;window.addEquineCare=function(){const a=herd().find(x=>String(x.id)===String(typeof currentId!=='undefined'?currentId:'')),date=el('eCareDate')?.value,type=el('eCareType')?.value,provider=el('eCareProvider')?.value.trim()||'',raw=el('eCareCost')?.value.trim()||'',cost=raw===''?0:Number(raw),before=a&&Array.isArray(a.health)?a.health.length:0,out=old.apply(this,arguments);if(a&&cost>0&&Array.isArray(a.health)&&a.health.length>before){const h=a.health[a.health.length-1],sid=localId();h.costEventId=sid;addEvent(a,{id:sid,date,category:type?.startsWith('Veterinary')?'Veterinary':'Other Care',sourceType:'equine_care',sourceId:sid,description:[type,provider].filter(Boolean).join(' • '),amount:cost,medicationCost:0});saveHerd();renderSummary(a)}return out};window.addEquineCare.__cvCost=true}}
function installRecordWrapper(){if(typeof window.openRecord!=='function'||window.openRecord.__cvMedicalCost)return;const old=window.openRecord;window.openRecord=async function(id){const out=await old.apply(this,arguments),a=herd().find(x=>String(x.id)===String(id));ensureMedicationTreatmentPanel();refreshMedicationOptions();if(a)renderSummary(a);return out};window.openRecord.__cvMedicalCost=true}
function pulse(){ensurePurchaseFields();installMedicationSaveWrapper();enhanceMedCards();ensureSummaryPanel();ensureMedicationTreatmentPanel();installReceiptWrappers();installRecordWrapper();if(el('dogVetDraft')&&!el('dogVetDraft').classList.contains('hidden'))fillVetCostSuggestions();if(el('litterVetDraft')&&!el('litterVetDraft').classList.contains('hidden'))fillLitterCostSuggestions()}
window.addEventListener('cv-med-cost-changed',()=>{enhanceMedCards();refreshMedicationOptions()});window.addEventListener('cv-medical-cost-changed',()=>{const a=herd().find(x=>String(x.id)===String(typeof currentId!=='undefined'?currentId:''));if(a)renderSummary(a)});
pulse();setInterval(pulse,1100);
})();