(function(){
if(window.__cvMedicationCostsInstalled)return;window.__cvMedicationCostsInstalled=true;
const el=id=>document.getElementById(id);
const safe=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const fmt=v=>num(v)===null?'—':`$${num(v).toFixed(2)}`;
function readMeds(){try{const x=JSON.parse(localStorage.getItem('cv2-meds')||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function writeMeds(m){localStorage.setItem('cv2-meds',JSON.stringify(m));window.dispatchEvent(new Event('cv-med-cost-changed'));window.dispatchEvent(new Event('cv-local-change'));window.cvRefreshMedicationCabinet?.()}
function id(){return typeof newLocalId==='function'?newLocalId():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function latestPurchase(m){const p=Array.isArray(m?.purchases)?m.purchases:[];if(!p.length)return null;return p.find(x=>String(x.id)===String(m.activePurchaseId))||p.slice().sort((a,b)=>String(b.date||b.created||'').localeCompare(String(a.date||a.created||'')))[0]||null}
window.cvLatestMedicationPurchase=latestPurchase;
function costPerUnit(m){const p=latestPurchase(m);return num(p?.costPerUnit)??num(m?.costPerUnit)}
window.cvMedicationCostPerUnit=costPerUnit;
function purchaseUnit(m){const p=latestPurchase(m);return p?.unit||m?.costUnit||m?.unit||''}
window.cvMedicationCostUnit=purchaseUnit;
function injectFields(){const grid=document.querySelector('#farmDrawer .med-form-grid');if(!grid||el('medPurchasePrice'))return;const photo=el('medPhoto')?.parentElement;const wrap=document.createElement('div');wrap.className='med-cost-entry wide';wrap.innerHTML=`<div class="med-cost-head"><b>Purchase Cost</b><span class="muted">Optional. This lets Cattle Vision calculate treatment cost per animal.</span></div><div class="med-cost-grid"><div><label>Purchase Price</label><input id="medPurchasePrice" inputmode="decimal" placeholder="Example: 425.00"></div><div><label>Container Size</label><input id="medContainerSize" inputmode="decimal" placeholder="Example: 100"></div><div><label>Cost Unit</label><select id="medCostUnit"><option>mL</option><option>cc</option><option>oz</option><option>tablet(s)</option><option>dose(s)</option></select></div><div><label>Purchase Date</label><input id="medPurchaseDate" type="date"></div><div class="wide"><label>Vendor / Clinic</label><input id="medVendor" placeholder="Optional"></div></div><div id="medCostPreview" class="med-cost-preview muted"></div>`;(photo||grid.lastElementChild)?.insertAdjacentElement('beforebegin',wrap);['medPurchasePrice','medContainerSize'].forEach(k=>el(k)?.addEventListener('input',updatePreview));el('medCostUnit')?.addEventListener('change',updatePreview);const unit=el('medUnit');if(unit&&!unit.__cvCostUnit){unit.__cvCostUnit=true;unit.addEventListener('change',()=>{if(el('medCostUnit'))el('medCostUnit').value=[...el('medCostUnit').options].some(o=>o.value===unit.value)?unit.value:'mL';updatePreview()})}if(!el('medPurchaseDate').value)el('medPurchaseDate').value=new Date().toISOString().slice(0,10);updatePreview()}
function updatePreview(){const price=num(el('medPurchasePrice')?.value),size=num(el('medContainerSize')?.value),unit=el('medCostUnit')?.value||'';const host=el('medCostPreview');if(!host)return;host.textContent=price!==null&&size&&size>0?`${fmt(price/size)} per ${unit}`:'Enter purchase price and container size to calculate cost per unit.'}
function clearFields(){['medPurchasePrice','medContainerSize','medVendor'].forEach(k=>{if(el(k))el(k).value=''});if(el('medPurchaseDate'))el('medPurchaseDate').value=new Date().toISOString().slice(0,10);updatePreview()}
function capturePurchase(){const price=num(el('medPurchasePrice')?.value),size=num(el('medContainerSize')?.value),unit=el('medCostUnit')?.value||el('medUnit')?.value||'',date=el('medPurchaseDate')?.value||new Date().toISOString().slice(0,10),vendor=el('medVendor')?.value.trim()||'';if(price===null&&size===null)return null;if(price===null||size===null||size<=0)return{invalid:true};return{id:id(),date,vendor,price,size,unit,costPerUnit:Number((price/size).toFixed(6)),created:new Date().toISOString()}}
function wrapSave(){if(typeof window.saveMedication!=='function'||window.saveMedication.__cvCost)return;const old=window.saveMedication;window.saveMedication=async function(){injectFields();const purchase=capturePurchase();if(purchase?.invalid)return alert('Enter both the purchase price and container size, or leave both blank.');const before=new Set(readMeds().map(m=>String(m.id)));const out=await old.apply(this,arguments);if(purchase){const meds=readMeds(),m=meds.find(x=>!before.has(String(x.id)));if(m){m.purchases=Array.isArray(m.purchases)?m.purchases:[];m.purchases.push(purchase);m.activePurchaseId=purchase.id;m.costPerUnit=purchase.costPerUnit;m.costUnit=purchase.unit;writeMeds(meds)}}clearFields();return out};window.saveMedication.__cvCost=true}
function injectRestockModal(){if(el('medRestockModal'))return;const m=document.createElement('div');m.id='medRestockModal';m.className='modal hidden';m.innerHTML=`<div class="sheet" style="max-width:620px"><div class="row"><div><h2>Restock Medication</h2><div id="medRestockName" class="muted"></div></div><button class="softbtn" onclick="closeMedRestock()">Close</button></div><div class="grid2"><div><label>Purchase Price</label><input id="medRestockPrice" inputmode="decimal"></div><div><label>Container Size</label><input id="medRestockSize" inputmode="decimal"></div></div><div class="grid2"><div><label>Cost Unit</label><select id="medRestockUnit"><option>mL</option><option>cc</option><option>oz</option><option>tablet(s)</option><option>dose(s)</option></select></div><div><label>Purchase Date</label><input id="medRestockDate" type="date"></div></div><label>Vendor / Clinic</label><input id="medRestockVendor"><label>New Bottle / Label Photo <span class="muted">(optional)</span></label><input id="medRestockPhoto" type="file" accept="image/*" capture="environment"><div id="medRestockPreview" class="med-cost-preview muted"></div><button class="greenbtn" style="width:100%;margin-top:12px" onclick="saveMedRestock()">Save Purchase</button></div>`;document.body.appendChild(m);['medRestockPrice','medRestockSize'].forEach(k=>el(k).addEventListener('input',restockPreview));el('medRestockUnit').addEventListener('change',restockPreview)}
let restockId=null;
function restockPreview(){const price=num(el('medRestockPrice')?.value),size=num(el('medRestockSize')?.value),unit=el('medRestockUnit')?.value||'',host=el('medRestockPreview');if(host)host.textContent=price!==null&&size&&size>0?`${fmt(price/size)} per ${unit}`:'Enter purchase price and container size.'}
function openMedRestock(mid){injectRestockModal();const m=readMeds().find(x=>String(x.id)===String(mid));if(!m)return;restockId=m.id;el('medRestockName').textContent=`${m.name} • saved label dose stays unchanged`;el('medRestockPrice').value='';el('medRestockSize').value='';el('medRestockUnit').value=[...el('medRestockUnit').options].some(o=>o.value===(m.costUnit||m.unit))?(m.costUnit||m.unit):'mL';el('medRestockDate').value=new Date().toISOString().slice(0,10);el('medRestockVendor').value='';el('medRestockPhoto').value='';restockPreview();el('medRestockModal').classList.remove('hidden')}
function closeMedRestock(){el('medRestockModal')?.classList.add('hidden');restockId=null}
window.openMedRestock=openMedRestock;window.closeMedRestock=closeMedRestock;
function compress(file){return new Promise((res,rej)=>{if(!file)return res('');const u=URL.createObjectURL(file),im=new Image;im.onload=()=>{const s=Math.min(1,900/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(im.width*s));c.height=Math.max(1,Math.round(im.height*s));c.getContext('2d').drawImage(im,0,0,c.width,c.height);URL.revokeObjectURL(u);res(c.toDataURL('image/jpeg',.68))};im.onerror=e=>{URL.revokeObjectURL(u);rej(e)};im.src=u})}
async function saveMedRestock(){const meds=readMeds(),m=meds.find(x=>String(x.id)===String(restockId));if(!m)return;const price=num(el('medRestockPrice').value),size=num(el('medRestockSize').value);if(price===null||size===null||size<=0)return alert('Enter the purchase price and container size.');const p={id:id(),date:el('medRestockDate').value||new Date().toISOString().slice(0,10),vendor:el('medRestockVendor').value.trim(),price,size,unit:el('medRestockUnit').value,costPerUnit:Number((price/size).toFixed(6)),created:new Date().toISOString()};m.purchases=Array.isArray(m.purchases)?m.purchases:[];m.purchases.push(p);m.activePurchaseId=p.id;m.costPerUnit=p.costPerUnit;m.costUnit=p.unit;const file=el('medRestockPhoto').files?.[0];if(file){try{m.photo=await compress(file)}catch(e){console.warn(e)}}writeMeds(meds);closeMedRestock();alert(`${m.name} restocked at ${fmt(p.costPerUnit)} per ${p.unit}.`)}
window.saveMedRestock=saveMedRestock;
function cardId(card){const b=[...card.querySelectorAll('button')].find(x=>/deleteMedication\(/.test(x.getAttribute('onclick')||''));const m=(b?.getAttribute('onclick')||'').match(/deleteMedication\('([^']+)'\)/);return m?.[1]||null}
function decorateCards(){const meds=readMeds(),map=new Map(meds.map(m=>[String(m.id),m]));document.querySelectorAll('#medList .med-card').forEach(card=>{if(card.dataset.costDecorated)return;const mid=cardId(card),m=map.get(String(mid));if(!m)return;card.dataset.costDecorated='1';const p=latestPurchase(m),meta=card.querySelector('.med-meta'),actions=card.querySelector('.med-actions');if(meta){const d=document.createElement('div');d.className='med-cost-line';d.textContent=p?`Current cost: ${fmt(p.costPerUnit)} per ${p.unit} • ${fmt(p.price)} / ${p.size} ${p.unit}${p.date?` • ${p.date}`:''}`:'Purchase cost not entered yet';meta.appendChild(d)}if(actions){const b=document.createElement('button');b.className='softbtn';b.textContent='Restock / Cost';b.onclick=()=>openMedRestock(m.id);actions.insertBefore(b,actions.lastElementChild)}})}
function wrapMenu(){if(typeof window.openFarmMenu!=='function'||window.openFarmMenu.__cvMedicationCosts)return;const old=window.openFarmMenu;const wrapped=function(){const out=old.apply(this,arguments);install();return out};Object.assign(wrapped,old);wrapped.__cvMedicationCosts=true;window.openFarmMenu=wrapped}
function wrapRefresh(){if(typeof window.cvRefreshMedicationCabinet!=='function'||window.cvRefreshMedicationCabinet.__cvMedicationCosts)return;const old=window.cvRefreshMedicationCabinet;const wrapped=function(){const out=old.apply(this,arguments);decorateCards();return out};Object.assign(wrapped,old);wrapped.__cvMedicationCosts=true;window.cvRefreshMedicationCabinet=wrapped}
function install(){injectFields();injectRestockModal();wrapSave();wrapMenu();wrapRefresh();decorateCards()}
install();
})();
