(function(){
if(window.__cvMileageCostsInstalled)return;window.__cvMileageCostsInstalled=true;
const KEY='cv2-mileage-events',DELETE_KEY='cv2-mileage-delete-queue',ECON_KEY='cv2-animal-cost-events',ECON_DELETE_KEY='cv2-animal-cost-delete-queue';
const SPECIAL=new Set(['Livestock Guardian Dog','Horse']);
const DEFAULT_RATE=.76;
const el=id=>document.getElementById(id),herd=()=>typeof cattle!=='undefined'&&Array.isArray(cattle)?cattle:[],core=()=>herd().filter(a=>!SPECIAL.has(a.sex));
const id=()=>typeof newLocalId==='function'?newLocalId():((typeof crypto!=='undefined'&&crypto.randomUUID)?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2));
const safe=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const num=v=>{if(v===null||v===undefined||v==='')return null;const n=Number(v);return Number.isFinite(n)?n:null};
const money=v=>num(v)===null?'—':new Intl.NumberFormat(undefined,{style:'currency',currency:'USD',maximumFractionDigits:2}).format(num(v));
function readArray(k){try{const x=JSON.parse(localStorage.getItem(k)||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function writeArray(k,v){localStorage.setItem(k,JSON.stringify(v))}
function trips(){return readArray(KEY)}
function econ(){return readArray(ECON_KEY)}
function pastureNames(){const s=new Set();for(const a of core())if(String(a.location||'').trim())s.add(String(a.location).trim());if(typeof pastures!=='undefined'&&Array.isArray(pastures))for(const p of pastures)if(p?.name)s.add(String(p.name));return [...s].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}))}
function selectedAnimals(){const scope=el('mileScope')?.value||'all';if(scope==='all')return core();if(scope==='pastures'){const names=[...document.querySelectorAll('.mile-pasture-check:checked')].map(x=>String(x.value).toLowerCase()),set=new Set(names);return core().filter(a=>set.has(String(a.location||'').toLowerCase()))}if(scope==='tags'){const tags=(el('mileTags')?.value||'').split(/[\n,]+/).map(x=>x.trim().toLowerCase()).filter(Boolean),set=new Set(tags);return core().filter(a=>set.has(String(a.tag||'').trim().toLowerCase()))}return[]}
function selectedPastures(){return [...document.querySelectorAll('.mile-pasture-check:checked')].map(x=>x.value)}
function ensure(){if(el('mileageModal'))return;const m=document.createElement('div');m.id='mileageModal';m.className='modal hidden';m.innerHTML=`<div class="sheet" style="max-width:760px"><div class="row"><div><h2 style="margin:0">Ranch Mileage</h2><div class="muted">Allocate ranch-driving cost to the cattle that trip served.</div></div><button class="softbtn" onclick="closeMileageCosts()">Close</button></div><div class="section"><div class="mile-grid"><div><label>Date</label><input id="mileDate" type="date"></div><div><label>Miles</label><input id="mileMiles" inputmode="decimal" placeholder="Example: 34"></div><div><label>Cost / Mile</label><input id="mileRate" inputmode="decimal" value="0.76"></div><div><label>Apply To</label><select id="mileScope"><option value="all">Whole cattle herd</option><option value="pastures">One or more pastures</option><option value="tags">Selected tags</option></select></div><div id="milePastureWrap" class="wide hidden"><label>Pastures checked on this trip</label><div id="milePastures" class="mile-pastures"></div></div><div id="mileTagsWrap" class="wide hidden"><label>Tags</label><textarea id="mileTags" placeholder="3-11, 449, N-T"></textarea></div><div class="wide"><label>Notes</label><input id="mileNotes" placeholder="Feed/check cattle, haul mineral, AI work, etc."></div></div><div class="pc-market-note" style="margin-top:10px">Default benchmark: <b>$0.76/mile</b>, the IRS business mileage rate effective July 1, 2026. It is editable, and you can replace it later with your own pickup's actual cost per mile.</div><div id="milePreview" class="mile-preview"></div><button class="greenbtn" style="width:100%" onclick="saveMileageCost()">Save Trip & Allocate to These Cattle</button></div><div class="section"><h3 style="margin-top:0">Mileage History</h3><div id="mileHistory" class="mile-history"></div></div></div>`;document.body.appendChild(m);['mileMiles','mileRate','mileTags'].forEach(k=>el(k)?.addEventListener('input',preview));el('mileScope').addEventListener('change',scopeChanged)}
function reset(){el('mileDate').value=new Date().toISOString().slice(0,10);el('mileMiles').value='';el('mileRate').value=String(DEFAULT_RATE);el('mileScope').value='all';el('mileTags').value='';el('mileNotes').value='';renderPastureChecks();scopeChanged()}
function renderPastureChecks(){const host=el('milePastures');if(!host)return;host.innerHTML=pastureNames().map(n=>`<label><input class="mile-pasture-check" type="checkbox" value="${safe(n)}"><span>${safe(n)}</span></label>`).join('');host.querySelectorAll('input').forEach(x=>x.addEventListener('change',preview))}
function scopeChanged(){const s=el('mileScope').value;el('milePastureWrap').classList.toggle('hidden',s!=='pastures');el('mileTagsWrap').classList.toggle('hidden',s!=='tags');preview()}
function preview(){const miles=num(el('mileMiles')?.value),rate=num(el('mileRate')?.value),animals=selectedAnimals(),total=miles!==null&&rate!==null?miles*rate:null,per=animals.length&&total!==null?total/animals.length:null,host=el('milePreview');if(host)host.innerHTML=`<div><span>Miles</span><b>${miles===null?'—':miles.toFixed(1)}</b></div><div><span>Trip Cost</span><b>${money(total)}</b></div><div><span>Cattle Charged</span><b>${animals.length}</b></div><div><span>Cost / Head</span><b>${money(per)}</b></div>`}
function openMileageCosts(){ensure();reset();renderHistory();el('mileageModal').classList.remove('hidden')}
function closeMileageCosts(){el('mileageModal')?.classList.add('hidden')}
window.openMileageCosts=openMileageCosts;window.closeMileageCosts=closeMileageCosts;
function saveMileageCost(){const miles=num(el('mileMiles').value),rate=num(el('mileRate').value),animals=selectedAnimals();if(miles===null||miles<0)return alert('Enter the ranch miles driven.');if(rate===null||rate<0)return alert('Enter the cost per mile.');if(!animals.length)return alert('No cattle match that mileage allocation.');const total=miles*rate,totalCents=Math.round(total*100),base=Math.floor(totalCents/animals.length),rem=totalCents-base*animals.length,eventId=id(),date=el('mileDate').value||new Date().toISOString().slice(0,10),now=new Date().toISOString(),pastures=el('mileScope').value==='pastures'?selectedPastures():[],rec={id:eventId,date,miles,ratePerMile:rate,totalCost:Number((totalCents/100).toFixed(2)),allocationScope:el('mileScope').value,pastureNames:pastures,animalCount:animals.length,costPerAnimal:Number((total/animals.length).toFixed(4)),allocationAnimalIds:animals.map(a=>String(a.id)),rateSource:Math.abs(rate-DEFAULT_RATE)<.00001?'IRS business mileage benchmark effective 2026-07-01':'User-entered mileage rate',notes:el('mileNotes').value.trim(),createdAt:now,updatedAt:now},beforeTrips=trips(),beforeEcon=econ(),alloc=animals.map((a,i)=>({id:`${eventId}:${a.id}`,animalId:String(a.id),date,category:'Fuel / Equipment',description:`Ranch mileage — ${miles} mi @ ${money(rate)}/mi${pastures.length?` • ${pastures.join(', ')}`:''}${rec.notes?` • ${rec.notes}`:''}`,amount:(base+(i<rem?1:0))/100,sourceType:'ranch-economics-mileage',sourceId:eventId,updatedAt:now}));try{writeArray(KEY,[...beforeTrips,rec]);writeArray(ECON_KEY,[...beforeEcon,...alloc]);window.dispatchEvent(new Event('cv-mileage-changed'));window.dispatchEvent(new Event('cv-finance-changed'));window.dispatchEvent(new Event('cv-local-change'));renderHistory();reset();alert(`${money(rec.totalCost)} mileage cost saved across ${animals.length} cattle — ${money(rec.costPerAnimal)} per head.`)}catch(e){console.error(e);try{writeArray(KEY,beforeTrips);writeArray(ECON_KEY,beforeEcon)}catch{}alert('That mileage trip could not be saved on this device.')}}
window.saveMileageCost=saveMileageCost;
function renderHistory(){const host=el('mileHistory');if(!host)return;const rows=trips().slice().sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))||String(b.createdAt||'').localeCompare(String(a.createdAt||'')));host.innerHTML=rows.length?rows.map(x=>`<div class="mile-row"><div><b>${safe(x.date||'')} • ${safe(x.miles)} miles</b><div class="meta">${money(x.ratePerMile)}/mile${Array.isArray(x.pastureNames)&&x.pastureNames.length?` • ${safe(x.pastureNames.join(', '))}`:''}${x.notes?`<br>${safe(x.notes)}`:''}<br>${safe(x.rateSource||'')}</div></div><div class="mile-money"><b>${money(x.totalCost)}</b><small>${Number(x.animalCount||0)} head • ${money(x.costPerAnimal)} / head</small></div><div class="mile-actions"><button class="softbtn" onclick="deleteMileageCost('${safe(x.id)}')">Remove</button></div></div>`).join(''):'<div class="muted">No ranch mileage recorded yet.</div>'}
function deleteMileageCost(eid){const row=trips().find(x=>String(x.id)===String(eid));if(!row||!confirm(`Remove the ${row.miles}-mile trip and its per-cow costs?`))return;const oldTrips=trips(),oldEcon=econ(),removed=oldEcon.filter(x=>String(x.sourceId||'')===String(eid));try{writeArray(KEY,oldTrips.filter(x=>String(x.id)!==String(eid)));writeArray(ECON_KEY,oldEcon.filter(x=>String(x.sourceId||'')!==String(eid)));const q=readArray(DELETE_KEY);if(!q.includes(String(eid)))q.push(String(eid));writeArray(DELETE_KEY,q);const eq=readArray(ECON_DELETE_KEY);for(const x of removed)if(!eq.includes(String(x.id)))eq.push(String(x.id));writeArray(ECON_DELETE_KEY,eq);window.dispatchEvent(new Event('cv-mileage-changed'));window.dispatchEvent(new Event('cv-finance-changed'));window.dispatchEvent(new Event('cv-local-change'));renderHistory()}catch(e){console.error(e);try{writeArray(KEY,oldTrips);writeArray(ECON_KEY,oldEcon)}catch{}alert('That mileage trip could not be removed.')}}
window.deleteMileageCost=deleteMileageCost;
function injectMenus(){const econ=el('econFarmMenu');if(econ&&!el('mileFarmBtn')){const grid=econ.querySelector('.farm-menu-grid');if(grid){const b=document.createElement('button');b.id='mileFarmBtn';b.className='softbtn';b.type='button';b.innerHTML='<b>Ranch Mileage</b><br><span class="muted">Driving cost allocated per cow</span>';b.onclick=()=>{openMileageCosts();window.closeFarmMenu?.()};grid.appendChild(b)}}const actions=el('econDashboard')?.querySelector('.econ-actions');if(actions&&!el('mileEconBtn')){const b=document.createElement('button');b.id='mileEconBtn';b.className='softbtn';b.type='button';b.textContent='Ranch Mileage';b.onclick=openMileageCosts;actions.appendChild(b)}}
function install(){ensure();injectMenus()}
window.addEventListener('cv-mileage-restored',()=>{if(el('mileageModal')&&!el('mileageModal').classList.contains('hidden'))renderHistory()});install();
})();
