(function(){
let paperRows=[];
function syncPaperRows(rows){paperRows=rows;window.paperRows=paperRows}
function loadTesseract(){return new Promise((resolve,reject)=>{if(window.Tesseract)return resolve(window.Tesseract);const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.onload=()=>resolve(window.Tesseract);s.onerror=()=>reject(new Error('Could not load handwriting reader'));document.head.appendChild(s)})}
function parsePaperText(text){const lines=String(text||'').split(/\n+/).map(x=>x.trim()).filter(Boolean);const rows=[];for(const line of lines){const m=line.match(/^\s*#?\s*([A-Za-z]?\d+(?:-\d+)?)\b\s*[-:,.]?\s*(.*)$/);if(!m)continue;const tag=m[1].toUpperCase(),rest=m[2].trim(),low=rest.toLowerCase();let status='Unknown',sex='Cow',calved=false,calfSex='',date='';if(/\b(calved|had calf|had a calf)\b/.test(low)){status='Calved';calved=true}else if(/\b(pregnant|preg)\b/.test(low))status='Pregnant';else if(/\bbred\b/.test(low))status='Bred';else if(/\bopen\b/.test(low))status='Open';else if(/\bdry\b/.test(low))status='Dry';if(/heifer calf/.test(low))calfSex='Heifer';else if(/bull calf/.test(low))calfSex='Bull';const dm=rest.match(/\b(\d{1,2})[\/-](\d{1,2})(?:[\/-](\d{2,4}))?\b/);if(dm){let y=dm[3]?Number(dm[3]):new Date().getFullYear();if(y<100)y+=2000;const mo=Number(dm[1]),day=Number(dm[2]);if(mo>=1&&mo<=12&&day>=1&&day<=31)date=`${String(y).padStart(4,'0')}-${String(mo).padStart(2,'0')}-${String(day).padStart(2,'0')}`}
rows.push({tag,rest,status,sex,calved,calfSex,date,include:true});}return rows}
function renderPaperRows(){const el=$('paperRows');if(!el)return;el.innerHTML=paperRows.length?paperRows.map((r,i)=>`<div style="border:1px solid #d7d7d0;border-radius:10px;padding:10px;margin:8px 0;background:#fff"><label style="display:flex;gap:8px;align-items:center"><input type="checkbox" ${r.include?'checked':''} onchange="paperRows[${i}].include=this.checked"><b>Tag ${esc(r.tag)}</b></label><div class="grid2" style="margin-top:8px"><div><label>Status</label><select onchange="paperRows[${i}].status=this.value"><option ${r.status==='Unknown'?'selected':''}>Unknown</option><option ${r.status==='Calved'?'selected':''}>Calved</option><option ${r.status==='Bred'?'selected':''}>Bred</option><option ${r.status==='Pregnant'?'selected':''}>Pregnant</option><option ${r.status==='Open'?'selected':''}>Open</option><option ${r.status==='Dry'?'selected':''}>Dry</option></select></div><div><label>Date</label><input type="date" value="${esc(r.date||'')}" onchange="paperRows[${i}].date=this.value"></div></div><label>What the page appeared to say</label><input value="${esc(r.rest)}" oninput="paperRows[${i}].rest=this.value"><div class="muted" style="margin-top:5px">${r.calved?`Calving detected${r.calfSex?` • ${esc(r.calfSex)} calf`:''}`:'No calving phrase detected'}</div></div>`).join(''):'<div class="muted">No tag-number lines were recognized yet. You can edit the text above and tap Re-read Text.</div>'}
async function readPaperPhoto(){const f=$('paperPhoto').files[0];if(!f)return alert('Take or choose a picture of the herd-record page first.');$('paperStatus').textContent='Reading page… handwriting can take a little while.';try{const T=await loadTesseract();const out=await T.recognize(f,'eng',{logger:m=>{if(m.status==='recognizing text')$('paperStatus').textContent=`Reading page… ${Math.round((m.progress||0)*100)}%`;}});const text=out?.data?.text||'';$('paperText').value=text;syncPaperRows(parsePaperText(text));renderPaperRows();$('paperStatus').textContent=`Found ${paperRows.length} possible animal record${paperRows.length===1?'':'s'}. Review before importing.`}catch(e){console.error(e);$('paperStatus').textContent='Automatic reading could not run. You can still type or use voice dictation in the text box, then tap Re-read Text.'}}
function rereadPaperText(){syncPaperRows(parsePaperText($('paperText').value));renderPaperRows();$('paperStatus').textContent=`Found ${paperRows.length} possible animal record${paperRows.length===1?'':'s'}. Review before importing.`}
function importPaperRows(){const rows=paperRows.filter(r=>r.include);if(!rows.length)return alert('Select at least one record to import.');let created=0,updated=0,duplicates=0;for(const r of rows){let a=cattle.find(x=>String(x.tag||'').toLowerCase()===r.tag.toLowerCase());const note=`Paper record: ${r.rest}`;if(!a){a=norm({id:(typeof newLocalId==='function'?newLocalId():Date.now()+Math.random()),tag:r.tag,sex:'Cow',status:r.status,notes:note,created:new Date().toISOString()});cattle.push(a);created++;}else{if(r.status&&r.status!=='Unknown')a.status=r.status;const lines=String(a.notes||'').split('\n');if(!lines.includes(note))a.notes=(a.notes?`${a.notes}\n`:'')+note;else duplicates++;updated++;}if(r.calved){a.calvings=Array.isArray(a.calvings)?a.calvings:[];const exists=a.calvings.some(c=>c.paperRecord===r.rest&&String(c.date||'')===String(r.date||''));if(!exists)a.calvings.push({date:r.date||'',tag:'',sex:r.calfSex||'Unknown',notes:note,paperRecord:r.rest});else duplicates++;}}save();closePaperImport();alert(`${rows.length} paper record${rows.length===1?'':'s'} reviewed and imported. ${created} new animal${created===1?'':'s'}, ${updated} existing record${updated===1?'':'s'} checked${duplicates?`, ${duplicates} duplicate entr${duplicates===1?'y was':'ies were'} skipped`:''}.`)}
function closePaperImport(){$('paperImportModal')?.classList.add('hidden')}
function openPaperImport(){if(typeof closeFarmMenu==='function')closeFarmMenu();$('paperImportModal').classList.remove('hidden');$('paperStatus').textContent='';$('paperPhoto').value='';$('paperText').value='';syncPaperRows([]);renderPaperRows()}
window.openPaperImport=openPaperImport;window.closePaperImport=closePaperImport;window.readPaperPhoto=readPaperPhoto;window.rereadPaperText=rereadPaperText;window.importPaperRows=importPaperRows;syncPaperRows([]);
const m=document.createElement('div');m.id='paperImportModal';m.className='modal hidden';m.innerHTML=`<div class="sheet"><div class="row"><div><h2>Import Paper Herd Records</h2><div class="muted">Turn a handwritten herd sheet into draft animal records.</div></div><button class="softbtn" onclick="closePaperImport()">Close</button></div><div style="padding:12px;border-radius:10px;background:#fff8dc;border:1px solid #e3cf88;margin:12px 0"><b>Experimental handwriting reader</b><br>This may not be 100% accurate at this time. Please try it out, review every record before importing, and send us feedback so we can make it better as we go.</div><label>Take or choose a picture of the page</label><input id="paperPhoto" type="file" accept="image/*" capture="environment"><button class="greenbtn" style="width:100%;margin-top:10px" onclick="readPaperPhoto()">Read Handwritten Page</button><div id="paperStatus" class="muted" style="margin:10px 0"></div><label>What Cattle Vision read</label><textarea id="paperText" style="min-height:130px" placeholder="Recognized handwriting will appear here. You can correct it manually or use phone dictation."></textarea><button class="softbtn" style="width:100%;margin-top:8px" onclick="rereadPaperText()">Re-read Text</button><div id="paperRows" style="margin-top:12px"></div><button class="greenbtn" style="width:100%;margin-top:12px" onclick="importPaperRows()">Confirm & Import Selected Records</button></div>`;document.body.appendChild(m);
})();