(function(){
const URL='https://rtyiqggxruwejqqyqtmv.supabase.co';
const KEY='sb_publishable_BxkgX1XJz8o_PsTb_LcVDQ_7DR6oHOk';
let resetClient=null,shown=false;
const hasRecoveryHint=()=>/([?#&]type=recovery\b|[?&]code=)/i.test(location.href);
function ensureModal(){if(document.getElementById('cvPasswordResetModal'))return;const m=document.createElement('div');m.id='cvPasswordResetModal';m.className='modal hidden';m.innerHTML=`<div class="sheet" style="max-width:560px"><h2 style="margin-top:0">Choose a New Password</h2><p>You opened a Cattle Vision password-reset link. Enter the new password you want to use for your cloud account.</p><label>New Password</label><input id="cvNewPassword" type="password" autocomplete="new-password" placeholder="New password"><label style="margin-top:10px">Confirm New Password</label><input id="cvNewPassword2" type="password" autocomplete="new-password" placeholder="Confirm new password"><button class="greenbtn" style="width:100%;margin-top:14px" onclick="cvFinishPasswordReset()">Save New Password</button><button class="softbtn" style="width:100%;margin-top:10px" onclick="cvCancelPasswordReset()">Cancel</button><div id="cvPasswordResetStatus" class="muted" style="margin-top:10px"></div></div>`;document.body.appendChild(m)}
function show(){ensureModal();shown=true;document.getElementById('cvPasswordResetModal')?.classList.remove('hidden');setTimeout(()=>document.getElementById('cvNewPassword')?.focus(),50)}
function cleanUrl(){try{history.replaceState({},document.title,location.origin+location.pathname)}catch{}}
async function init(){if(!window.supabase?.createClient)return;ensureModal();resetClient=window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});resetClient.auth.onAuthStateChange((event)=>{if(event==='PASSWORD_RECOVERY')show()});if(hasRecoveryHint()){setTimeout(async()=>{if(shown)return;const {data}=await resetClient.auth.getSession();if(data?.session)show()},700)}}
window.cvFinishPasswordReset=async function(){const a=document.getElementById('cvNewPassword')?.value||'',b=document.getElementById('cvNewPassword2')?.value||'',s=document.getElementById('cvPasswordResetStatus');if(a.length<8){if(s)s.textContent='Use at least 8 characters.';return}if(a!==b){if(s)s.textContent='Those passwords do not match.';return}if(s)s.textContent='Saving new password…';const {error}=await resetClient.auth.updateUser({password:a});if(error){if(s)s.textContent='Could not update password: '+error.message;return}if(s)s.textContent='Password updated successfully.';cleanUrl();setTimeout(()=>{document.getElementById('cvPasswordResetModal')?.classList.add('hidden');alert('Your Cattle Vision password has been changed. You can now use the new password to sign in.')},400)};
window.cvCancelPasswordReset=function(){cleanUrl();document.getElementById('cvPasswordResetModal')?.classList.add('hidden')};
init();
})();