let pastures=JSON.parse(localStorage.getItem('cv2-pastures')||'[]');
let pasturePhotoTarget='';
function savePastures(){localStorage.setItem('cv2-pastures',JSON.stringify(pastures));renderPastureOptions();}
function harvestPastures(){for(const a of cattle){const n=(a.location||'').trim();if(n&&!pastures.some(p=>p.name.toLowerCase()===n.toLowerCase()))pastures.push({id:String(Date.now()+Math.random()),name:n});}savePastures();}
function renderPastureOptions(){const dl=$('pastureOptions');if(dl)dl.innerHTML=pastures.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(p=>`<option value="${esc(p.name)}"></option>`).join('');}
function openPastures(){harvestPastures();renderPastureManager();$('pastureModal').classList.remove('hidden');}
function closePastures(){$('pastureModal').classList.add('hidden');}
function addPasture(){const input=$('newPastureName'),name=input.value.trim();if(!name)return alert('Enter a pasture name.');if(pastures.some(p=>p.name.toLowerCase()===name.toLowerCase()))return alert('That pasture already exists.');pastures.push({id:String(Date.now()+Math.random()),name});input.value='';savePastures();renderPastureManager();}
function deletePasture(id){const p=pastures.find(x=>String(x.id)===String(id));if(!p)return;const count=cattle.filter(a=>(a.location||'').toLowerCase()===p.name.toLowerCase()).length;if(count&&!confirm(`${count} animal${count===1?' is':'s are'} assigned to ${p.name}. Remove the pasture and leave those cattle unassigned?`))return;if(count)cattle.forEach(a=>{if((a.location||'').toLowerCase()===p.name.toLowerCase())setAnimalPasture(a,'');});pastures=pastures.filter(x=>String(x.id)!==String(id));savePastures();save();renderPastureManager();}
function setAnimalPasture(a,pastureName){if(!a)return;const from=(a.location||'').trim(),to=(pastureName||'').trim();if(from===to)return;a.locationHistory=Array.isArray(a.locationHistory)?a.locationHistory:[];a.locationHistory.push({from,to,date:new Date().toISOString()});a.location=to;}
function assignAnimalToPasture(animalId,pastureName){const a=cattle.find(x=>String(x.id)===String(animalId));if(!a)return;setAnimalPasture(a,pastureName);save();renderPastureManager();}
function bulkAssignPasture(){const p=$('bulkPastureSelect').value;if(!p)return alert('Choose the pasture you want to move the selected cattle to.');const checks=[...document.querySelectorAll('.pasture-animal-check:checked')];if(!checks.length)return alert('Select at least one animal.');checks.forEach(c=>{const a=cattle.find(x=>String(x.id)===String(c.value));setAnimalPasture(a,p);});save();renderPastureManager();alert(`${checks.length} animal${checks.length===1?'':'s'} moved to ${p}.`);}
function filterPastureAnimals(name){const f=$('pastureSourceFilter');if(f){f.value=name;renderPastureAnimalRows();}}
function renderPastureAnimalRows(){const names=pastures.slice().sort((a,b)=>a.name.localeCompare(b.name));const source=$('pastureSourceFilter')?.value||'';let rows=cattle.slice().sort((a,b)=>String(a.tag).localeCompare(String(b.tag),undefined,{numeric:true}));if(source==='__unassigned__')rows=rows.filter(a=>!(a.location||'').trim());else if(source)rows=rows.filter(a=>(a.location||'').toLowerCase()===source.toLowerCase());const animals=$('pastureAnimalList');if(!animals)return;animals.innerHTML=rows.length?rows.map(a=>`<label class="pasture-animal-row"><input class="pasture-animal-check" type="checkbox" value="${a.id}"><span><b>${a.sex==='Livestock Guardian Dog'?'Guardian Dog':'Tag '+esc(a.tag||'N-T')}</b><small>${esc(a.location||'Unassigned')}</small></span><select onchange="assignAnimalToPasture('${a.id}',this.value)"><option value="">Unassigned</option>${names.map(p=>`<option value="${esc(p.name)}" ${(a.location||'')===p.name?'selected':''}>${esc(p.name)}</option>`).join('')}</select></label>`).join(''):'<div class="empty">No cattle match this pasture filter.</div>';}
function startPasturePhotoUpload(name){pasturePhotoTarget=name;const input=$('pasturePhotoInput');if(!input)return;input.value='';input.click();}
function handlePasturePhotoFiles(e){const files=Array.from(e.target.files||[]);if(!files.length)return;if(typeof openBulkSorter!=='function')return alert('Bulk photo sorter is unavailable.');closePastures();openBulkSorter(files,pasturePhotoTarget);pasturePhotoTarget='';}
function renderPastureManager(){renderPastureOptions();const list=$('pastureList');const names=pastures.slice().sort((a,b)=>a.name.localeCompare(b.name));list.innerHTML=names.length?names.map(p=>{const animals=cattle.filter(a=>(a.location||'').toLowerCase()===p.name.toLowerCase()).sort((a,b)=>String(a.tag).localeCompare(String(b.tag),undefined,{numeric:true}));const safe=String(p.name).replace(/'/g,"\\'");return `<div class="pasture-card"><div class="pasture-card-head"><div><strong>${esc(p.name)}</strong><span>${animals.length} head</span></div><button class="softbtn" onclick="deletePasture('${p.id}')">Remove</button></div><div class="pasture-card-actions"><button class="greenbtn" onclick="startPasturePhotoUpload('${safe}')">Upload Herd Photos</button><button class="softbtn" onclick="filterPastureAnimals('${safe}')">Select / Move Cattle</button><button class="softbtn" onclick="openHerdWork('${safe}')">Work Entire Herd</button></div><div class="pasture-tags">${animals.length?animals.map(a=>`<button onclick="openRecord('${a.id}');closePastures()">${a.sex==='Livestock Guardian Dog'?'Guardian Dog':'Tag '+esc(a.tag||'N-T')}</button>`).join(''):'<span class="muted">No cattle assigned yet.</span>'}</div></div>`}).join(''):'<div class="empty">No pastures yet. Add your first pasture above.</div>';
const source=$('pastureSourceFilter'),oldSource=source?.value||'';if(source){source.innerHTML='<option value="">All cattle</option><option value="__unassigned__">Unassigned cattle</option>'+names.map(p=>`<option value="${esc(p.name)}">${esc(p.name)}</option>`).join('');if([...source.options].some(o=>o.value===oldSource))source.value=oldSource;}
const select=$('bulkPastureSelect');if(select)select.innerHTML='<option value="">Move selected cattle to...</option>'+names.map(p=>`<option value="${esc(p.name)}">${esc(p.name)}</option>`).join('');renderPastureAnimalRows();}
harvestPastures();
(function loadHerdWork(){if(document.querySelector('script[data-herd-work]'))return;const s=document.createElement('script');s.src='herd-work.js?v=1';s.dataset.herdWork='1';document.body.appendChild(s);})();
(function loadGuardianGrass(){if(document.querySelector('script[data-guardian-grass]'))return;const s=document.createElement('script');s.src='guardian-grass.js?v=1';s.dataset.guardianGrass='1';document.body.appendChild(s);})();