let pastures=JSON.parse(localStorage.getItem('cv2-pastures')||'[]');
function savePastures(){localStorage.setItem('cv2-pastures',JSON.stringify(pastures));renderPastureOptions();}
function harvestPastures(){for(const a of cattle){const n=(a.location||'').trim();if(n&&!pastures.some(p=>p.name.toLowerCase()===n.toLowerCase()))pastures.push({id:String(Date.now()+Math.random()),name:n});}savePastures();}
function renderPastureOptions(){const dl=$('pastureOptions');if(dl)dl.innerHTML=pastures.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(p=>`<option value="${esc(p.name)}"></option>`).join('');}
function openPastures(){harvestPastures();renderPastureManager();$('pastureModal').classList.remove('hidden');}
function closePastures(){$('pastureModal').classList.add('hidden');}
function addPasture(){const input=$('newPastureName'),name=input.value.trim();if(!name)return alert('Enter a pasture name.');if(pastures.some(p=>p.name.toLowerCase()===name.toLowerCase()))return alert('That pasture already exists.');pastures.push({id:String(Date.now()+Math.random()),name});input.value='';savePastures();renderPastureManager();}
function deletePasture(id){const p=pastures.find(x=>String(x.id)===String(id));if(!p)return;const count=cattle.filter(a=>(a.location||'').toLowerCase()===p.name.toLowerCase()).length;if(count&&!confirm(`${count} animal${count===1?' is':'s are'} assigned to ${p.name}. Remove the pasture and leave those cattle unassigned?`))return;if(count)cattle.forEach(a=>{if((a.location||'').toLowerCase()===p.name.toLowerCase())a.location='';});pastures=pastures.filter(x=>String(x.id)!==String(id));savePastures();save();renderPastureManager();}
function assignAnimalToPasture(animalId,pastureName){const a=cattle.find(x=>String(x.id)===String(animalId));if(!a)return;a.location=pastureName;save();renderPastureManager();}
function bulkAssignPasture(){const p=$('bulkPastureSelect').value;if(!p)return alert('Choose a pasture.');const checks=[...document.querySelectorAll('.pasture-animal-check:checked')];if(!checks.length)return alert('Select at least one animal.');checks.forEach(c=>{const a=cattle.find(x=>String(x.id)===String(c.value));if(a)a.location=p;});save();renderPastureManager();alert(`${checks.length} animal${checks.length===1?'':'s'} assigned to ${p}.`);}
function renderPastureManager(){renderPastureOptions();const list=$('pastureList');const names=pastures.slice().sort((a,b)=>a.name.localeCompare(b.name));list.innerHTML=names.length?names.map(p=>{const animals=cattle.filter(a=>(a.location||'').toLowerCase()===p.name.toLowerCase()).sort((a,b)=>String(a.tag).localeCompare(String(b.tag),undefined,{numeric:true}));return `<div class="pasture-card"><div class="pasture-card-head"><div><strong>${esc(p.name)}</strong><span>${animals.length} head</span></div><button class="softbtn" onclick="deletePasture('${p.id}')">Remove</button></div><div class="pasture-tags">${animals.length?animals.map(a=>`<button onclick="openRecord('${a.id}');closePastures()">Tag ${esc(a.tag)}</button>`).join(''):'<span class="muted">No cattle assigned yet.</span>'}</div></div>`}).join(''):'<div class="empty">No pastures yet. Add your first pasture above.</div>';
const select=$('bulkPastureSelect');select.innerHTML='<option value="">Choose pasture...</option>'+names.map(p=>`<option value="${esc(p.name)}">${esc(p.name)}</option>`).join('');
const animals=$('pastureAnimalList');animals.innerHTML=cattle.length?cattle.slice().sort((a,b)=>String(a.tag).localeCompare(String(b.tag),undefined,{numeric:true})).map(a=>`<label class="pasture-animal-row"><input class="pasture-animal-check" type="checkbox" value="${a.id}"><span><b>Tag ${esc(a.tag)}</b><small>${esc(a.location||'Unassigned')}</small></span><select onchange="assignAnimalToPasture('${a.id}',this.value)"><option value="">Unassigned</option>${names.map(p=>`<option value="${esc(p.name)}" ${a.location===p.name?'selected':''}>${esc(p.name)}</option>`).join('')}</select></label>`).join(''):'<div class="empty">Add cattle first, then assign them to pastures here.</div>';}
harvestPastures();